import { MarketingLesson } from '../types';

/**
 * Digital Marketing Strategy — Module 2 (Social) and Module 3 (PPC) lessons,
 * expanded for complete beginners.
 */
export const modules2And3Lessons: Record<string, MarketingLesson> = {
  // ─── Module 2: Social ─────────────────────────────────────────────────
  "dm-m2-l1": {
    title: "Content Pillars and Scheduling Strategies",
    objective: "design content pillars and a sustainable calendar.",
    content: [
      { type: "heading", value: "In simple terms" },
      { type: "text", value: "Think of a local radio station. It does not decide every morning what to broadcast. It has regular shows: news at 8, music at 9, a phone-in at 12. Listeners know what to expect, and the presenters always know what to prepare." },
      { type: "text", value: "Content pillars are your regular shows. A content calendar is your broadcast timetable. Together they make it easy to post regularly without panic." },
      { type: "heading", value: "Key terms" },
      { type: "table", headers: ["Term", "Plain meaning"], rows: [
        ["Content pillar", "One of three to five main topics your account always posts about."],
        ["Content calendar", "A plan (often a simple spreadsheet) showing what you will post, where, and on which day."],
        ["Batching", "Creating many posts in one sitting instead of one post each day."],
        ["Scheduling", "Setting a post to publish automatically at a future date and time."],
        ["Repurposing", "Taking one idea and reshaping it to suit a different platform."],
        ["Asset / artefact", "The finished thing you post: the image, video or written text."],
        ["Engagement", "Any interaction with a post: likes, comments, shares, saves, clicks."],
        ["Meta Business Suite", "Meta's free tool for managing and scheduling Facebook and Instagram posts in one place."],
      ] },
      { type: "heading", value: "Why consistency matters most" },
      { type: "text", value: "Most social media accounts fail because they are inconsistent, not because the content is bad." },
      { type: "text", value: "Imagine two accounts. Account A posts every day for three weeks, then disappears for two months. Account B posts twice a week, every week, without stopping. Account B usually does better. Followers learn to expect it, and the platforms keep showing its posts." },
      { type: "text", value: "Pillars and a calendar exist for one reason: to make that kind of consistency possible." },
      { type: "heading", value: "Content pillars" },
      { type: "text", value: "Pillars are three to five themes that you post about again and again." },
      { type: "text", value: "They solve the \"blank page\" problem. You never have to invent a post from nothing. You only have to decide what to post inside a theme you already know." },
      { type: "example", title: "Pillars for a project-management tool", value: "1. Practical how-to    — workflows, templates, tips\n2. Customer stories    — proof, outcomes, before and after\n3. Industry commentary — opinions on trends, hiring, remote work\n4. Behind the scenes   — how the team works, product decisions\n\nEvery post belongs to one pillar. If it fits none, question whether\nit should be posted at all." },
      { type: "example", title: "Pillars for Rosie's Bakery (a small high-street bakery)", value: "1. Bake of the day     — photos and short videos of fresh bakes\n2. How we make it      — dough folding, icing a cake, early starts\n3. Customer moments    — birthday cakes, regulars, reviews (with permission)\n4. Offers and news     — new menu items, holiday opening hours\n\nPillars 1-3 give value or entertainment. Pillar 4 asks people to buy.\nThat keeps the account roughly 4 parts giving to 1 part asking." },
      { type: "heading", value: "Ratio and restraint" },
      { type: "text", value: "A common guideline says about four out of every five posts should give value (help, teach, entertain). About one in five can ask for something (buy, book, sign up)." },
      { type: "text", value: "The exact numbers are not important. The idea is. An account that only sells gets ignored, because nobody has a reason to follow it." },
      { type: "compare", columns: [
        { title: "Sustainable plan", subtitle: "Works for months", tone: "olive", items: [
          "Three posts a week, every week.",
          "Posts written in one batch every two weeks.",
          "Every post fits a clear pillar.",
          "Each platform gets a version made for it.",
          "Most posts give value; a few ask for a sale.",
        ] },
        { title: "Burnout plan", subtitle: "Stops after a few weeks", tone: "rose", items: [
          "Two posts a day, until the owner gets busy.",
          "Each post invented on the morning it goes out.",
          "Random topics with no pattern.",
          "The same image and caption copied everywhere.",
          "Almost every post says \"buy now\".",
        ] },
      ] },
      { type: "heading", value: "Sustainable scheduling" },
      { type: "list", items: [
        "Choose a posting frequency you can keep up during a bad, busy week, not a good one.",
        "Batch your work. Write two weeks of posts in one session instead of improvising every day.",
        "Schedule posts in advance, but leave space to react to anything timely (news, a local event, the weather).",
        "Track which pillars perform best, and slowly shift your mix towards them.",
      ] },
      { type: "alert", value: "Posting the identical asset to every platform performs poorly. A LinkedIn post and an Instagram post have different formats, lengths and audience expectations. Repurpose the idea; do not copy the artefact." },
      { type: "example", title: "Repurposing one idea for Rosie's Bakery", value: "Idea: \"How we make our sourdough\"\n\nInstagram  -> a 20-second Reel of the dough being shaped, short caption\nFacebook   -> 3 photos plus a friendly paragraph and opening hours\nLinkedIn   -> (only if relevant) a post about starting a small food business\nEmail      -> a short story in the monthly newsletter\n\nOne idea, four versions. Each one suits its platform." },
      { type: "steps", title: "Schedule a week of posts in Meta Business Suite (free)", steps: [
        { label: "Open Meta Business Suite", text: "Go to business.facebook.com and choose your business. You need a Facebook Page, and ideally your Instagram professional account connected to it." },
        { label: "Go to Content or Planner", text: "Choose Content in the left menu (or Planner, which shows a calendar view). The exact menu names can change slightly over time." },
        { label: "Click Create post", text: "Tick where it should go: your Facebook Page, your Instagram account, or both." },
        { label: "Add media and text", text: "Upload your photo or video and write the caption. Use the option to customise the text for each platform so they are not identical." },
        { label: "Choose Schedule", text: "Instead of Publish now, open the scheduling options and pick a date and time. Business Suite may suggest active times when your audience is usually online." },
        { label: "Save and repeat", text: "Schedule the rest of the week's posts the same way, then check the Planner to see the whole week at a glance." },
      ] },
      { type: "warning", value: "Common beginner mistakes: (1) Starting with a posting frequency that is too high, then giving up. (2) Having no pillars, so every day starts with \"what shall I post?\". (3) Copying the same post to every platform. (4) Scheduling everything and never checking the comments. (5) Only posting promotions. (6) Never looking at which posts actually worked." },
      { type: "heading", value: "Try it yourself" },
      { type: "list", ordered: true, items: [
        "Pick a real or imaginary small business (you can use Rosie's Bakery).",
        "Write down three to five content pillars for it, with one sentence explaining each.",
        "Under each pillar, write two post ideas. You now have 6-10 ideas.",
        "Decide a frequency you could keep on a busy week (for example, three posts a week).",
        "Draw a simple two-week table (Day | Platform | Pillar | Post idea) and fill it in.",
        "Check the ratio: how many posts give value, and how many ask for a sale?",
      ] },
      { type: "heading", value: "Check your understanding" },
      { type: "list", items: [
        "Why does posting twice a week forever usually beat posting daily for three weeks? (Consistency builds audience habits and steady reach; stopping loses both.)",
        "What problem do content pillars solve? (The blank-page problem: you always know which themes to post within.)",
        "Should you post the exact same image and caption on Instagram and LinkedIn? (No. Reuse the idea, but adapt the format, length and tone for each platform.)",
      ] },
    ],
    takeaways: [
      "Inconsistency, not content quality, is the usual reason social accounts fail.",
      "Three to five content pillars remove the blank-page problem.",
      "Give far more than you ask: roughly four value posts for every sales post.",
      "Pick a frequency you can keep on a bad week, and batch your writing.",
      "Repurpose ideas across platforms rather than duplicating posts.",
    ],
  },

  "dm-m2-l2": {
    title: "Algorithm Optimization (LinkedIn, Instagram)",
    objective: "understand what social algorithms optimise for and work with it honestly.",
    content: [
      { type: "heading", value: "In simple terms" },
      { type: "text", value: "Imagine a shopkeeper who decides which items go in the shop window. They watch customers. Items that make people stop, look closely and talk about them stay in the window. Items that everyone walks past get moved to the back." },
      { type: "text", value: "A social media algorithm is that shopkeeper. It watches how people react to your post, then decides whether to show it to more people or fewer." },
      { type: "heading", value: "Key terms" },
      { type: "table", headers: ["Term", "Plain meaning"], rows: [
        ["Algorithm", "The automatic system a platform uses to decide which posts each person sees, and in what order."],
        ["Feed", "The scrolling list of posts you see when you open the app."],
        ["Reach", "How many different people saw your post."],
        ["Signal", "A clue the algorithm uses to judge a post, such as how long people looked at it."],
        ["Dwell time", "How long someone stops scrolling to look at or read your post."],
        ["Engagement", "Interactions with a post: likes, comments, shares, saves."],
        ["Shares / sends", "When someone passes your post on, publicly or by direct message (DM)."],
        ["Completion rate", "The share of people who watch a video, or read a post, to the end."],
        ["Hook", "The first line or first seconds of a post, designed to make people stop."],
        ["Engagement bait", "Tricks that beg for interaction, such as \"comment YES if you agree\"."],
        ["Owned channel", "A channel you control, like your email list or website, that no platform can take away."],
        ["Rented reach", "Audience you reach through someone else's platform, which they can reduce at any time."],
      ] },
      { type: "heading", value: "What every algorithm wants" },
      { type: "text", value: "Every social media algorithm optimises for the same thing: keeping people on the platform. More time on the app means more adverts they can show." },
      { type: "text", value: "Everything else follows from this. Posts that hold attention and get people interacting are shown to more people. Posts that people scroll straight past are not." },
      { type: "heading", value: "What the signals generally are" },
      { type: "text", value: "Platforms do not publish their full formulas, and they change often. But these signals are widely confirmed by the platforms and by testing:" },
      { type: "list", items: [
        "Dwell time — how long someone stops on the post. This is usually the strongest signal.",
        "Meaningful interaction — comments and shares count for more than likes, because they take more effort.",
        "Early engagement — how the post performs in roughly its first hour helps decide how widely it is shown next.",
        "Completion — whether people watch a video, or read a post, to the end.",
        "Relevance — how similar the post is to things this particular person has engaged with before.",
      ] },
      { type: "table", headers: ["Platform", "What tends to matter (2026)"], rows: [
        ["Instagram", "Instagram's leaders have said watch time, likes and sends (people sharing your post by DM) are among the most important signals. Original content is favoured over reposted content."],
        ["LinkedIn", "Posts that keep professionals reading and start real discussion in the comments do well. Content relevant to the author's area of expertise tends to travel further. Many creators find posts with external links get less reach, so they add links sparingly."],
      ] },
      { type: "heading", value: "Practical implications" },
      { type: "table", headers: ["Signal", "What it means for your post"], rows: [
        ["Dwell time", "Your opening line has to earn the second line. Put the interesting part first."],
        ["Comments over likes", "Ask a genuine question people have an opinion about, and reply to their answers."],
        ["Early engagement", "Post when your audience is usually online, then stay around to reply."],
        ["Completion", "Short and finished beats long and abandoned."],
      ] },
      { type: "compare", columns: [
        { title: "Honest, strong hook", subtitle: "Earns attention", tone: "olive", items: [
          "\"We threw away 40 croissants last Tuesday. Here is what we changed.\"",
          "Ends with: \"What is your favourite bake to buy on a Saturday?\"",
          "Replies to every comment in the first hour.",
          "A 15-second Reel that shows the finished cake in the first second.",
        ] },
        { title: "Weak or bait", subtitle: "Scrolled past or demoted", tone: "rose", items: [
          "\"Hello everyone! Happy Monday! We have some news...\"",
          "\"Comment YES if you love cake!\"",
          "Tagging 20 people who have nothing to do with the post.",
          "A 90-second video where the cake appears at the end.",
        ] },
      ] },
      { type: "alert", value: "Engagement bait — \"comment YES if you agree\", tagging people for no reason, fake controversy — is actively demoted on most platforms. It also damages trust with the very audience you are trying to build. The short-term reach is not worth it." },
      { type: "steps", title: "Find your best posting times and top posts (free tools)", steps: [
        { label: "Switch to a professional account", text: "On Instagram, use a Business or Creator account; this unlocks free insights. LinkedIn company Pages have analytics built in." },
        { label: "Open Instagram insights", text: "In the Instagram app, go to your profile and open Professional dashboard, then Insights. You can also use Insights in Meta Business Suite on a computer." },
        { label: "Check when your followers are online", text: "Look at the audience section for the most active days and times. Note the top two or three time slots." },
        { label: "Sort your content", text: "Look at your recent posts and Reels. Compare reach, watch time, shares and saves, not just likes." },
        { label: "Check LinkedIn analytics", text: "On your LinkedIn Page, open Analytics and look at posts with the most impressions and comments." },
        { label: "Write down a pattern", text: "Which pillar, format and time slot did best? Plan next week's posts around that pattern." },
      ] },
      { type: "example", title: "Rosie's Bakery tests a better hook (illustrative figures)", value: "Week 1 post: \"New lemon drizzle available today!\"\n  Reach 800, comments 4\n  Comment rate = 4 / 800 = 0.005 = 0.5%\n\nWeek 2 post: \"Our lemon drizzle recipe took 11 tries. Try number 7\n  was a disaster (photo in the comments). Which cake should we\n  perfect next?\"\n  Reach 2,400, comments 36\n  Comment rate = 36 / 2400 = 0.015 = 1.5%\n\nReach went from 800 to 2,400 (3 times higher).\nComment rate went from 0.5% to 1.5% (3 times higher).\nSame cake, same photo quality. The hook and the question did the work.\n(One test is not proof — repeat it a few times before deciding.)" },
      { type: "heading", value: "The platform risk" },
      { type: "text", value: "Algorithms change without warning, and you cannot appeal. An account that reliably reached 50,000 people can reach 3,000 next month, and nobody will explain why." },
      { type: "text", value: "This is why social media should feed an owned channel, not be the final destination. Reach you rent can be taken away. An email list cannot." },
      { type: "text", value: "For Rosie's Bakery, that could mean a monthly post saying: \"Join our email list and get first notice of Christmas cake orders.\"" },
      { type: "warning", value: "Common beginner mistakes: (1) Judging posts only by likes. (2) Starting posts with greetings instead of a hook. (3) Posting and then not replying to comments in the first hour. (4) Using engagement bait or buying followers. (5) Chasing every rumoured algorithm \"hack\". (6) Building the whole business on one platform with no email list." },
      { type: "heading", value: "Try it yourself" },
      { type: "list", ordered: true, items: [
        "Find three recent posts from a brand you follow on Instagram or LinkedIn.",
        "For each, copy the first line and ask: would this make a stranger stop scrolling?",
        "Rewrite the weakest first line so that the most interesting part comes first.",
        "Add one genuine question at the end that people would have an opinion about.",
        "Check: does your version use any engagement bait? If yes, remove it.",
        "Write one sentence explaining how that brand could move followers to an email list.",
      ] },
      { type: "heading", value: "Check your understanding" },
      { type: "list", items: [
        "What is the main goal of every social media algorithm? (To keep people on the platform for as long as possible.)",
        "Why do comments usually count for more than likes? (They take more effort, so they show stronger interest.)",
        "Why should social media feed an email list? (Algorithms can cut your reach at any time; an email list is an owned channel you control.)",
      ] },
    ],
    takeaways: [
      "Algorithms optimise for keeping attention; everything else follows from that.",
      "Dwell time, comments and shares count for more than likes.",
      "Put the interesting part first and reply to comments quickly.",
      "Engagement bait is demoted and costs audience trust.",
      "Use social media to build an owned list — rented reach can vanish.",
    ],
  },

  "dm-m2-l3": {
    title: "Community Management & Engagement",
    objective: "run community interaction that builds trust, including when it goes wrong.",
    content: [
      { type: "heading", value: "In simple terms" },
      { type: "text", value: "Imagine a café owner who stands at the counter. They greet regulars, answer questions about ingredients, and when a customer complains about cold coffee, they apologise and make a fresh cup in front of everyone." },
      { type: "text", value: "Community management is doing that same job online. The difference is that every conversation happens in public, and many other people are watching how you behave." },
      { type: "heading", value: "Key terms" },
      { type: "table", headers: ["Term", "Plain meaning"], rows: [
        ["Community management", "Replying to, moderating and looking after the people who interact with your brand online."],
        ["Moderation", "Deciding which comments stay, which are hidden, and which are removed."],
        ["DM (direct message)", "A private message sent on a social platform."],
        ["Unified inbox", "One screen that collects comments and messages from several platforms, such as the Inbox in Meta Business Suite."],
        ["Hide (a comment)", "On Facebook, hiding a comment means only the writer and their friends can still see it. Other people cannot."],
        ["Hidden words / keyword filter", "A setting that automatically hides comments containing words you choose, such as swear words."],
        ["Saved reply", "A reusable template answer for common questions, which you personalise before sending."],
        ["Escalation", "When a problem gets bigger and louder, often because it was handled badly."],
        ["Response time", "How long it takes you to reply to a comment or message."],
        ["Personal data", "Information that identifies someone, such as a phone number, home address or order details."],
      ] },
      { type: "heading", value: "Why it matters" },
      { type: "text", value: "Community management is the unglamorous half of social media. It means replying, moderating, and handling complaints in public." },
      { type: "text", value: "It rarely produces impressive numbers. But it has a very large effect on whether people trust the brand." },
      { type: "heading", value: "Responding well" },
      { type: "list", items: [
        "Reply quickly. On social media, people expect an answer within hours, not days.",
        "Sound like a person. Corporate-sounding replies to a genuine question seem evasive.",
        "Answer the question they actually asked before adding anything else.",
        "Move complex or sensitive issues to a private channel, but acknowledge them publicly first.",
      ] },
      { type: "compare", columns: [
        { title: "Human reply", subtitle: "Builds trust", tone: "olive", items: [
          "Question: \"Are your brownies gluten free?\"",
          "Reply: \"Not our usual brownies, sorry Sam. But our almond and orange cake is gluten free and made on Fridays. Want us to save you a slice?\"",
          "Answers the question first, uses their name, offers a next step.",
        ] },
        { title: "Robotic reply", subtitle: "Feels like a brush-off", tone: "rose", items: [
          "Question: \"Are your brownies gluten free?\"",
          "Reply: \"Thank you for your enquiry. Please refer to our website for allergen information.\"",
          "Does not answer, sends them elsewhere, sounds like a machine.",
        ] },
      ] },
      { type: "heading", value: "Handling criticism" },
      { type: "text", value: "Public complaints feel urgent, and they are often handled badly." },
      { type: "text", value: "Deleting them almost always makes things worse. The person takes a screenshot of the deletion. Now the story is about your cover-up, not the original problem." },
      { type: "example", title: "Two responses to the same complaint", value: "Complaint: \"Third time this month the export has failed. Unusable.\"\n\nPoor: \"Sorry for any inconvenience! Please DM us.\"\n  -> Generic, concedes nothing, and asks them to do the work.\n\nBetter: \"That is three failures too many and I understand the\n  frustration. We had an export bug affecting large files, fixed on\n  Tuesday. If it is still failing for you, send me the file size and\n  I will look at it today.\"\n  -> Specific, acknowledges the actual problem, offers a real next step." },
      { type: "steps", title: "A simple four-step method for any public complaint", steps: [
        { label: "Acknowledge", text: "Show you have read and understood the specific problem. Do not argue in public." },
        { label: "Take responsibility for what is yours", text: "If you got it wrong, say so plainly. If you need to check, say you are checking." },
        { label: "Offer a real next step", text: "A refund, a replacement, a phone call, or a clear question. Give a timeframe." },
        { label: "Move details private, then close the loop", text: "Ask them to message you for order details (never ask for personal data in public). When it is solved, a short public follow-up shows others it was handled." },
      ] },
      { type: "alert", value: "Only delete comments that are abusive, spam, or contain someone's personal data. Deleting legitimate criticism reliably makes the situation worse and is the single most common self-inflicted social media crisis." },
      { type: "steps", title: "Set up your inbox and moderation in Meta Business Suite (free)", steps: [
        { label: "Open the Inbox", text: "In Meta Business Suite, choose Inbox. It collects Facebook comments, Instagram comments and messages in one place." },
        { label: "Create saved replies", text: "Write templates for your five most common questions (opening hours, allergens, delivery, prices, ordering). Always personalise them before sending." },
        { label: "Turn on keyword filters", text: "In your Facebook Page and Instagram settings, use the hidden words or moderation options to automatically hide comments with offensive words." },
        { label: "Set up automated answers carefully", text: "You can set an instant reply for messages, such as \"Thanks! We reply within a few hours, 8am–6pm.\" Keep it honest and short." },
        { label: "Agree a routine", text: "Decide who checks the inbox and when, for example at 9am, 1pm and 5pm every day." },
      ] },
      { type: "example", title: "Rosie's Bakery handles a one-star complaint", value: "Comment on Facebook: \"Ordered a birthday cake for Saturday. Collected it\nand the name was spelled wrong. My daughter was upset.\"\n\nRosie's reply (posted within 2 hours):\n\"Hi Priya, I am so sorry — getting the name wrong on a birthday cake\nis not okay, and I understand why she was upset. That was our mistake.\nI would like to refund the cake in full and make her a fresh one this\nweek, free. I have sent you a private message to arrange it.\"\n\nThree days later, Priya adds: \"Rosie sorted it and the new cake was\nlovely. Thank you.\"\n\nEveryone who reads that thread now sees a bakery that fixes problems." },
      { type: "heading", value: "What good community work produces" },
      { type: "text", value: "It does not show up neatly in a dashboard. Instead, it shows up in three ways:" },
      { type: "list", items: [
        "Customers who defend you without being asked.",
        "Less work for customer support, because answers are public and easy to find.",
        "Product ideas and feedback that you would otherwise pay a research agency for.",
      ] },
      { type: "warning", value: "Common beginner mistakes: (1) Deleting honest criticism. (2) Replying days late, or only replying to praise. (3) Copy-pasting the same template to everyone. (4) Arguing with a customer in public. (5) Asking people to post their phone number or order details in a public comment. (6) Leaving the inbox with no one responsible for checking it." },
      { type: "heading", value: "Try it yourself" },
      { type: "list", ordered: true, items: [
        "Find a real complaint on a brand's public social page or on Google reviews.",
        "Read the brand's reply (if any). Did it acknowledge the actual problem?",
        "Write your own reply using the four steps: acknowledge, take responsibility, next step, move private.",
        "Keep it under 60 words and read it aloud. Does it sound like a person?",
        "Write three saved replies that Rosie's Bakery could use for common questions.",
      ] },
      { type: "heading", value: "Check your understanding" },
      { type: "list", items: [
        "When is it acceptable to delete a comment? (When it is abusive, spam, or contains someone's personal data.)",
        "Why do we acknowledge a complaint publicly before moving it to private messages? (So everyone watching sees it was taken seriously, not ignored.)",
        "Name one benefit of good community management that does not appear in a dashboard. (Trust, customers who defend you, reduced support load, or product insight.)",
      ] },
    ],
    takeaways: [
      "Reply fast and in a human voice, answering the actual question first.",
      "Acknowledge publicly, then resolve privately where appropriate.",
      "Deleting legitimate criticism escalates almost every time.",
      "Use saved replies and filters to save time, but always personalise.",
      "The rewards are trust and product insight, not dashboard numbers.",
    ],
  },

  // ─── Module 3: PPC ────────────────────────────────────────────────────
  "dm-m3-l1": {
    title: "Google Search Ads Campaign Setup",
    objective: "structure a search campaign and choose match types deliberately.",
    content: [
      { type: "heading", value: "In simple terms" },
      { type: "text", value: "Imagine someone walks into a shopping centre and asks the information desk, \"Where can I buy a birthday cake?\" If you could pay a small fee to have your bakery's name mentioned at that exact moment, it would be very valuable. The person already wants what you sell." },
      { type: "text", value: "Google Search ads work like that. People type what they want into Google, and you pay to appear at the top of the results. You usually pay only when someone clicks." },
      { type: "heading", value: "Key terms" },
      { type: "table", headers: ["Term", "Plain meaning"], rows: [
        ["PPC (pay-per-click)", "Advertising where you pay each time someone clicks your advert."],
        ["Query / search term", "The exact words a person types into Google."],
        ["Keyword", "A word or phrase you choose so that your advert can appear for related searches."],
        ["Campaign", "The top level of your ads. Budget, locations and bidding are set here."],
        ["Ad group", "A folder inside a campaign that holds one theme of keywords and the adverts for them."],
        ["Match type", "A setting that controls how closely a search must match your keyword."],
        ["Negative keyword", "A word you add so your advert does NOT show for searches containing it."],
        ["CPC (cost per click)", "What you pay for one click on your advert."],
        ["CTR (click-through rate)", "Clicks divided by impressions. For example, 5 clicks from 100 views is 5%."],
        ["Impression", "One time your advert is shown."],
        ["Landing page", "The page on your website people arrive at after clicking the advert."],
        ["Quality Score", "Google's 1–10 rating of how relevant your keyword, advert and landing page are."],
        ["RSA (responsive search ad)", "Google's standard search advert. You write several headlines and descriptions, and Google tests combinations."],
        ["Conversion", "A valuable action after the click, such as a purchase, an order or a phone call."],
        ["Search terms report", "A list in Google Ads showing the real searches that triggered your adverts."],
      ] },
      { type: "heading", value: "Why search ads work" },
      { type: "text", value: "Search ads capture demand that already exists. The person has typed a query that shows what they want, and you bid to appear next to it." },
      { type: "text", value: "That intent is why search usually converts better than any other paid channel. It is also why each click tends to cost more." },
      { type: "heading", value: "Account structure" },
      { type: "text", value: "The structure has one job: to help your advert and landing page match the search as closely as possible." },
      { type: "text", value: "The closer the match, the better your Quality Score. A better Quality Score means you pay less for the same position." },
      { type: "example", title: "Structure", value: "Campaign: Running Shoes            (budget and location set here)\n  Ad group: Trail Running Shoes\n    keywords: trail running shoes, off road running shoes\n    ad copy:  about trail shoes specifically\n    landing:  /shoes/trail\n  Ad group: Road Running Shoes\n    keywords: road running shoes, marathon shoes\n    ad copy:  about road shoes specifically\n    landing:  /shoes/road\n\nOne theme per ad group. Mixing themes forces generic copy that\nmatches nothing well." },
      { type: "compare", columns: [
        { title: "Tidy structure", subtitle: "Relevant and cheaper", tone: "olive", items: [
          "Ad group \"Birthday cakes\": birthday cake delivery, custom birthday cake.",
          "Advert headline: \"Custom Birthday Cakes in Leeds\".",
          "Landing page: the birthday cakes page.",
        ] },
        { title: "Messy structure", subtitle: "Generic and costly", tone: "rose", items: [
          "One ad group with cakes, bread, coffee, wedding catering and jobs.",
          "Advert headline: \"Rosie's Bakery — Visit Us Today\".",
          "Landing page: the home page for every search.",
        ] },
      ] },
      { type: "heading", value: "Match types" },
      { type: "table", headers: ["Match type", "Written as", "Triggers on", "Risk"], rows: [
        ["Broad", "running shoes", "Anything Google considers related", "Wastes budget on loosely related queries"],
        ["Phrase", "\"running shoes\"", "Queries containing that meaning", "Balanced — the usual starting point"],
        ["Exact", "[running shoes]", "That query and close variants", "Limited volume"],
      ] },
      { type: "text", value: "Note: Google now matches by meaning, not just exact words, for all match types. \"Close variants\" include plurals, misspellings and searches with the same meaning. Google increasingly recommends broad match with automated bidding; that can work well once you have solid conversion tracking, but beginners with small budgets should watch it closely." },
      { type: "alert", value: "Negative keywords matter as much as keywords. Without them a shoe retailer pays for \"running shoes free\", \"running shoes repair\" and \"running shoes history\". Review the search terms report weekly and add negatives — this is where most wasted spend hides." },
      { type: "heading", value: "Quality Score" },
      { type: "text", value: "Google looks at three things when scoring your keywords:" },
      { type: "list", items: [
        "Expected click-through rate — how likely people are to click your advert.",
        "Ad relevance — how well your advert matches what the person searched for.",
        "Landing page experience — how useful, relevant and easy to use your landing page is.",
      ] },
      { type: "text", value: "A higher score means a lower cost per click for the same position. So relevance is not just good practice. It directly reduces what you pay." },
      { type: "steps", title: "Set up a basic Search campaign in Google Ads", steps: [
        { label: "Create an account", text: "Go to ads.google.com and sign in. If Google offers a simplified Smart mode, look for the option to switch to Expert mode so you can see every setting." },
        { label: "Set up conversion tracking first", text: "Under Goals, create a conversion such as a purchase, form submission or phone call. Without this, you cannot tell which clicks made money." },
        { label: "Start a new campaign", text: "Click New campaign, choose an objective such as Sales or Leads (or create one without guidance), and select Search as the campaign type." },
        { label: "Choose networks and locations", text: "Untick the Display Network so your ads only show in search results. Set locations to where you actually serve customers, and choose languages." },
        { label: "Set budget and bidding", text: "Enter an average daily budget. For a new, small campaign, start simple (see the next lesson on bidding)." },
        { label: "Build ad groups and keywords", text: "Create one ad group per theme. Add 5–15 closely related keywords in phrase or exact match." },
        { label: "Write a responsive search ad", text: "Add up to 15 headlines (30 characters each) and up to 4 descriptions (90 characters each). Include the keyword theme and a clear reason to click. Set the final URL to the matching landing page." },
        { label: "Add negative keywords and publish", text: "Add obvious negatives such as free, jobs, recipe, course. Review everything, then publish. Check the search terms report after a few days." },
      ] },
      { type: "example", title: "Rosie's Bakery: first week of a search campaign (illustrative figures)", value: "Ad group: Birthday cakes (phrase match)\nBudget: GBP 10 per day x 7 days = GBP 70\n\nResults after 7 days:\n  Impressions   1,400\n  Clicks        56\n  Spend         GBP 70\n\nCTR = 56 / 1400 = 0.04 = 4%\nCPC = 70 / 56   = GBP 1.25\n\nSearch terms report shows 12 clicks from \"birthday cake recipe\".\nWasted spend = 12 x GBP 1.25 = GBP 15\nShare wasted = 15 / 70 = about 21%\n\nAction: add \"recipe\" as a negative keyword.\nNext week, that GBP 15 goes towards people who want to buy a cake." },
      { type: "warning", value: "Common beginner mistakes: (1) Launching without conversion tracking. (2) Leaving the Display Network ticked in a Search campaign. (3) Using broad match with no negative keywords. (4) Sending every click to the home page. (5) Putting unrelated keywords in one ad group. (6) Targeting a whole country when you only deliver locally. (7) Never opening the search terms report." },
      { type: "heading", value: "Try it yourself" },
      { type: "list", ordered: true, items: [
        "Choose one product from Rosie's Bakery or a small online shop you know.",
        "Write two ad group themes (for example, \"birthday cakes\" and \"wedding cakes\").",
        "List five keywords for each theme, and mark each as phrase or exact match.",
        "List at least five negative keywords that would waste money (think: free, recipe, jobs).",
        "Write three headlines of 30 characters or fewer for one ad group. Count the characters.",
        "Write down which landing page each ad group should send people to.",
      ] },
      { type: "heading", value: "Check your understanding" },
      { type: "list", items: [
        "Why do search ads often convert better than social ads? (The person is already searching for what you sell, so the intent is higher.)",
        "What does the negative keyword \"recipe\" do for a bakery? (It stops the advert showing for searches like \"birthday cake recipe\", from people who want to bake, not buy.)",
        "Name the three parts of Quality Score. (Expected click-through rate, ad relevance, and landing page experience.)",
      ] },
    ],
    takeaways: [
      "Search ads capture existing demand; they convert well but cost more per click.",
      "Use one theme per ad group so the advert and landing page match the search.",
      "Phrase match is a sensible default; broad match needs close supervision and good tracking.",
      "Negative keywords and the search terms report are where wasted spend is recovered.",
      "Set up conversion tracking before you spend any money.",
    ],
  },

  "dm-m3-l2": {
    title: "Meta (Facebook/Instagram) Ads Manager",
    objective: "build a paid social campaign and understand why creative dominates results.",
    content: [
      { type: "heading", value: "In simple terms" },
      { type: "text", value: "Search ads are like a shop sign on a road where people are already looking for bakeries. Social ads are more like a street performer. People are walking past, busy with something else. The performer must grab their attention in seconds, or they keep walking." },
      { type: "text", value: "On Facebook and Instagram, people are scrolling through friends' photos and videos. Your advert has to make them stop before it can sell anything." },
      { type: "heading", value: "Key terms" },
      { type: "table", headers: ["Term", "Plain meaning"], rows: [
        ["Meta Ads Manager", "Meta's free tool for creating and managing adverts on Facebook, Instagram, Messenger and Threads."],
        ["Objective", "The main result you tell Meta to aim for, such as Awareness, Traffic, Leads or Sales."],
        ["Campaign", "The top level, where you choose the objective."],
        ["Ad set", "The middle level, where you set the audience, placements, budget and schedule."],
        ["Ad", "The bottom level: the actual image or video, text and button people see."],
        ["Creative", "The content of the advert itself: visuals, words and call to action."],
        ["CTA (call to action)", "The action you ask for, such as Shop now, Order now or Learn more."],
        ["Placement", "Where the advert appears: Feed, Stories, Reels and so on."],
        ["Cold audience", "People who have never interacted with your business."],
        ["Retargeting", "Showing adverts to people who already visited your website or engaged with you."],
        ["Custom audience", "An audience built from your own data, like website visitors or a customer list."],
        ["Lookalike audience", "New people Meta finds who resemble a source audience, such as your customers."],
        ["Advantage+", "Meta's name for its automated options, where its AI chooses audiences, placements or creative for you."],
        ["Meta Pixel / Conversions API", "Tracking tools that tell Meta when someone takes an action on your website, such as a purchase."],
        ["Attribution", "Deciding which advert or channel gets the credit for a sale."],
        ["Frequency", "The average number of times each person has seen your advert."],
      ] },
      { type: "heading", value: "Interrupting, not capturing" },
      { type: "text", value: "Paid social interrupts people instead of capturing a search. Nobody opened Instagram to buy your product." },
      { type: "text", value: "So the advert has to earn attention first, and persuade second. That one difference explains why creative matters more here than anywhere else." },
      { type: "heading", value: "Campaign structure" },
      { type: "list", items: [
        "Campaign — sets the objective. Choose the objective that matches your real goal. If you want purchases but choose Traffic, you get lots of cheap clicks from people who rarely buy.",
        "Ad set — the audience, placements, budget and schedule.",
        "Ad — the creative itself: image or video, text, and call to action.",
      ] },
      { type: "heading", value: "Targeting" },
      { type: "table", headers: ["Audience type", "Built from", "Typical use"], rows: [
        ["Core (saved audience)", "Demographics, interests, behaviours", "Cold prospecting when you have no data"],
        ["Custom", "Your customer list, site visitors, video viewers", "Retargeting people who already engaged"],
        ["Lookalike", "People resembling a source audience", "Scaling once you know who converts"],
      ] },
      { type: "text", value: "In 2026, Meta often switches on Advantage+ audience by default. Your age, location and interest choices then act mostly as suggestions, and Meta's system looks for likely buyers more widely. Location and minimum age can still be set as firm limits. Automation works best when your Pixel or Conversions API is sending accurate purchase data." },
      { type: "text", value: "Retargeting almost always performs better than cold targeting, because familiarity does much of the persuading." },
      { type: "text", value: "Someone who looked at your prices last week is a very different prospect from someone who has never heard of you. The advert should say something different to each." },
      { type: "compare", columns: [
        { title: "Thumb-stopping creative", subtitle: "Earns attention", tone: "olive", items: [
          "A vertical video showing a knife cutting through a layered cake in the first second.",
          "Text on screen: \"Order by Thursday for Saturday collection\".",
          "One clear CTA: Order now.",
          "Made for Reels and Stories, with captions for people watching on mute.",
        ] },
        { title: "Easy-to-ignore creative", subtitle: "Scrolled past", tone: "rose", items: [
          "A small, dark photo of the shop front.",
          "Paragraph of text: \"Rosie's Bakery has been serving the community since 2009...\".",
          "No clear action to take.",
          "A landscape image cropped badly in Stories.",
        ] },
      ] },
      { type: "alert", value: "Creative is the largest lever in paid social — larger than targeting. The platforms have become very good at finding receptive people; they cannot make a boring advert interesting. Expect to refresh creative regularly, because performance decays as an audience sees the same thing repeatedly." },
      { type: "steps", title: "Create a simple Sales campaign in Meta Ads Manager", steps: [
        { label: "Prepare tracking", text: "In Events Manager, connect the Meta Pixel (and ideally the Conversions API) to your website so purchases are recorded. Many shop platforms, such as Shopify, can do this through an integration. In the UK, make sure your cookie consent banner covers this tracking." },
        { label: "Open Ads Manager", text: "Go to adsmanager.facebook.com and click Create." },
        { label: "Choose the objective", text: "Pick Sales if you want online orders, or Leads if you want enquiries. Give the campaign a clear name, for example \"Sales – Birthday cakes – Sept\"." },
        { label: "Set up the ad set", text: "Choose the conversion event (for example, Purchase). Set a daily budget and schedule. Set the location to where you deliver or where customers can visit." },
        { label: "Decide on audience", text: "Either accept Advantage+ audience and add suggestions, or build a custom audience of website visitors for retargeting." },
        { label: "Choose placements", text: "Advantage+ placements (automatic) is usually fine for beginners. Make sure your creative works in vertical formats for Reels and Stories." },
        { label: "Create the ad", text: "Upload an image or video, write the main text and headline, choose a call-to-action button, and add your website link. Check the preview for every placement." },
        { label: "Publish and wait", text: "Click Publish. Avoid big changes for the first several days while the system learns. Then compare results against your own website or shop sales data." },
      ] },
      { type: "example", title: "Rosie's Bakery: cold versus retargeting (illustrative figures)", value: "Budget: GBP 100 for each ad set over two weeks.\n\nAd set A — cold audience (people within 10 miles)\n  Orders:          4\n  Cost per order = 100 / 4  = GBP 25.00\n\nAd set B — retargeting (website visitors in the last 30 days)\n  Orders:          10\n  Cost per order = 100 / 10 = GBP 10.00\n\nRetargeting cost 25 - 10 = GBP 15 less per order.\n\nBut: ad set B's audience is small (only people who already visited).\nSo Rosie cannot just move all GBP 200 into retargeting — it would run\nout of new people. She needs cold ads to fill the website with visitors,\nand retargeting ads to bring them back to order.\n\nCheck: Shopify showed 12 orders from Meta links, while Ads Manager\nreported 14. Platform numbers are estimates — trust your shop data." },
      { type: "heading", value: "Measurement caveat" },
      { type: "text", value: "Attribution on social media is genuinely difficult. Privacy changes and cookie restrictions mean the conversions reported by the platform are estimates." },
      { type: "text", value: "Platforms also have an obvious reason to give themselves generous credit. Compare their numbers with your own analytics (such as Google Analytics 4 or your shop's sales reports) and, where possible, with your total revenue. Do not trust the ad platform alone." },
      { type: "warning", value: "Common beginner mistakes: (1) Choosing the Traffic or Engagement objective when you really want sales. (2) Using the \"Boost post\" button for everything instead of Ads Manager. (3) Launching without the Pixel or Conversions API set up. (4) Running one image for months without refreshing it. (5) Showing the same message to strangers and past visitors. (6) Changing budgets and audiences every day, so the system never learns. (7) Believing platform-reported sales without checking your own data." },
      { type: "heading", value: "Try it yourself" },
      { type: "list", ordered: true, items: [
        "Open the Meta Ad Library (facebook.com/ads/library) — it is free and needs no ad account.",
        "Search for a bakery, café or small shop brand you know, and look at its active adverts.",
        "Pick two adverts. For each, note: what makes you stop in the first second? What is the CTA?",
        "Guess which objective each advert might use (Awareness, Traffic, Leads or Sales).",
        "Write one advert idea for Rosie's Bakery for a cold audience, and a different one for people who visited the website.",
        "For each idea, write one sentence describing the first second of the video or image.",
      ] },
      { type: "heading", value: "Check your understanding" },
      { type: "list", items: [
        "What are the three levels of a Meta campaign, and what is set at each? (Campaign: objective. Ad set: audience, placements, budget, schedule. Ad: the creative.)",
        "Why does retargeting usually cost less per sale? (The people already know the business, so they need less persuading.)",
        "Why should you compare Ads Manager results with your own shop data? (Platform-reported conversions are estimates and tend to be generous.)",
      ] },
    ],
    takeaways: [
      "Paid social interrupts people, so the creative must earn attention first.",
      "Choose the objective that matches your real goal, such as Sales for orders.",
      "Creative matters more than targeting; refresh it regularly.",
      "Retargeting outperforms cold targeting, but the message should differ and the audience is small.",
      "Platform-reported conversions are optimistic estimates — check them against your own data.",
    ],
  },

  "dm-m3-l3": {
    title: "Bidding Strategies, Budgets, and Retargeting",
    objective: "set budgets and bids that stay profitable, using CAC and LTV.",
    content: [
      { type: "heading", value: "In simple terms" },
      { type: "text", value: "Imagine you pay a friend GBP 5 for every new customer they bring to your market stall. If each new customer only ever buys one GBP 3 item, you lose money on every introduction. If each new customer comes back every week for a year, GBP 5 is a bargain." },
      { type: "text", value: "Advertising works the same way. The key question is simple: does it cost less to win a customer than that customer is worth to you?" },
      { type: "heading", value: "Key terms" },
      { type: "table", headers: ["Term", "Plain meaning"], rows: [
        ["Bid", "The amount you are willing to pay for a click or result in an advertising auction."],
        ["Bidding strategy", "The rule for how your bids are set: by you (manual) or automatically by the platform."],
        ["Budget", "The maximum you are happy to spend, usually per day or per campaign."],
        ["CAC (customer acquisition cost)", "Total ad spend divided by the number of new customers it brought in."],
        ["CPA (cost per acquisition)", "What you pay for one conversion, such as a sale or a lead. Often similar to CAC."],
        ["LTV (lifetime value)", "How much profit a customer brings you over the whole time they buy from you."],
        ["Gross margin", "The percentage of the price left after paying for the product itself. A GBP 10 cake costing GBP 6 to make has a 40% margin."],
        ["LTV:CAC ratio", "Customer value compared with the cost of getting them. 3:1 means GBP 3 value for every GBP 1 spent."],
        ["ROAS (return on ad spend)", "Revenue from ads divided by ad spend. GBP 400 revenue from GBP 100 spend is a ROAS of 4 (or 400%)."],
        ["Manual CPC", "You set the maximum cost per click yourself."],
        ["Smart bidding", "Google's automated bidding that uses machine learning to set bids for each auction."],
        ["Conversion volume", "How many conversions a campaign records — automated bidding needs enough of them to learn."],
        ["Retargeting", "Showing adverts to people who already visited your website or engaged with you."],
        ["Frequency cap", "A limit on how many times the same person sees your advert in a period."],
      ] },
      { type: "heading", value: "The only numbers that matter" },
      { type: "text", value: "A campaign is profitable when it costs less to win a customer than that customer is worth." },
      { type: "text", value: "Everything else — click cost, impressions, engagement rate — is useful detail for finding problems. But it sits underneath that one question." },
      { type: "example", title: "Working it through", value: "Spend                 GBP 2,000\nCustomers acquired    40\nCAC = 2000 / 40     = GBP 50\n\nAverage order          GBP 60\nAverage repeat orders  3\nGross margin           40%\nLTV = 60 x 3 x 0.40  = GBP 72\n\nLTV:CAC = 72:50 = 1.44:1\n\nProfitable, but thin. A widely used benchmark is 3:1; below that,\ngrowth consumes cash faster than it generates it." },
      { type: "text", value: "Reading the example slowly: each customer orders GBP 60 of goods, three times, so they spend GBP 180 in total. But only 40% of that is profit before advertising: GBP 180 x 0.40 = GBP 72. Getting that customer cost GBP 50. So each customer leaves GBP 72 - GBP 50 = GBP 22, before other costs such as rent and staff." },
      { type: "alert", value: "Calculating LTV on revenue rather than margin is the most common error here, and it flatters the number badly. A GBP 60 order at 40% margin contributes GBP 24, not GBP 60. Businesses have scaled themselves into insolvency on that mistake." },
      { type: "compare", columns: [
        { title: "Correct: LTV on margin", subtitle: "Honest picture", tone: "olive", items: [
          "LTV = 60 x 3 x 0.40 = GBP 72",
          "LTV:CAC = 72:50 = 1.44:1",
          "Conclusion: profitable but thin — improve before scaling.",
        ] },
        { title: "Wrong: LTV on revenue", subtitle: "Dangerously flattering", tone: "rose", items: [
          "LTV = 60 x 3 = GBP 180",
          "LTV:CAC = 180:50 = 3.6:1",
          "Conclusion: \"Great, spend more!\" — which could drain the business's cash.",
        ] },
      ] },
      { type: "heading", value: "Bidding" },
      { type: "list", items: [
        "Manual CPC — you have full control. Useful when data is thin or spend is small.",
        "Maximise conversions — the platform spends your budget to get as many conversions as possible. Your conversion tracking must be correct.",
        "Target CPA — aims for a cost per acquisition that you set. It needs enough conversion history to learn from. (In Google Ads, this is now an optional target inside Maximise conversions.)",
        "Target ROAS — aims for a return on ad spend. It needs accurate revenue values sent back to the platform. (In Google Ads, this is an optional target inside Maximise conversion value.)",
      ] },
      { type: "text", value: "Automated bidding needs data. If a campaign gets four conversions a month and you set Target CPA, the algorithm has almost nothing to learn from." },
      { type: "text", value: "A good path is: start manual (or with simple Maximise clicks or Maximise conversions), gather data, then add a target. Google's guidance has generally suggested at least around 15 conversions in the last 30 days before using targets, and more is better." },
      { type: "steps", title: "Change a Google Ads campaign's bidding strategy", steps: [
        { label: "Check your conversion data", text: "In Google Ads, open Campaigns and look at the Conversions column for the last 30 days. If it is very low, stay with a simpler strategy for now." },
        { label: "Open the campaign settings", text: "Click the campaign name, then Settings, then expand Bidding." },
        { label: "Choose a strategy", text: "Pick Maximise conversions (or Maximise conversion value if you track revenue). Tick the option to set a target CPA or target ROAS only when you have enough data." },
        { label: "Set a realistic target", text: "Base your target CPA on your recent actual CPA, not a wish. For example, if recent CPA is GBP 12, do not suddenly set GBP 5." },
        { label: "Save and be patient", text: "Automated strategies go through a learning period, often about one to two weeks. Avoid large budget or target changes during that time." },
        { label: "Review against profit", text: "After a few weeks, compare CPA with what a customer is worth (LTV). Adjust the target gradually, by around 10–20% at a time." },
      ] },
      { type: "heading", value: "Setting a budget you can afford" },
      { type: "text", value: "Work backwards from what a customer is worth. First decide the maximum you can pay for a customer (your target CAC). Then multiply by how many customers you want." },
      { type: "example", title: "Rosie's Bakery sets a monthly ad budget (illustrative figures)", value: "Rosie sells celebration cakes online.\n\nStep 1: profit per order\n  Average order       GBP 40\n  Gross margin        50%\n  Profit per order  = 40 x 0.50 = GBP 20\n\nStep 2: lifetime value\n  Average orders per customer (per year)  2\n  LTV = GBP 20 x 2 = GBP 40\n\nStep 3: maximum CAC for a 3:1 ratio\n  Max CAC = LTV / 3 = 40 / 3 = about GBP 13.33\n\nStep 4: budget\n  Goal: 30 new customers a month\n  Budget = 30 x GBP 13.33 = about GBP 400 a month\n  Daily  = 400 / 30 = about GBP 13 a day\n\nStep 5: check after one month\n  Actual spend GBP 400, new customers 25\n  Actual CAC = 400 / 25 = GBP 16\n  LTV:CAC = 40 / 16 = 2.5:1  -> below 3:1, so improve ads or the\n  landing page before increasing the budget." },
      { type: "heading", value: "Retargeting economics" },
      { type: "text", value: "Retargeting is usually the cheapest way to win customers, because the audience already knows you." },
      { type: "text", value: "But it has a limit. You can only retarget people who already visited. It makes existing demand stronger; it does not create new demand. So it cannot be your whole strategy." },
      { type: "alert", value: "Cap retargeting frequency. Following someone around the internet with the same advert twenty times a week produces irritation, not sales, and damages brand perception in a way the dashboard will not show you." },
      { type: "text", value: "How to control frequency in practice: Google Display campaigns have a frequency management setting. On Meta, a direct frequency cap is only available with some objectives (such as Reach). With other objectives, watch the Frequency column in Ads Manager, and control it through a smaller budget, a shorter audience window (for example, visitors in the last 14 days) and several different adverts." },
      { type: "compare", columns: [
        { title: "Respectful retargeting", subtitle: "Helpful reminder", tone: "olive", items: [
          "Shown to people who viewed a cake page in the last 14 days.",
          "Excludes people who already ordered.",
          "Frequency kept to a few views a week.",
          "Message: \"Still thinking about it? Order by Thursday for Saturday.\"",
        ] },
        { title: "Annoying retargeting", subtitle: "Feels like being followed", tone: "rose", items: [
          "Shown to everyone who visited in the last 180 days.",
          "Keeps showing to people who already bought.",
          "Same advert 20+ times a week.",
          "Message identical to the cold advert they already ignored.",
        ] },
      ] },
      { type: "warning", value: "Common beginner mistakes: (1) Calculating LTV on revenue instead of margin. (2) Judging success on cheap clicks rather than CAC. (3) Turning on Target CPA or Target ROAS with very few conversions. (4) Setting an unrealistic target that starves the campaign. (5) Changing bids every day during the learning period. (6) Spending most of the budget on retargeting and wondering why growth stops. (7) Forgetting to exclude people who already bought." },
      { type: "heading", value: "Try it yourself" },
      { type: "list", ordered: true, items: [
        "Pick a small online shop (real or imaginary). Write down its average order value and a sensible gross margin (for example, 40%).",
        "Estimate how many times a typical customer buys per year.",
        "Calculate profit per order: order value x margin.",
        "Calculate LTV: profit per order x number of orders.",
        "Calculate the maximum CAC for a 3:1 ratio: LTV / 3.",
        "Decide how many new customers you want a month, and multiply to get the monthly budget. Divide by 30 for a daily budget.",
        "Write one sentence: which bidding strategy would you start with, and why?",
      ] },
      { type: "heading", value: "Check your understanding" },
      { type: "list", items: [
        "A shop spends GBP 600 and gets 20 new customers. What is the CAC? (GBP 600 / 20 = GBP 30.)",
        "Why should LTV be calculated on margin, not revenue? (Revenue includes the cost of the product; only the margin is money you actually keep, so revenue makes LTV look far too high.)",
        "Why is Target CPA a poor choice for a campaign with four conversions a month? (The algorithm needs much more conversion data to learn from; start manual or simpler and gather data first.)",
      ] },
    ],
    takeaways: [
      "Profitability means LTV compared with CAC; aim for roughly 3:1.",
      "Always calculate LTV on margin, never on revenue.",
      "Work backwards from customer value to set a budget you can afford.",
      "Automated bidding needs conversion volume — start simple, then add targets.",
      "Retargeting is cheap but limited in size, and it needs frequency limits and exclusions.",
    ],
  },
};
