import { LessonMap } from './types';

/** Module 9 (views, indexes, performance) + Module 10 (transactions) + Module 11 (procedures). */
export const advancedLessons: LessonMap = {
  // ─────────────────────────── MODULE 9 ───────────────────────────
  'm9-l1': {
    title: 'Views',
    content: [
      { type: 'text', value: 'A view is a stored SELECT statement that you can query as though it were a table. It holds no rows of its own — every time you read from it, the underlying query runs again.' },
      { type: 'diagram', name: 'sql-view', caption: 'A view stores a definition, not data. That is both its main strength and its main limitation.' },
      { type: 'code', language: 'sql', value: "CREATE VIEW employee_directory AS\nSELECT e.id,\n       e.name,\n       d.name AS department,\n       d.city\nFROM   employees e\nLEFT JOIN departments d ON d.id = e.dept_id;\n\n-- Now query it like any table\nSELECT * FROM employee_directory WHERE city = 'Pune';" },
      { type: 'heading', value: 'What views are actually for' },
      { type: 'list', items: [
        'Hiding complexity: a five-table join becomes one readable name that the rest of the codebase uses.',
        'Security: grant access to a view exposing only non-sensitive columns, without granting access to the base table at all.',
        'A stable interface: refactor the underlying tables while keeping the view definition constant, and nothing downstream breaks.',
        'Consistency: everyone computing "active customer" uses one definition instead of five slightly different WHERE clauses.',
      ] },
      { type: 'code', language: 'sql', value: "-- Security use: analysts see the directory, never the salaries\nCREATE VIEW public_directory AS\nSELECT name, department, city FROM employee_directory;\n\nGRANT SELECT ON public_directory TO analyst_role;\n-- no grant on employees at all" },
      { type: 'warning', value: 'A view does not make anything faster. Selecting from a view that joins five tables costs exactly what running that join costs. Views organise queries; indexes make them fast. Confusing the two is a common early mistake.' },
      { type: 'heading', value: 'Materialised views — when you do want the rows stored' },
      { type: 'text', value: 'A materialised view computes the query once and stores the result on disk. Reads are then as fast as reading a table, at the cost of the data being stale until you refresh it.' },
      { type: 'code', language: 'sql', value: "CREATE MATERIALIZED VIEW department_stats AS\nSELECT d.id, d.name,\n       COUNT(e.id)           AS headcount,\n       COALESCE(SUM(e.salary), 0) AS payroll\nFROM   departments d\nLEFT JOIN employees e ON e.dept_id = d.id\nGROUP BY d.id, d.name;\n\n-- Recompute it (blocks readers)\nREFRESH MATERIALIZED VIEW department_stats;\n\n-- Recompute without blocking readers (needs a unique index on the view)\nCREATE UNIQUE INDEX ON department_stats (id);\nREFRESH MATERIALIZED VIEW CONCURRENTLY department_stats;" },
      { type: 'compare', columns: [
        { title: 'View', tone: 'olive', items: [
          'Stores only the query text',
          'Always reflects current data',
          'Costs the full query on every read',
          'Use for abstraction and access control',
        ] },
        { title: 'Materialised view', tone: 'honey', items: [
          'Stores the computed rows',
          'Stale until refreshed',
          'Reads are as cheap as a table scan',
          'Use for expensive dashboards and reports',
        ] },
      ] },
      { type: 'heading', value: 'Updating through a view' },
      { type: 'text', value: 'A simple view over one table with no aggregation is updatable — INSERT and UPDATE against it reach the base table. Anything involving a join, GROUP BY or DISTINCT is not, because the database cannot know which underlying row you meant.' },
      { type: 'alert', value: 'If you need writes through a complex view, PostgreSQL supports INSTEAD OF triggers, which let you define exactly what an INSERT into the view should do. That is usually a sign the design should be reconsidered first.' },
    ],
    objectives: [
      'Create views to encapsulate complex queries',
      'Use views to grant column-level access safely',
      'Choose between a view and a materialised view',
    ],
    takeaways: [
      'A view stores a query, not rows — it costs full price on every read.',
      'Materialised views trade freshness for speed, and need an explicit refresh.',
      'Views are for abstraction and security; indexes are for performance.',
    ],
  },

  'm9-l2': {
    title: 'Indexing',
    content: [
      { type: 'text', value: 'An index is a separate, sorted data structure that lets the database find rows without examining all of them. It is the single highest-impact performance tool you have, and also the easiest one to misuse.' },
      { type: 'heading', value: 'The problem an index solves' },
      { type: 'diagram', name: 'sql-scan-comparison', caption: 'Without an index the engine must inspect every page. With one, it goes straight to the row.' },
      { type: 'text', value: 'Without an index, WHERE email = ? means reading every row in the table and comparing — a sequential scan. On a million-row table that is a million comparisons for a query you run on every login.' },
      { type: 'heading', value: 'How a B-Tree index works' },
      { type: 'diagram', name: 'sql-btree', caption: 'Each level roughly halves the search space, so lookup cost grows logarithmically rather than linearly.' },
      { type: 'text', value: 'B-Tree is the default index type and covers almost every case. Because the tree stays balanced, finding one row among a million takes about twenty comparisons instead of a million. And because the leaves are sorted and linked, the same index also serves range queries and ORDER BY.' },
      { type: 'code', language: 'sql', value: "CREATE INDEX idx_employees_dept ON employees (dept_id);\n\n-- Unique index: also enforces uniqueness\nCREATE UNIQUE INDEX idx_users_email ON users (LOWER(email));\n\n-- Build without locking writes (essential in production)\nCREATE INDEX CONCURRENTLY idx_orders_placed ON orders (placed_at);\n\nDROP INDEX idx_employees_dept;" },
      { type: 'heading', value: 'Composite indexes and the leftmost-prefix rule' },
      { type: 'text', value: 'An index on (a, b, c) is sorted by a first, then b within equal a, then c. That ordering determines exactly which queries it can help — and the rule is that you must use a leading prefix of the columns.' },
      { type: 'code', language: 'sql', value: "CREATE INDEX idx_orders ON orders (user_id, status, placed_at);\n\n-- Uses the index:\nWHERE user_id = 7\nWHERE user_id = 7 AND status = 'paid'\nWHERE user_id = 7 AND status = 'paid' AND placed_at > '2024-01-01'\n\n-- Cannot use it (no leading user_id):\nWHERE status = 'paid'\nWHERE placed_at > '2024-01-01'" },
      { type: 'alert', value: 'The analogy that makes this stick: a phone book sorted by (last name, first name). Finding everyone called Iyer is instant. Finding everyone called Ana, of any surname, means reading the whole book — the sort order gives you nothing.' },
      { type: 'heading', value: 'Index types beyond B-Tree' },
      { type: 'table', headers: ['Type', 'Good at', 'Use when'], rows: [
        ['B-Tree (default)', 'Equality, ranges, sorting', 'Almost always'],
        ['Hash', 'Equality only', 'Rarely — B-Tree does this too'],
        ['GIN', 'Multiple values inside one column', 'JSONB, arrays, full-text search'],
        ['GiST', 'Geometric and range overlap', 'PostGIS, range types'],
        ['BRIN', 'Very large, naturally ordered tables', 'Time-series where rows arrive in order'],
      ] },
      { type: 'heading', value: 'Partial and expression indexes' },
      { type: 'code', language: 'sql', value: "-- Partial: index only the rows you actually query.\n-- Far smaller and cheaper to maintain.\nCREATE INDEX idx_orders_pending ON orders (placed_at)\nWHERE status = 'pending';\n\n-- Expression: makes a function call indexable\nCREATE INDEX idx_users_lower_email ON users (LOWER(email));\n-- now WHERE LOWER(email) = 'a@b.com' can use an index" },
      { type: 'heading', value: 'The cost side of the ledger' },
      { type: 'text', value: 'Every index must be updated on every INSERT, UPDATE and DELETE to the indexed columns. Five indexes means five extra structures to maintain per write, plus the disk they occupy, plus the memory they take from the page cache.' },
      { type: 'compare', columns: [
        { title: 'Index these', tone: 'olive', items: [
          'Foreign key columns — they are joined constantly',
          'Columns in frequent WHERE clauses',
          'Columns in ORDER BY on large tables',
          'Columns with high selectivity (many distinct values)',
        ] },
        { title: 'Do not index these', tone: 'rose', items: [
          'Small tables — a full scan is already cheap',
          'Low-selectivity columns like a boolean flag',
          'Columns that are written far more than read',
          'Anything "just in case" — every index has a price',
        ] },
      ] },
      { type: 'warning', value: 'PostgreSQL does not create an index on a foreign key column automatically — only on the primary key it references. Missing FK indexes are one of the most common causes of slow joins and slow cascading deletes in real applications.' },
      { type: 'code', language: 'sql', value: "-- Find indexes nobody is using\nSELECT relname AS table, indexrelname AS index, idx_scan AS times_used\nFROM   pg_stat_user_indexes\nWHERE  idx_scan = 0\nORDER BY pg_relation_size(indexrelid) DESC;" },
    ],
    objectives: [
      'Explain why a B-Tree turns linear search into logarithmic',
      'Apply the leftmost-prefix rule to composite indexes',
      'Weigh index read benefit against write and storage cost',
    ],
    takeaways: [
      'An index on (a, b, c) helps queries filtering on a leading prefix only.',
      'Every index slows writes — index deliberately, not defensively.',
      'Foreign key columns are not indexed automatically, and usually should be.',
    ],
  },

  'm9-l3': {
    title: 'Performance and EXPLAIN',
    content: [
      { type: 'text', value: 'EXPLAIN is how you stop guessing. It shows the plan the optimiser chose: which indexes it will use, how it will join, and how many rows it expects at each step.' },
      { type: 'code', language: 'sql', value: "-- The plan only, without running the query\nEXPLAIN SELECT * FROM employees WHERE dept_id = 1;\n\n-- Run it and report what actually happened, with real timings\nEXPLAIN (ANALYZE, BUFFERS, FORMAT TEXT)\nSELECT e.name, d.name\nFROM   employees e\nJOIN   departments d ON d.id = e.dept_id\nWHERE  e.salary > 70000;" },
      { type: 'heading', value: 'Reading a plan' },
      { type: 'code', language: 'text', value: "Hash Join  (cost=1.07..2.15 rows=2 width=64) (actual time=0.031..0.038 rows=2 loops=1)\n  Hash Cond: (e.dept_id = d.id)\n  ->  Seq Scan on employees e  (cost=0.00..1.06 rows=2 width=36)\n        Filter: (salary > 70000)\n        Rows Removed by Filter: 3\n  ->  Hash  (cost=1.03..1.03 rows=3 width=36)\n        ->  Seq Scan on departments d  (cost=0.00..1.03 rows=3 width=36)\nPlanning Time: 0.180 ms\nExecution Time: 0.061 ms" },
      { type: 'syntax', title: 'What each part is telling you', parts: [
        { clause: 'Read inwards', text: 'the most indented nodes run first; results flow outward to the top.' },
        { clause: 'cost=a..b', text: 'estimated startup cost and total cost, in arbitrary planner units. Useful for comparison, not as a time.' },
        { clause: 'rows=', text: 'the estimate. Compare it with the actual — a large mismatch means stale statistics.' },
        { clause: 'actual time=', text: 'real milliseconds, present only with ANALYZE.' },
        { clause: 'loops=', text: 'how many times this node ran. Multiply it by actual time for the true cost.' },
        { clause: 'Rows Removed by Filter', text: 'work the engine did and then threw away — often the clue that an index is missing.' },
      ] },
      { type: 'heading', value: 'Scan types, from best to worst' },
      { type: 'table', headers: ['Node', 'Meaning', 'Verdict'], rows: [
        ['Index Only Scan', 'Answered entirely from the index, table never touched', 'Ideal'],
        ['Index Scan', 'Found rows via the index, then fetched them', 'Good'],
        ['Bitmap Heap Scan', 'Many index matches, gathered then fetched in disk order', 'Fine for medium result sets'],
        ['Seq Scan', 'Read the entire table', 'Correct on small tables; a red flag on large ones'],
      ] },
      { type: 'alert', value: 'A sequential scan is not automatically bad. On a 500-row table, reading everything is cheaper than the indirection of an index, and the planner knows that. Judge a Seq Scan by the table size and by Rows Removed by Filter, not by its name.' },
      { type: 'heading', value: 'Join strategies' },
      { type: 'table', headers: ['Strategy', 'How it works', 'Chosen when'], rows: [
        ['Nested Loop', 'For each left row, look up matching right rows', 'One side is small, or an index makes lookups cheap'],
        ['Hash Join', 'Build a hash table of one side, probe with the other', 'Both sides are large and the join is on equality'],
        ['Merge Join', 'Walk two sorted inputs in step', 'Both inputs are already sorted on the join key'],
      ] },
      { type: 'heading', value: 'A worked diagnosis' },
      { type: 'steps', title: 'The order to work through a slow query', steps: [
        { label: 'EXPLAIN ANALYZE', text: 'get the real plan and real timings. Never optimise from intuition.' },
        { label: 'Find the expensive node', text: 'look for the highest actual time × loops, not the highest cost estimate.' },
        { label: 'Check estimate vs actual', text: 'if rows=5 but actual rows=50000, run ANALYZE table_name to refresh statistics.' },
        { label: 'Look for Seq Scan on a big table', text: 'combined with a Filter that removes most rows, this means an index is missing.' },
        { label: 'Check for a function on the column', text: 'WHERE DATE(created_at) = ... cannot use a plain index. Rewrite as a range, or add an expression index.' },
        { label: 'Add one index', text: 'then re-run EXPLAIN ANALYZE and confirm the plan actually changed. Sometimes it will not.' },
      ] },
      { type: 'heading', value: 'The habits that prevent slow queries' },
      { type: 'list', items: [
        'SELECT the columns you need, not *. Fewer columns means less I/O and makes index-only scans possible.',
        'Keep columns bare in WHERE clauses so indexes remain usable.',
        'Filter as early as possible — reduce rows before joining and aggregating.',
        'Use keyset pagination rather than deep OFFSET.',
        'Run ANALYZE after a bulk load, so the planner is not working from stale statistics.',
        'Add the missing foreign key indexes.',
      ] },
      { type: 'code', language: 'sql', value: "-- Find your slowest queries in production (requires pg_stat_statements)\nSELECT calls,\n       ROUND(mean_exec_time::NUMERIC, 2) AS avg_ms,\n       ROUND(total_exec_time::NUMERIC, 0) AS total_ms,\n       LEFT(query, 80) AS query\nFROM   pg_stat_statements\nORDER BY total_exec_time DESC\nLIMIT 10;" },
      { type: 'alert', value: 'Optimise by total time, not by average. A query taking 5 ms but running two million times a day costs far more than a nightly report that takes 30 seconds.' },
    ],
    objectives: [
      'Read an EXPLAIN ANALYZE plan and locate the expensive node',
      'Recognise scan types and join strategies',
      'Diagnose a slow query methodically rather than by guesswork',
    ],
    takeaways: [
      'Estimated rows far from actual rows means stale statistics — run ANALYZE.',
      'Seq Scan is only a problem in proportion to the table size and rows discarded.',
      'Optimise by total time across all calls, not by the slowest single query.',
    ],
  },

  // ─────────────────────────── MODULE 10 ───────────────────────────
  'm10-l1': {
    title: 'Transactions',
    content: [
      { type: 'text', value: 'A transaction groups several statements into a single unit that either entirely happens or entirely does not. It is the mechanism that makes a database trustworthy for anything involving money, inventory or bookings.' },
      { type: 'diagram', name: 'sql-transaction', caption: 'Between BEGIN and COMMIT, the work is invisible to everyone else and reversible by you.' },
      { type: 'heading', value: 'The problem, concretely' },
      { type: 'code', language: 'sql', value: "-- Transferring 1000 between accounts is two statements\nUPDATE accounts SET balance = balance - 1000 WHERE id = 1;\n-- ← if the process dies here, 1000 has simply ceased to exist\nUPDATE accounts SET balance = balance + 1000 WHERE id = 2;" },
      { type: 'code', language: 'sql', value: "-- Wrapped in a transaction, there is no 'here' to die at:\nBEGIN;\n  UPDATE accounts SET balance = balance - 1000 WHERE id = 1;\n  UPDATE accounts SET balance = balance + 1000 WHERE id = 2;\nCOMMIT;\n\n-- A crash before COMMIT rolls both statements back automatically." },
      { type: 'heading', value: 'The commands' },
      { type: 'table', headers: ['Command', 'Effect'], rows: [
        ['BEGIN / START TRANSACTION', 'Open a transaction block'],
        ['COMMIT', 'Make every change permanent and visible to others'],
        ['ROLLBACK', 'Discard every change since BEGIN'],
        ['SAVEPOINT name', 'Mark a point you can partially roll back to'],
        ['ROLLBACK TO name', 'Undo back to that savepoint, keeping earlier work'],
      ] },
      { type: 'alert', value: 'Outside an explicit BEGIN, every single statement is its own transaction — this is autocommit. It is why a bare UPDATE with no WHERE is immediately and permanently applied.' },
      { type: 'heading', value: 'Transactions carry a real cost' },
      { type: 'text', value: 'While a transaction is open it holds locks and prevents cleanup of old row versions. A transaction left open for an hour by a script that forgot to commit can bloat tables and block other writers.' },
      { type: 'list', items: [
        'Keep transactions short — acquire locks late and release them quickly.',
        'Never wait on an external API call inside a transaction.',
        'Never wait for user input inside a transaction.',
        'Always ensure your application code commits or rolls back on every path, including exceptions.',
      ] },
      { type: 'code', language: 'javascript', value: "// The pattern every backend should use\nconst client = await pool.connect();\ntry {\n  await client.query('BEGIN');\n  await client.query('UPDATE accounts SET balance = balance - $1 WHERE id = $2', [amount, from]);\n  await client.query('UPDATE accounts SET balance = balance + $1 WHERE id = $2', [amount, to]);\n  await client.query('COMMIT');\n} catch (err) {\n  await client.query('ROLLBACK');\n  throw err;\n} finally {\n  client.release();   // the finally block is not optional\n}" },
      { type: 'warning', value: 'Forgetting the finally block leaks a connection on every error. The pool drains, and eventually every request hangs waiting for a connection that will never be returned. This is one of the most common production database incidents.' },
    ],
    objectives: [
      'Group statements into an atomic unit with BEGIN and COMMIT',
      'Roll back cleanly on failure',
      'Keep transactions short and always release the connection',
    ],
    takeaways: [
      'A transaction turns "two statements that might half-run" into one that cannot.',
      'Every statement outside BEGIN is its own autocommitted transaction.',
      'Long-open transactions hold locks and bloat tables — commit promptly.',
    ],
  },

  'm10-l2': {
    title: 'ACID Properties',
    content: [
      { type: 'text', value: 'ACID names the four guarantees a relational database makes about transactions. They are not abstract theory — each one corresponds to a specific way data would otherwise be corrupted.' },
      { type: 'heading', value: 'A — Atomicity' },
      { type: 'text', value: 'All statements in the transaction succeed, or none of them do. There is no partial state. This is what makes the money transfer safe.' },
      { type: 'text', value: 'Mechanism: PostgreSQL writes new row versions without removing the old ones. A COMMIT marks the new versions visible; a ROLLBACK simply never does, and the abandoned versions are cleaned up later by VACUUM.' },
      { type: 'heading', value: 'C — Consistency' },
      { type: 'text', value: 'A transaction moves the database from one valid state to another. Every constraint — primary keys, foreign keys, CHECK, NOT NULL — holds before it starts and holds after it commits. If any statement would break one, the whole transaction fails.' },
      { type: 'code', language: 'sql', value: "BEGIN;\n  INSERT INTO orders (user_id, total) VALUES (999, 50);\n  -- ERROR: FK violation — no user 999\nCOMMIT;   -- the transaction was already aborted; nothing is written" },
      { type: 'heading', value: 'I — Isolation' },
      { type: 'text', value: 'Concurrent transactions do not see each other partial work. How strictly this is enforced is configurable, because stricter isolation costs concurrency.' },
      { type: 'table', headers: ['Level', 'Prevents', 'Still allows'], rows: [
        ['READ UNCOMMITTED', 'Nothing', 'Dirty reads (not implemented in PostgreSQL)'],
        ['READ COMMITTED', 'Dirty reads', 'Non-repeatable reads, phantoms'],
        ['REPEATABLE READ', 'Dirty and non-repeatable reads', 'Some write skew'],
        ['SERIALIZABLE', 'Everything', 'Nothing — but transactions may be aborted and need retrying'],
      ] },
      { type: 'alert', value: 'PostgreSQL defaults to READ COMMITTED: each statement sees a snapshot taken at the moment that statement began. That means two SELECTs in one transaction can legitimately return different data. If you need them to agree, use REPEATABLE READ.' },
      { type: 'code', language: 'sql', value: "BEGIN ISOLATION LEVEL REPEATABLE READ;\n  SELECT SUM(balance) FROM accounts;    -- snapshot taken here\n  -- another transaction commits a change\n  SELECT SUM(balance) FROM accounts;    -- identical result: same snapshot\nCOMMIT;" },
      { type: 'heading', value: 'The three anomalies, concretely' },
      { type: 'table', headers: ['Anomaly', 'What happens'], rows: [
        ['Dirty read', 'You read a value another transaction wrote but has not committed — and it then rolls back'],
        ['Non-repeatable read', 'You read a row twice in one transaction and get different values, because someone committed in between'],
        ['Phantom read', 'You run the same query twice and the second run returns extra rows that were inserted in between'],
      ] },
      { type: 'heading', value: 'D — Durability' },
      { type: 'text', value: 'Once COMMIT returns, the change survives a crash, a power cut, or the process being killed. The mechanism is the write-ahead log: the change is written to the WAL and flushed to disk before COMMIT returns, even though the data files themselves are updated later.' },
      { type: 'warning', value: 'Durability depends on the disk actually flushing. Setting synchronous_commit = off makes commits faster by returning before the WAL is durable — you can lose the last fraction of a second of committed transactions in a crash. That is a legitimate trade for analytics, and never for payments.' },
      { type: 'heading', value: 'Why NoSQL often gives some of this up' },
      { type: 'text', value: 'Distributed systems face the CAP trade-off: when the network partitions, you must choose consistency or availability. Many NoSQL databases choose availability and offer eventual consistency instead of ACID. That is a reasonable engineering choice for a social feed and an unacceptable one for a ledger.' },
    ],
    objectives: [
      'Explain each ACID property and the failure it prevents',
      'Choose an isolation level for a given workload',
      'Identify dirty, non-repeatable and phantom reads',
    ],
    takeaways: [
      'Atomicity is all-or-nothing; Durability is survives-a-crash. They are different guarantees.',
      "PostgreSQL's READ COMMITTED default means two SELECTs in one transaction can disagree.",
      'Stricter isolation costs concurrency — pick the weakest level that is still correct.',
    ],
  },

  'm10-l3': {
    title: 'Rollback and Savepoints',
    content: [
      { type: 'text', value: 'ROLLBACK undoes everything since BEGIN. A savepoint gives you something finer: a marker you can return to without discarding the work that came before it.' },
      { type: 'code', language: 'sql', value: "BEGIN;\n  INSERT INTO departments (name, city) VALUES ('Design', 'Bengaluru');\n\n  SAVEPOINT after_dept;\n\n  INSERT INTO employees (name, dept_id, salary) VALUES ('Fay Nair', 99, 70000);\n  -- ERROR: FK violation, dept 99 does not exist\n\n  ROLLBACK TO SAVEPOINT after_dept;   -- undo only the failed insert\n\n  INSERT INTO employees (name, dept_id, salary) VALUES ('Fay Nair', 1, 70000);\nCOMMIT;   -- the Design department AND Fay are both saved" },
      { type: 'alert', value: 'This matters more than it first appears. In PostgreSQL, any error aborts the entire transaction — every subsequent statement fails with "current transaction is aborted" until you roll back. A savepoint is the only way to recover from an expected error and carry on.' },
      { type: 'heading', value: 'Where savepoints earn their keep' },
      { type: 'steps', title: 'Bulk import where some rows are known to be bad', steps: [
        { label: 'BEGIN', text: 'open one transaction for the whole import.' },
        { label: 'Per row: SAVEPOINT', text: 'mark a point before attempting each insert.' },
        { label: 'Try the INSERT', text: 'if it succeeds, RELEASE SAVEPOINT and move on.' },
        { label: 'On failure', text: 'ROLLBACK TO SAVEPOINT, record the row in a rejects table, continue.' },
        { label: 'COMMIT', text: 'every good row lands; every bad row is logged rather than aborting the run.' },
      ] },
      { type: 'code', language: 'javascript', value: "for (const row of rows) {\n  await client.query('SAVEPOINT row_sp');\n  try {\n    await client.query('INSERT INTO employees (name, dept_id) VALUES ($1, $2)', [row.name, row.dept]);\n    await client.query('RELEASE SAVEPOINT row_sp');\n  } catch (err) {\n    await client.query('ROLLBACK TO SAVEPOINT row_sp');\n    rejected.push({ row, reason: err.message });\n  }\n}" },
      { type: 'heading', value: 'The commands' },
      { type: 'table', headers: ['Statement', 'Effect'], rows: [
        ['SAVEPOINT name', 'Create a marker inside the current transaction'],
        ['ROLLBACK TO SAVEPOINT name', 'Undo back to the marker; the transaction stays open'],
        ['RELEASE SAVEPOINT name', 'Discard the marker, keeping the work'],
      ] },
      { type: 'warning', value: 'Savepoints are not free. Each one is effectively a nested subtransaction, and creating tens of thousands in a single transaction degrades performance noticeably. For large imports, batching — a savepoint per thousand rows rather than per row — is the usual compromise.' },
      { type: 'alert', value: 'Most ORMs expose savepoints as "nested transactions". Knowing that a nested transaction is really a savepoint explains why rolling one back does not undo the outer one.' },
    ],
    objectives: [
      'Recover from an error mid-transaction with a savepoint',
      'Implement partial-failure bulk imports',
      'Understand savepoints as the mechanism behind nested transactions',
    ],
    takeaways: [
      'In PostgreSQL any error aborts the whole transaction — a savepoint is the escape hatch.',
      'ROLLBACK TO SAVEPOINT keeps the transaction open and preserves earlier work.',
      'Savepoints have a real cost; batch them rather than creating one per row at scale.',
    ],
  },

  'm10-l4': {
    title: 'Locks and Deadlocks',
    content: [
      { type: 'text', value: 'When two transactions want the same row, the database must serialise them. It does this with locks — and locks, held in the wrong order, produce deadlocks.' },
      { type: 'heading', value: 'What gets locked' },
      { type: 'table', headers: ['Lock', 'Acquired by', 'Blocks'], rows: [
        ['Row-level exclusive', 'UPDATE, DELETE, SELECT FOR UPDATE', 'Other writers of the same row'],
        ['Row-level share', 'SELECT FOR SHARE', 'Writers, but not other readers'],
        ['Table-level ACCESS EXCLUSIVE', 'DROP, TRUNCATE, most ALTER TABLE', 'Absolutely everything, including SELECT'],
      ] },
      { type: 'alert', value: 'A crucial PostgreSQL property: readers never block writers, and writers never block readers. This is MVCC — a reader sees the previous committed version of a row rather than waiting for the writer. Only writer-versus-writer on the same row actually waits.' },
      { type: 'heading', value: 'The lost update, and how to prevent it' },
      { type: 'code', language: 'sql', value: "-- Two concurrent sessions both read 100, both write 99.\n-- One decrement is silently lost.\nSELECT stock FROM products WHERE id = 1;   -- 100\nUPDATE products SET stock = 99 WHERE id = 1;\n\n-- Fix 1: let the database do the arithmetic. The UPDATE takes the lock.\nUPDATE products SET stock = stock - 1 WHERE id = 1 AND stock > 0;\n\n-- Fix 2: lock the row explicitly while you decide\nBEGIN;\n  SELECT stock FROM products WHERE id = 1 FOR UPDATE;   -- others now wait\n  -- ... application logic ...\n  UPDATE products SET stock = stock - 1 WHERE id = 1;\nCOMMIT;" },
      { type: 'heading', value: 'Deadlocks' },
      { type: 'diagram', name: 'sql-deadlock', caption: 'Each transaction holds what the other needs. Neither can make progress, so the database breaks the tie.' },
      { type: 'code', language: 'sql', value: "-- Session A                        -- Session B\nBEGIN;                              BEGIN;\nUPDATE accounts SET ... WHERE id=1;  UPDATE accounts SET ... WHERE id=2;\n-- holds lock on row 1               -- holds lock on row 2\nUPDATE accounts SET ... WHERE id=2;  UPDATE accounts SET ... WHERE id=1;\n-- waits for B                       -- waits for A  → DEADLOCK" },
      { type: 'text', value: 'PostgreSQL detects the cycle automatically after a short timeout, kills one transaction with a deadlock detected error, and lets the other proceed. Your application must catch that error and retry.' },
      { type: 'heading', value: 'Preventing deadlocks' },
      { type: 'list', items: [
        'Acquire locks in a consistent order everywhere. If every code path updates accounts in ascending id order, the cycle above cannot form.',
        'Keep transactions short — fewer locks held for less time means fewer chances to collide.',
        'Do not hold a lock across a network call, a queue publish, or anything you do not control.',
        'Retry on deadlock. It is an expected condition under concurrency, not a bug to eliminate entirely.',
      ] },
      { type: 'code', language: 'sql', value: "-- Ordering the updates removes the cycle entirely\nBEGIN;\n  UPDATE accounts SET balance = balance - 100\n  WHERE  id = LEAST($1, $2);\n  UPDATE accounts SET balance = balance + 100\n  WHERE  id = GREATEST($1, $2);\nCOMMIT;" },
      { type: 'heading', value: 'Seeing what is blocked right now' },
      { type: 'code', language: 'sql', value: "SELECT pid,\n       state,\n       wait_event_type,\n       NOW() - query_start AS duration,\n       LEFT(query, 60) AS query\nFROM   pg_stat_activity\nWHERE  state <> 'idle'\nORDER BY duration DESC;\n\n-- Terminate a stuck session (last resort)\nSELECT pg_terminate_backend(12345);" },
      { type: 'warning', value: 'SELECT FOR UPDATE without a LIMIT or a narrow WHERE can lock far more rows than intended, turning a small write into a table-wide traffic jam. Lock the fewest rows you can, for the shortest time you can.' },
    ],
    objectives: [
      'Explain MVCC and why readers do not block writers',
      'Prevent lost updates with atomic UPDATE or SELECT FOR UPDATE',
      'Avoid deadlocks by ordering lock acquisition consistently',
    ],
    takeaways: [
      'In PostgreSQL, only writer-versus-writer on the same row actually waits.',
      'Consistent lock ordering is the one reliable structural fix for deadlocks.',
      'Deadlocks are expected under concurrency — catch the error and retry.',
    ],
  },

  // ─────────────────────────── MODULE 11 ───────────────────────────
  'm11-l1': {
    title: 'Functions vs Procedures',
    content: [
      { type: 'text', value: 'Both let you store logic inside the database and call it by name. The difference is what they can do and where they can be used.' },
      { type: 'compare', columns: [
        { title: 'Function', tone: 'olive', items: [
          'Must return a value (or a set of rows)',
          'Callable inside a SELECT, WHERE or JOIN',
          'Runs inside the caller transaction',
          'Cannot COMMIT or ROLLBACK',
          'Use for computation and reusable expressions',
        ] },
        { title: 'Procedure', tone: 'honey', items: [
          'Need not return anything',
          'Invoked with CALL, never inside a query',
          'Can manage its own transactions',
          'Can COMMIT and ROLLBACK internally',
          'Use for multi-step batch work',
        ] },
      ] },
      { type: 'code', language: 'sql', value: "-- Function: computes and returns\nCREATE FUNCTION annual_salary(monthly NUMERIC)\nRETURNS NUMERIC\nLANGUAGE sql IMMUTABLE\nAS $$ SELECT monthly * 12 $$;\n\nSELECT name, annual_salary(salary) FROM employees;\n\n-- Procedure: performs work, controls its own transactions\nCREATE PROCEDURE archive_old_orders(cutoff DATE)\nLANGUAGE plpgsql\nAS $$\nBEGIN\n  INSERT INTO orders_archive SELECT * FROM orders WHERE placed_at < cutoff;\n  DELETE FROM orders WHERE placed_at < cutoff;\n  COMMIT;\nEND;\n$$;\n\nCALL archive_old_orders('2023-01-01');" },
      { type: 'heading', value: 'Volatility — the marker that decides optimisation' },
      { type: 'text', value: 'Declaring how a function behaves lets the planner cache or inline it. Getting this wrong produces subtly wrong results, so it is worth understanding.' },
      { type: 'table', headers: ['Marker', 'Promise', 'Example'], rows: [
        ['IMMUTABLE', 'Same arguments always give the same result, forever', 'monthly * 12'],
        ['STABLE', 'Same result within one statement, may differ between statements', 'A function that reads a table'],
        ['VOLATILE (default)', 'May return anything, may have side effects', 'random(), NOW(), anything that writes'],
      ] },
      { type: 'warning', value: 'Marking a function IMMUTABLE when it reads a table lets PostgreSQL cache its result and even use it in an index. When the table changes, the cached value and the index are both silently wrong. Only mark something IMMUTABLE if it genuinely depends on nothing but its arguments.' },
      { type: 'heading', value: 'When to put logic in the database at all' },
      { type: 'compare', columns: [
        { title: 'Good reasons', tone: 'olive', items: [
          'The logic is data-heavy and would need many round trips otherwise',
          'The rule must hold regardless of which application writes',
          'Several different services need identical behaviour',
        ] },
        { title: 'Good reasons not to', tone: 'rose', items: [
          'Harder to version-control, test and review than application code',
          'Debugging tooling is far weaker',
          'Business logic scattered across two layers is hard to reason about',
          'Deployment is a migration, not a code push',
        ] },
      ] },
      { type: 'alert', value: 'The pragmatic middle ground most teams settle on: constraints and triggers in the database for data integrity, business logic in the application, and stored procedures reserved for heavy batch operations where round trips dominate.' },
    ],
    objectives: [
      'Distinguish functions from procedures by capability and call site',
      'Declare volatility correctly',
      'Judge when logic belongs in the database',
    ],
    takeaways: [
      'A function returns a value and runs inside a query; a procedure is CALLed and can manage transactions.',
      'Mislabelling a function IMMUTABLE causes silently stale results.',
      'Integrity rules belong in the database; business logic usually does not.',
    ],
  },

  'm11-l2': {
    title: 'Parameters and Return Types',
    content: [
      { type: 'heading', value: 'Parameter modes' },
      { type: 'table', headers: ['Mode', 'Meaning'], rows: [
        ['IN (default)', 'Input only'],
        ['OUT', 'Returned to the caller, not supplied by them'],
        ['INOUT', 'Supplied and returned'],
        ['VARIADIC', 'Accepts any number of trailing arguments'],
      ] },
      { type: 'code', language: 'sql', value: "-- Multiple OUT parameters give a function several return values\nCREATE FUNCTION dept_summary(\n  IN  p_dept_id  INT,\n  OUT headcount  INT,\n  OUT payroll    NUMERIC,\n  OUT avg_salary NUMERIC\n)\nLANGUAGE plpgsql\nAS $$\nBEGIN\n  SELECT COUNT(*), COALESCE(SUM(salary),0), COALESCE(AVG(salary),0)\n  INTO   headcount, payroll, avg_salary\n  FROM   employees\n  WHERE  dept_id = p_dept_id;\nEND;\n$$;\n\nSELECT * FROM dept_summary(1);\n-- headcount | payroll | avg_salary\n--         2 |  170000 |      85000" },
      { type: 'heading', value: 'Returning sets of rows' },
      { type: 'code', language: 'sql', value: "-- RETURNS TABLE: the clearest way to return multiple rows\nCREATE FUNCTION employees_in(p_city TEXT)\nRETURNS TABLE (id INT, name TEXT, salary NUMERIC)\nLANGUAGE sql STABLE\nAS $$\n  SELECT e.id, e.name, e.salary\n  FROM   employees e\n  JOIN   departments d ON d.id = e.dept_id\n  WHERE  d.city = p_city;\n$$;\n\n-- Use it exactly like a table\nSELECT * FROM employees_in('Pune') WHERE salary > 80000;" },
      { type: 'alert', value: 'A function returning TABLE composes with the rest of SQL — you can filter it, join it, aggregate over it. That is a genuine advantage over returning a cursor or a JSON blob.' },
      { type: 'heading', value: 'Defaults and named arguments' },
      { type: 'code', language: 'sql', value: "CREATE FUNCTION raise_salary(\n  p_employee_id INT,\n  p_percent     NUMERIC DEFAULT 5\n)\nRETURNS NUMERIC\nLANGUAGE plpgsql\nAS $$\nDECLARE new_salary NUMERIC;\nBEGIN\n  UPDATE employees\n  SET    salary = salary * (1 + p_percent / 100)\n  WHERE  id = p_employee_id\n  RETURNING salary INTO new_salary;\n\n  RETURN new_salary;\nEND;\n$$;\n\nSELECT raise_salary(1);                        -- default 5%\nSELECT raise_salary(1, 10);                    -- positional\nSELECT raise_salary(p_employee_id => 1, p_percent => 10);   -- named" },
      { type: 'heading', value: 'Overloading' },
      { type: 'text', value: 'PostgreSQL allows several functions with the same name and different parameter types. It is convenient and also a source of confusion — DROP FUNCTION must name the exact signature.' },
      { type: 'code', language: 'sql', value: "CREATE FUNCTION find_employee(p_id   INT)  RETURNS SETOF employees ...;\nCREATE FUNCTION find_employee(p_name TEXT) RETURNS SETOF employees ...;\n\nDROP FUNCTION find_employee(INT);   -- signature required" },
      { type: 'warning', value: 'Prefix parameter names (p_id rather than id) to avoid collisions with column names. If a parameter is called id and the function body says WHERE id = id, PL/pgSQL resolves both to the parameter — the condition is always true and the statement affects every row.' },
    ],
    objectives: [
      'Use IN, OUT, INOUT and VARIADIC parameters',
      'Return sets with RETURNS TABLE and compose them in queries',
      'Avoid parameter/column name collisions',
    ],
    takeaways: [
      'RETURNS TABLE keeps a function composable with the rest of SQL.',
      'Default and named arguments make signatures easier to evolve.',
      'Naming a parameter after a column is how you write an accidental UPDATE of every row.',
    ],
  },

  'm11-l3': {
    title: 'PL/pgSQL Basics',
    content: [
      { type: 'text', value: 'PL/pgSQL adds variables, conditionals, loops and exception handling to SQL. You need it whenever a task requires branching or iteration that a single statement cannot express.' },
      { type: 'heading', value: 'The block structure' },
      { type: 'code', language: 'sql', value: "CREATE OR REPLACE FUNCTION example(p_id INT)\nRETURNS TEXT\nLANGUAGE plpgsql\nAS $$\nDECLARE\n  v_name   TEXT;\n  v_salary NUMERIC;\nBEGIN\n  -- executable section\n  SELECT name, salary INTO v_name, v_salary\n  FROM   employees WHERE id = p_id;\n\n  IF NOT FOUND THEN\n    RAISE EXCEPTION 'Employee % not found', p_id;\n  END IF;\n\n  RETURN v_name || ' earns ' || v_salary;\n\nEXCEPTION\n  WHEN OTHERS THEN\n    RAISE NOTICE 'Failed: %', SQLERRM;\n    RETURN NULL;\nEND;\n$$;" },
      { type: 'alert', value: 'The $$ delimiters are dollar quoting. They let the function body contain single quotes without escaping every one of them. You can label them — $func$ ... $func$ — when a body itself contains $$.' },
      { type: 'heading', value: 'Control flow' },
      { type: 'code', language: 'sql', value: "-- Conditionals\nIF v_salary > 90000 THEN\n  v_band := 'senior';\nELSIF v_salary > 60000 THEN\n  v_band := 'mid';\nELSE\n  v_band := 'junior';\nEND IF;\n\n-- Loop over a query result\nFOR rec IN SELECT id, name FROM employees ORDER BY id LOOP\n  RAISE NOTICE 'Employee %: %', rec.id, rec.name;\nEND LOOP;\n\n-- Numeric loop\nFOR i IN 1..10 LOOP\n  INSERT INTO counters (n) VALUES (i);\nEND LOOP;\n\n-- Conditional loop\nWHILE v_remaining > 0 LOOP\n  v_remaining := v_remaining - 1;\nEND LOOP;" },
      { type: 'heading', value: 'Exception handling' },
      { type: 'code', language: 'sql', value: "BEGIN\n  INSERT INTO users (email) VALUES (p_email);\nEXCEPTION\n  WHEN unique_violation THEN\n    UPDATE users SET last_seen = NOW() WHERE email = p_email;\n  WHEN foreign_key_violation THEN\n    RAISE EXCEPTION 'Referenced record does not exist';\nEND;" },
      { type: 'warning', value: 'Every BEGIN ... EXCEPTION block creates an implicit savepoint, which is not free. A loop over a million rows with an exception handler inside it is dramatically slower than the same loop without one. Handle exceptions outside the loop where you can.' },
      { type: 'heading', value: 'Triggers — the main use of PL/pgSQL' },
      { type: 'code', language: 'sql', value: "-- 1. A trigger function returns TRIGGER and sees NEW and OLD\nCREATE OR REPLACE FUNCTION set_updated_at()\nRETURNS TRIGGER\nLANGUAGE plpgsql\nAS $$\nBEGIN\n  NEW.updated_at := NOW();\n  RETURN NEW;\nEND;\n$$;\n\n-- 2. Attach it to a table\nCREATE TRIGGER employees_updated_at\nBEFORE UPDATE ON employees\nFOR EACH ROW\nEXECUTE FUNCTION set_updated_at();" },
      { type: 'code', language: 'sql', value: "-- An audit trigger: record every change to a sensitive table\nCREATE OR REPLACE FUNCTION audit_salary_change()\nRETURNS TRIGGER LANGUAGE plpgsql AS $$\nBEGIN\n  IF NEW.salary IS DISTINCT FROM OLD.salary THEN\n    INSERT INTO salary_audit (employee_id, old_salary, new_salary, changed_at, changed_by)\n    VALUES (OLD.id, OLD.salary, NEW.salary, NOW(), CURRENT_USER);\n  END IF;\n  RETURN NEW;\nEND;\n$$;\n\nCREATE TRIGGER trg_audit_salary\nAFTER UPDATE ON employees\nFOR EACH ROW EXECUTE FUNCTION audit_salary_change();" },
      { type: 'text', value: 'Note the IS DISTINCT FROM rather than <>. An UPDATE that sets salary from NULL to a value should be audited, and <> would miss it.' },
      { type: 'alert', value: 'Triggers are invisible from the application side: a developer reading the INSERT statement has no indication that three other tables were also written. Use them for audit trails and derived timestamps — things nobody needs to reason about — and keep business logic where it can be read.' },
    ],
    objectives: [
      'Write PL/pgSQL blocks with variables and control flow',
      'Handle specific exceptions by name',
      'Implement audit and timestamp triggers',
    ],
    takeaways: [
      'Dollar quoting avoids escaping every quote in a function body.',
      'Exception blocks create implicit savepoints — keep them out of hot loops.',
      'Triggers act invisibly; reserve them for audit and housekeeping, not business rules.',
    ],
  },
};
