import { LessonMap, EMPLOYEES, DEPARTMENTS } from './types';

/** Module 6 (aggregation) + Module 7 (joins) + Module 8 (subqueries). */
export const analysisLessons: LessonMap = {
  // ─────────────────────────── MODULE 6 ───────────────────────────
  'm6-l1': {
    title: 'Aggregate Functions',
    content: [
      { type: 'text', value: 'Everything so far returned rows that already existed. Aggregate functions do something different: they consume many rows and produce one summary value. This is where SQL starts answering business questions rather than fetching records.' },
      { type: 'dataset', name: 'employees', ...EMPLOYEES },
      { type: 'queryResult', query: "SELECT COUNT(*)      AS headcount,\n       SUM(salary)   AS payroll,\n       ROUND(AVG(salary), 2) AS avg_salary,\n       MIN(salary)   AS lowest,\n       MAX(salary)   AS highest\nFROM   employees;", headers: ['headcount', 'payroll', 'avg_salary', 'lowest', 'highest'], rows: [['5', '349000', '69800.00', '51000', '92000']], note: 'Five input rows collapse to exactly one output row. That collapse is the defining behaviour of an aggregate.' },
      { type: 'heading', value: 'COUNT(*) and COUNT(column) are different functions' },
      { type: 'text', value: 'This distinction appears in interviews constantly, and it matters in real queries. COUNT(*) counts rows. COUNT(column) counts rows where that column is not NULL.' },
      { type: 'queryResult', query: "SELECT COUNT(*)                AS all_rows,\n       COUNT(dept_id)          AS with_department,\n       COUNT(DISTINCT dept_id) AS distinct_departments,\n       COUNT(DISTINCT salary)  AS distinct_salaries\nFROM   employees;", headers: ['all_rows', 'with_department', 'distinct_departments', 'distinct_salaries'], rows: [['5', '4', '2', '4']], note: "Eli's NULL department is counted by COUNT(*) but not by COUNT(dept_id). And Cy and Dia share a salary, so four distinct values out of five rows." },
      { type: 'heading', value: 'Every aggregate ignores NULL — except COUNT(*)' },
      { type: 'text', value: 'This is a feature, not an oversight. If three of ten reviews have no rating, AVG(rating) averages the seven that exist. Had NULL been treated as zero, your average would be wrong in a way nobody would notice.' },
      { type: 'code', language: 'sql', value: "-- Given ratings: 5, 4, NULL, 3\nSELECT COUNT(*),        -- 4  (rows)\n       COUNT(rating),   -- 3  (non-null values)\n       SUM(rating),     -- 12\n       AVG(rating)      -- 4.0  = 12 / 3, not 12 / 4\nFROM   reviews;\n\n-- To count NULLs as zero, say so explicitly\nSELECT AVG(COALESCE(rating, 0)) FROM reviews;   -- 3.0" },
      { type: 'heading', value: 'Conditional aggregation' },
      { type: 'text', value: 'A technique worth learning early: put a CASE inside an aggregate to count or sum only some of the rows. It lets one query produce several differently-filtered numbers in a single pass over the table.' },
      { type: 'queryResult', query: "SELECT COUNT(*) FILTER (WHERE salary > 70000) AS well_paid,\n       COUNT(*) FILTER (WHERE dept_id IS NULL) AS unassigned,\n       SUM(salary) FILTER (WHERE dept_id = 1)  AS engineering_payroll\nFROM   employees;", headers: ['well_paid', 'unassigned', 'engineering_payroll'], rows: [['2', '1', '170000']], note: 'FILTER is the clean PostgreSQL syntax. The portable equivalent is COUNT(CASE WHEN salary > 70000 THEN 1 END) — the CASE returns NULL otherwise, and COUNT skips NULLs.' },
      { type: 'warning', value: 'You cannot use an aggregate in WHERE. WHERE runs before aggregation, so at that point AVG(salary) does not exist yet. Filtering on an aggregate is what HAVING is for — the next lesson.' },
      { type: 'heading', value: 'Other aggregates worth knowing' },
      { type: 'table', headers: ['Function', 'Returns'], rows: [
        ['STRING_AGG(col, sep)', 'All values joined into one string'],
        ['ARRAY_AGG(col)', 'All values as an array'],
        ['BOOL_AND / BOOL_OR', 'Whether all / any values are true'],
        ['PERCENTILE_CONT(0.5)', 'The median (SQL has no MEDIAN function)'],
        ['STDDEV / VARIANCE', 'Statistical spread'],
      ] },
      { type: 'code', language: 'sql', value: "SELECT STRING_AGG(name, ', ' ORDER BY name) AS everyone\nFROM   employees;\n-- Ana Iyer, Bo Chen, Cy Das, Dia Rao, Eli Roy\n\nSELECT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY salary) AS median\nFROM   employees;   -- 64000" },
    ],
    objectives: [
      'Summarise a table with COUNT, SUM, AVG, MIN and MAX',
      'Explain how each aggregate treats NULL',
      'Produce several filtered metrics in one pass with FILTER',
    ],
    takeaways: [
      'Aggregates collapse many rows into one — that is what separates them from ordinary functions.',
      'COUNT(*) counts rows; COUNT(col) counts non-NULL values. They routinely differ.',
      'Aggregates cannot appear in WHERE, because WHERE runs before they are computed.',
    ],
  },

  'm6-l2': {
    title: 'GROUP BY and HAVING',
    content: [
      { type: 'text', value: 'An aggregate over the whole table gives one number. GROUP BY gives you one number per group — per department, per month, per customer. It is the clause that turns SQL into a reporting tool.' },
      { type: 'heading', value: 'How grouping actually works' },
      { type: 'steps', title: 'What the engine does with GROUP BY dept_id', steps: [
        { label: 'Partition', text: 'sort or hash the rows into buckets, one bucket per distinct dept_id value.' },
        { label: 'Aggregate', text: 'run each aggregate function separately inside every bucket.' },
        { label: 'Emit', text: 'produce exactly one output row per bucket.' },
        { label: 'HAVING', text: 'discard the buckets whose summary values fail the condition.' },
      ] },
      { type: 'dataset', name: 'employees', caption: 'the input: five rows, three distinct dept_id values including NULL', ...EMPLOYEES },
      { type: 'queryResult', query: "SELECT dept_id,\n       COUNT(*)              AS headcount,\n       SUM(salary)           AS payroll,\n       ROUND(AVG(salary), 0) AS avg_salary\nFROM   employees\nGROUP BY dept_id\nORDER BY dept_id;", headers: ['dept_id', 'headcount', 'payroll', 'avg_salary'], rows: [['1', '2', '170000', '85000'], ['2', '2', '128000', '64000'], ['', '1', '51000', '51000']], note: 'Three groups from five rows. Note that NULL forms its own group — GROUP BY treats all NULLs as equal, even though = does not.' },
      { type: 'heading', value: 'The rule that governs the SELECT list' },
      { type: 'text', value: 'Every column in the SELECT list must either appear in the GROUP BY, or be wrapped in an aggregate. There is no third option, and the reason is straightforward: a group of two employees has two names but only one count, so the engine would not know which name to print.' },
      { type: 'code', language: 'sql', value: "-- ERROR: column \"employees.name\" must appear in the GROUP BY clause\nSELECT dept_id, name, COUNT(*)\nFROM   employees\nGROUP BY dept_id;\n\n-- Fix 1: group by it too (now one row per department per name)\nSELECT dept_id, name, COUNT(*) FROM employees GROUP BY dept_id, name;\n\n-- Fix 2: aggregate it, saying which name you want\nSELECT dept_id, MIN(name) AS first_alphabetically, COUNT(*)\nFROM   employees GROUP BY dept_id;\n\n-- Fix 3: collect them all\nSELECT dept_id, STRING_AGG(name, ', ') AS members, COUNT(*)\nFROM   employees GROUP BY dept_id;" },
      { type: 'warning', value: 'MySQL historically allowed the first query and silently returned an arbitrary name. That behaviour has caused an enormous amount of quietly wrong reporting. PostgreSQL rejects it, which is the correct and kinder choice.' },
      { type: 'heading', value: 'WHERE versus HAVING' },
      { type: 'text', value: 'They both filter, but at different stages, and that stage is the entire distinction. WHERE removes rows before grouping. HAVING removes groups after aggregation.' },
      { type: 'diagram', name: 'sql-execution-order', caption: 'WHERE runs at step 3, GROUP BY at step 4, HAVING at step 5. That ordering is the whole answer.' },
      { type: 'compare', columns: [
        { title: 'WHERE', tone: 'olive', subtitle: 'filters rows, before grouping', items: [
          'Sees individual rows',
          'Cannot reference an aggregate',
          'Reduces work for the grouping step',
          'Can use an index',
        ] },
        { title: 'HAVING', tone: 'honey', subtitle: 'filters groups, after aggregating', items: [
          'Sees one summary row per group',
          'Exists precisely to reference aggregates',
          'Runs on already-computed results',
          'Cannot use an index',
        ] },
      ] },
      { type: 'queryResult', query: "SELECT dept_id, COUNT(*) AS headcount, ROUND(AVG(salary),0) AS avg_salary\nFROM   employees\nWHERE  salary > 55000        -- drops Eli (51000) before grouping\nGROUP BY dept_id\nHAVING AVG(salary) > 70000   -- drops Sales (64000) after grouping\nORDER BY avg_salary DESC;", headers: ['dept_id', 'headcount', 'avg_salary'], rows: [['1', '2', '85000']], note: 'Read it in execution order: five rows → WHERE leaves four → grouped into two → HAVING leaves one. Swapping the two conditions would give a different, wrong answer.' },
      { type: 'heading', value: 'Grouping by an expression' },
      { type: 'queryResult', query: "SELECT EXTRACT(YEAR FROM hired_on)::INT AS hire_year,\n       COUNT(*)                         AS hires\nFROM   employees\nGROUP BY hire_year\nORDER BY hire_year;", headers: ['hire_year', 'hires'], rows: [['2020', '1'], ['2021', '1'], ['2022', '1'], ['2023', '2']], note: 'GROUP BY accepts an output alias in PostgreSQL. Grouping by DATE_TRUNC(\'month\', ...) is the same pattern and is how every monthly chart is built.' },
      { type: 'alert', value: 'A useful sanity check on any GROUP BY query: does SUM of the per-group counts equal COUNT(*) on the raw table? If it does not, a join is duplicating rows or a WHERE is dropping more than you thought.' },
    ],
    objectives: [
      'Group rows and compute per-group aggregates',
      'Satisfy the SELECT-list rule correctly',
      'Choose between WHERE and HAVING based on execution stage',
    ],
    takeaways: [
      'GROUP BY partitions rows into buckets and emits one row per bucket.',
      'WHERE filters rows before grouping; HAVING filters groups after.',
      'Every selected column must be grouped or aggregated — no exceptions.',
    ],
  },

  // ─────────────────────────── MODULE 7 ───────────────────────────
  'm7-l1': {
    title: 'INNER JOIN',
    content: [
      { type: 'text', value: 'Normalisation splits data across tables so each fact is stored once. Joins put it back together for the duration of one query. A join is not a permanent link — it is an instruction to match rows from two tables on a condition, for this query only.' },
      { type: 'dataset', name: 'employees', ...EMPLOYEES },
      { type: 'dataset', name: 'departments', ...DEPARTMENTS },
      { type: 'heading', value: 'INNER JOIN keeps only matched rows' },
      { type: 'diagram', name: 'sql-join-inner', caption: 'Only the overlap survives: rows that have a partner on both sides.' },
      { type: 'queryResult', query: "SELECT e.name    AS employee,\n       d.name    AS department,\n       d.city\nFROM   employees e\nINNER JOIN departments d ON d.id = e.dept_id\nORDER BY e.id;", headers: ['employee', 'department', 'city'], rows: [
        ['Ana Iyer', 'Engineering', 'Pune'],
        ['Bo Chen', 'Engineering', 'Pune'],
        ['Cy Das', 'Sales', 'Mumbai'],
        ['Dia Rao', 'Sales', 'Mumbai'],
      ], note: 'Five employees in, four rows out. Eli has no dept_id, so no department row matched — and INNER JOIN silently drops unmatched rows.' },
      { type: 'text', value: 'Notice what is missing in both directions. Eli disappeared because their dept_id is NULL. Legal disappeared because no employee references it. An INNER JOIN is symmetric in that sense: anything without a partner is gone.' },
      { type: 'heading', value: 'How the engine builds that result' },
      { type: 'steps', steps: [
        { label: 'Take a row', text: 'from employees — say Ana, dept_id = 1.' },
        { label: 'Find partners', text: 'look in departments for every row where id = 1. That finds Engineering.' },
        { label: 'Combine', text: 'emit one output row containing every column from both.' },
        { label: 'Repeat', text: 'for every employee. If a row finds no partner, INNER JOIN emits nothing for it.' },
      ] },
      { type: 'alert', value: 'If one employee could match two department rows, you would get two output rows for that employee. A join can return more rows than either input table — that is not a bug, it is what matching means.' },
      { type: 'heading', value: 'Aliases make joins readable' },
      { type: 'code', language: 'sql', value: "-- Without aliases: verbose, and ambiguous columns must be fully qualified\nSELECT employees.name, departments.name\nFROM   employees\nJOIN   departments ON departments.id = employees.dept_id;\n\n-- With aliases: the standard style\nSELECT e.name AS employee, d.name AS department\nFROM   employees e\nJOIN   departments d ON d.id = e.dept_id;" },
      { type: 'warning', value: 'Both tables have a column called name. Selecting a bare name would be ambiguous and error; and selecting both without aliasing them gives you two columns with the same header. Always alias overlapping output columns.' },
      { type: 'heading', value: 'JOIN, INNER JOIN and the old comma syntax' },
      { type: 'code', language: 'sql', value: "-- These three are identical in meaning\nFROM employees e JOIN       departments d ON d.id = e.dept_id\nFROM employees e INNER JOIN departments d ON d.id = e.dept_id\nFROM employees e, departments d WHERE d.id = e.dept_id   -- pre-1992 style" },
      { type: 'alert', value: 'Prefer explicit JOIN ... ON. The comma form mixes join conditions with filter conditions in one WHERE clause, so forgetting one condition silently produces a cross join instead of an error. Explicit syntax also makes outer joins possible at all.' },
      { type: 'heading', value: 'Joining three tables' },
      { type: 'code', language: 'sql', value: "SELECT u.name    AS customer,\n       o.id      AS order_id,\n       p.name    AS product,\n       oi.quantity\nFROM   users u\nJOIN   orders      o  ON o.user_id  = u.id\nJOIN   order_items oi ON oi.order_id = o.id\nJOIN   products    p  ON p.id       = oi.product_id\nWHERE  o.placed_at >= '2024-01-01'\nORDER BY o.id;" },
      { type: 'text', value: 'Joins chain left to right: the result of the first join becomes the left input to the second. There is no practical limit, though beyond five or six tables it is usually worth asking whether a CTE would make the query readable.' },
    ],
    objectives: [
      'Combine tables with INNER JOIN and read the result',
      'Explain why unmatched rows disappear from both sides',
      'Chain joins across three or more tables with aliases',
    ],
    takeaways: [
      'INNER JOIN keeps only rows with a partner — unmatched rows vanish without warning.',
      'A join can return more rows than either input if matches are not one-to-one.',
      'Explicit JOIN ... ON separates matching from filtering; the comma form conflates them.',
    ],
  },

  'm7-l2': {
    title: 'LEFT and RIGHT JOIN',
    content: [
      { type: 'text', value: 'INNER JOIN answers "which employees have a department?". Outer joins answer the far more common business question: "list every employee, and show their department if they have one." Keeping the unmatched rows is usually the entire point.' },
      { type: 'heading', value: 'LEFT JOIN — keep every row from the left table' },
      { type: 'diagram', name: 'sql-join-left', caption: 'Everything in A survives. Where B has no match, its columns come back as NULL.' },
      { type: 'queryResult', query: "SELECT e.name AS employee,\n       d.name AS department\nFROM   employees e\nLEFT JOIN departments d ON d.id = e.dept_id\nORDER BY e.id;", headers: ['employee', 'department'], rows: [
        ['Ana Iyer', 'Engineering'],
        ['Bo Chen', 'Engineering'],
        ['Cy Das', 'Sales'],
        ['Dia Rao', 'Sales'],
        ['Eli Roy', ''],
      ], highlightRows: [4], note: 'Five rows in, five rows out. Eli is kept, with NULL standing in for every column that would have come from departments.' },
      { type: 'alert', value: 'A LEFT JOIN can never return fewer rows than the left table has. If yours does, the cause is almost always a condition in WHERE that should have been in ON — see below.' },
      { type: 'heading', value: 'The mistake that turns a LEFT JOIN back into an INNER JOIN' },
      { type: 'text', value: 'This is the single most common outer-join bug. Filtering on a right-table column in WHERE discards the NULL-padded rows you just worked to keep — because NULL fails every comparison.' },
      { type: 'code', language: 'sql', value: "-- Broken: the WHERE runs after the join and drops Eli's NULL city\nSELECT e.name, d.name\nFROM   employees e\nLEFT JOIN departments d ON d.id = e.dept_id\nWHERE  d.city = 'Pune';       -- Eli's city is NULL → excluded\n\n-- Correct: put the condition in ON, so it restricts matching, not the result\nSELECT e.name, d.name\nFROM   employees e\nLEFT JOIN departments d ON d.id = e.dept_id AND d.city = 'Pune';" },
      { type: 'syntax', title: 'The rule to remember', parts: [
        { clause: 'ON', text: 'decides which rows count as a match. Restricting here keeps unmatched left rows, padded with NULL.' },
        { clause: 'WHERE', text: 'filters the finished result. Restricting here removes rows entirely, NULL-padded ones included.' },
      ] },
      { type: 'heading', value: 'The anti-join: finding rows with no match' },
      { type: 'text', value: 'Deliberately combining the two gives you one of the most useful patterns in SQL — customers with no orders, products never sold, users who never logged in.' },
      { type: 'diagram', name: 'sql-join-left-anti', caption: 'LEFT JOIN then filter for NULL: only the rows that failed to match survive.' },
      { type: 'queryResult', query: "SELECT e.name AS employee\nFROM   employees e\nLEFT JOIN departments d ON d.id = e.dept_id\nWHERE  d.id IS NULL;", headers: ['employee'], rows: [['Eli Roy']], note: 'Here the WHERE on a right-table column is intentional: d.id can only be NULL for rows that found no partner.' },
      { type: 'heading', value: 'RIGHT JOIN — the mirror image' },
      { type: 'diagram', name: 'sql-join-right', caption: 'Everything in B survives; unmatched left columns become NULL.' },
      { type: 'queryResult', query: "SELECT e.name AS employee,\n       d.name AS department\nFROM   employees e\nRIGHT JOIN departments d ON d.id = e.dept_id\nORDER BY d.id;", headers: ['employee', 'department'], rows: [
        ['Ana Iyer', 'Engineering'],
        ['Bo Chen', 'Engineering'],
        ['Cy Das', 'Sales'],
        ['Dia Rao', 'Sales'],
        ['', 'Legal'],
      ], highlightRows: [4], note: 'Now Legal is kept — a department with no employees — and Eli is dropped. Exactly the opposite of the LEFT JOIN above.' },
      { type: 'alert', value: 'Every RIGHT JOIN can be written as a LEFT JOIN by swapping the table order, and in practice almost everyone does. Reading a query is easier when every join extends the same direction, so most codebases use LEFT JOIN exclusively.' },
      { type: 'heading', value: 'A realistic use: counting including the zeros' },
      { type: 'code', language: 'sql', value: "-- Every department, including those with nobody in them\nSELECT d.name                    AS department,\n       COUNT(e.id)               AS headcount\nFROM   departments d\nLEFT JOIN employees e ON e.dept_id = d.id\nGROUP BY d.name\nORDER BY headcount DESC;\n\n-- Engineering  2\n-- Sales        2\n-- Legal        0" },
      { type: 'warning', value: 'Use COUNT(e.id), not COUNT(*), in that query. For Legal there is one NULL-padded row, so COUNT(*) would report 1 employee instead of 0. Counting a column from the outer-joined side is what makes the zero come out right.' },
    ],
    objectives: [
      'Preserve unmatched rows with LEFT and RIGHT JOIN',
      'Place conditions in ON versus WHERE deliberately',
      'Use the anti-join pattern to find rows with no match',
    ],
    takeaways: [
      'A condition on the right table belongs in ON; putting it in WHERE silently reverts to an INNER JOIN.',
      'LEFT JOIN … WHERE right.id IS NULL is the standard "find the missing" pattern.',
      'With an outer join, COUNT(*) counts NULL-padded rows — count a real column instead.',
    ],
  },

  'm7-l3': {
    title: 'FULL, SELF and CROSS JOIN',
    content: [
      { type: 'heading', value: 'FULL OUTER JOIN — keep everything from both sides' },
      { type: 'diagram', name: 'sql-join-full', caption: 'Matched rows, plus unmatched rows from the left, plus unmatched rows from the right.' },
      { type: 'queryResult', query: "SELECT e.name AS employee,\n       d.name AS department\nFROM   employees e\nFULL OUTER JOIN departments d ON d.id = e.dept_id\nORDER BY d.id NULLS LAST;", headers: ['employee', 'department'], rows: [
        ['Ana Iyer', 'Engineering'],
        ['Bo Chen', 'Engineering'],
        ['Cy Das', 'Sales'],
        ['Dia Rao', 'Sales'],
        ['', 'Legal'],
        ['Eli Roy', ''],
      ], highlightRows: [4, 5], note: 'Six rows: the four matches, plus the department with nobody in it, plus the employee with no department. Nothing is lost from either side.' },
      { type: 'text', value: 'FULL JOIN is comparatively rare in application code but invaluable for reconciliation — comparing two systems and finding what exists in one but not the other.' },
      { type: 'code', language: 'sql', value: "-- Reconciliation: what is in one ledger but not the other?\nSELECT COALESCE(a.txn_id, b.txn_id) AS txn_id,\n       a.amount AS ours,\n       b.amount AS theirs\nFROM   our_ledger a\nFULL OUTER JOIN bank_ledger b ON b.txn_id = a.txn_id\nWHERE  a.txn_id IS NULL          -- only they have it\n   OR  b.txn_id IS NULL          -- only we have it\n   OR  a.amount <> b.amount;     -- both have it, amounts disagree" },
      { type: 'heading', value: 'SELF JOIN — a table joined to itself' },
      { type: 'text', value: 'Nothing special is required; you simply list the same table twice with different aliases. It is how you model hierarchies: an employee whose manager is another employee.' },
      { type: 'code', language: 'sql', value: "-- Assume employees also has a manager_id column referencing employees.id\nSELECT e.name    AS employee,\n       m.name    AS manager\nFROM   employees e\nLEFT JOIN employees m ON m.id = e.manager_id\nORDER BY e.id;" },
      { type: 'alert', value: 'Use LEFT JOIN for the manager lookup, not INNER JOIN. The person at the top of the hierarchy has no manager, and an INNER JOIN would quietly remove the CEO from your org chart.' },
      { type: 'code', language: 'sql', value: "-- Another classic: find pairs, without duplicates or self-pairs\nSELECT a.name, b.name, a.salary\nFROM   employees a\nJOIN   employees b ON b.salary = a.salary\n                 AND b.id     > a.id;    -- > not <>, so each pair appears once\n\n-- Returns: Cy Das, Dia Rao, 64000" },
      { type: 'heading', value: 'CROSS JOIN — every combination' },
      { type: 'diagram', name: 'sql-join-cross', caption: 'No ON clause: every row on the left is paired with every row on the right.' },
      { type: 'text', value: 'A cross join has no matching condition, so the result size is simply the product of the two inputs. Five employees crossed with three departments gives fifteen rows.' },
      { type: 'code', language: 'sql', value: "SELECT e.name, d.name\nFROM   employees e\nCROSS JOIN departments d;\n-- 5 × 3 = 15 rows\n\n-- Genuinely useful case: generate a complete date series so a report\n-- shows zero-rows for days with no sales instead of skipping them\nSELECT d.day, p.name, COALESCE(SUM(s.amount), 0) AS revenue\nFROM   GENERATE_SERIES('2024-01-01'::DATE, '2024-01-31'::DATE, '1 day') AS d(day)\nCROSS JOIN products p\nLEFT JOIN sales s ON s.sold_on = d.day AND s.product_id = p.id\nGROUP BY d.day, p.name\nORDER BY d.day;" },
      { type: 'warning', value: 'An accidental cross join is the classic runaway query: forget the ON clause between two tables of 100,000 rows and you have asked for ten billion rows. If a query is inexplicably slow, checking that every join has a condition is the first thing to do.' },
      { type: 'heading', value: 'Choosing the right join' },
      { type: 'table', headers: ['The question you are answering', 'Join to use'], rows: [
        ['Only records that have a match on both sides', 'INNER JOIN'],
        ['Every record from this table, matched where possible', 'LEFT JOIN'],
        ['Records from this table that have no match', 'LEFT JOIN + WHERE right.id IS NULL'],
        ['Everything from both, matched where possible', 'FULL OUTER JOIN'],
        ['Rows related to other rows in the same table', 'SELF JOIN'],
        ['Every possible combination', 'CROSS JOIN'],
      ] },
    ],
    objectives: [
      'Use FULL OUTER JOIN for reconciliation between two sources',
      'Write self joins for hierarchies and pair-finding',
      'Recognise when a CROSS JOIN is intentional and when it is a bug',
    ],
    takeaways: [
      'FULL JOIN loses nothing from either side — ideal for comparing two systems.',
      'A self join is just the same table twice with two aliases.',
      'A missing ON clause turns a join into a cross join, and the row count explodes.',
    ],
  },

  // ─────────────────────────── MODULE 8 ───────────────────────────
  'm8-l1': {
    title: 'Subqueries — Scalar, Row and Table',
    content: [
      { type: 'text', value: 'A subquery is a SELECT nested inside another statement. Its job is to compute something the outer query needs but cannot express directly — a threshold, a set of ids, or a derived table.' },
      { type: 'diagram', name: 'sql-subquery-flow', caption: 'The inner query is evaluated first; the outer query then behaves as if you had typed the result yourself.' },
      { type: 'heading', value: 'Scalar subquery — returns exactly one value' },
      { type: 'text', value: 'The most common form. "Everyone earning above average" cannot be written with a plain WHERE, because AVG is not available at row-filtering time. A subquery computes it first.' },
      { type: 'queryResult', query: "SELECT name, salary\nFROM   employees\nWHERE  salary > (SELECT AVG(salary) FROM employees)\nORDER BY salary DESC;", headers: ['name', 'salary'], rows: [['Ana Iyer', '92000'], ['Bo Chen', '78000']], note: 'The inner query returns 69800. The outer query then runs as if you had written WHERE salary > 69800.' },
      { type: 'code', language: 'sql', value: "-- A scalar subquery can also sit in the SELECT list\nSELECT name,\n       salary,\n       salary - (SELECT AVG(salary) FROM employees) AS vs_average\nFROM   employees;" },
      { type: 'warning', value: 'A scalar subquery that returns more than one row raises an error at runtime, not at parse time. Queries that work in development on small data can fail in production when a second matching row appears. Add LIMIT 1, or an aggregate, when the single-row guarantee is not structural.' },
      { type: 'heading', value: 'Multi-row subquery — returns a set' },
      { type: 'code', language: 'sql', value: "-- IN: matches any value in the set\nSELECT name FROM employees\nWHERE  dept_id IN (SELECT id FROM departments WHERE city = 'Pune');\n\n-- ANY / SOME: compares against any member\nSELECT name FROM employees\nWHERE  salary > ANY (SELECT salary FROM employees WHERE dept_id = 2);\n-- true if greater than at least one Sales salary\n\n-- ALL: must satisfy the comparison against every member\nSELECT name FROM employees\nWHERE  salary > ALL (SELECT salary FROM employees WHERE dept_id = 2);\n-- true only if greater than every Sales salary" },
      { type: 'queryResult', query: "SELECT name, salary FROM employees\nWHERE  salary > ALL (SELECT salary FROM employees WHERE dept_id = 2);", headers: ['name', 'salary'], rows: [['Ana Iyer', '92000'], ['Bo Chen', '78000']], note: 'Sales salaries are 64000 and 64000. Ana and Bo both exceed every one of them; Eli at 51000 does not.' },
      { type: 'heading', value: 'Table subquery — a derived table in FROM' },
      { type: 'code', language: 'sql', value: "-- Aggregate first, then filter and join the summary\nSELECT d.name AS department, s.headcount, s.avg_salary\nFROM   (\n         SELECT dept_id,\n                COUNT(*)              AS headcount,\n                ROUND(AVG(salary), 0) AS avg_salary\n         FROM   employees\n         GROUP BY dept_id\n       ) AS s\nJOIN   departments d ON d.id = s.dept_id\nWHERE  s.headcount >= 2;" },
      { type: 'alert', value: 'A derived table must be given an alias — AS s here — even if you never reference it. PostgreSQL rejects the query without one.' },
      { type: 'heading', value: 'The three shapes at a glance' },
      { type: 'table', headers: ['Shape', 'Returns', 'Where it can appear'], rows: [
        ['Scalar', 'One row, one column', 'SELECT list, WHERE, HAVING — anywhere a value fits'],
        ['Multi-row', 'Many rows, one column', 'With IN, ANY, ALL, EXISTS'],
        ['Table', 'Many rows, many columns', 'FROM and JOIN clauses'],
      ] },
      { type: 'alert', value: 'Once a query has more than one subquery, a CTE (Module 14) will usually read far better. WITH lets you name each step and reference it more than once, turning a nested query inside-out into a readable sequence.' },
    ],
    objectives: [
      'Write scalar, multi-row and table subqueries',
      'Choose between IN, ANY and ALL',
      'Recognise when a derived table is the right structure',
    ],
    takeaways: [
      'A scalar subquery computes a value the outer query cannot see for itself.',
      'A subquery returning two rows where one was expected fails at runtime, not at parse time.',
      'Derived tables need an alias; beyond two subqueries, prefer a CTE.',
    ],
  },

  'm8-l2': {
    title: 'Correlated Subqueries, EXISTS and Nth-Highest',
    content: [
      { type: 'heading', value: 'Correlated subqueries' },
      { type: 'text', value: 'An ordinary subquery runs once. A correlated subquery references a column from the outer query, so it must be re-evaluated for every outer row — conceptually a loop.' },
      { type: 'code', language: 'sql', value: "-- For each employee, compare against their own department's average\nSELECT e.name, e.salary, e.dept_id\nFROM   employees e\nWHERE  e.salary > (\n         SELECT AVG(salary)\n         FROM   employees x\n         WHERE  x.dept_id = e.dept_id     -- ← the correlation\n       );" },
      { type: 'queryResult', query: "SELECT e.name, e.salary, e.dept_id\nFROM   employees e\nWHERE  e.salary > (SELECT AVG(salary) FROM employees x WHERE x.dept_id = e.dept_id);", headers: ['name', 'salary', 'dept_id'], rows: [['Ana Iyer', '92000', '1']], note: 'Engineering averages 85000, so only Ana clears her own department bar. Sales averages 64000 and both members sit exactly on it, so neither exceeds it.' },
      { type: 'alert', value: 'A correlated subquery is readable but potentially slow: a thousand outer rows means a thousand inner executions. Modern PostgreSQL often rewrites them into joins, but a window function (Module 14) is usually both faster and clearer for this shape of question.' },
      { type: 'heading', value: 'EXISTS — asking whether any row matches' },
      { type: 'text', value: 'EXISTS returns true as soon as the subquery produces its first row, then stops. It does not care what the subquery selects, which is why the convention is SELECT 1.' },
      { type: 'code', language: 'sql', value: "-- Departments that have at least one employee\nSELECT d.name\nFROM   departments d\nWHERE  EXISTS (SELECT 1 FROM employees e WHERE e.dept_id = d.id);\n\n-- Departments with nobody in them\nSELECT d.name\nFROM   departments d\nWHERE  NOT EXISTS (SELECT 1 FROM employees e WHERE e.dept_id = d.id);\n-- Legal" },
      { type: 'heading', value: 'EXISTS versus IN — and why it matters' },
      { type: 'compare', columns: [
        { title: 'IN (subquery)', tone: 'honey', items: [
          'Builds the full result set, then checks membership',
          'Breaks badly if the set contains NULL (NOT IN returns nothing)',
          'Fine for small, known sets',
        ] },
        { title: 'EXISTS (subquery)', tone: 'olive', items: [
          'Stops at the first matching row',
          'Handles NULL correctly — it only asks "is there a row?"',
          'Preferred for correlated checks and large sets',
        ] },
      ] },
      { type: 'code', language: 'sql', value: "-- Dangerous: if any department id is NULL, this returns zero rows. Always.\nSELECT name FROM employees\nWHERE  dept_id NOT IN (SELECT id FROM departments WHERE city = 'Delhi');\n\n-- Safe: NOT EXISTS has no NULL failure mode\nSELECT e.name FROM employees e\nWHERE  NOT EXISTS (\n         SELECT 1 FROM departments d\n         WHERE  d.id = e.dept_id AND d.city = 'Delhi'\n       );" },
      { type: 'warning', value: 'This NOT IN behaviour is not a quirk to memorise for interviews — it causes silent production bugs. A query that returned rows for months starts returning none the day a single NULL appears in the referenced column. Default to NOT EXISTS.' },
      { type: 'heading', value: 'The Nth-highest salary — the classic interview question' },
      { type: 'text', value: 'There are three good answers, and knowing why they differ is more valuable than memorising any one of them.' },
      { type: 'code', language: 'sql', value: "-- 1. OFFSET: simplest, but treats ties as separate rows\nSELECT DISTINCT salary FROM employees\nORDER BY salary DESC\nLIMIT 1 OFFSET 1;          -- 2nd highest → 78000\n\n-- 2. Correlated subquery: the classic pre-window-function answer\nSELECT DISTINCT e.salary FROM employees e\nWHERE  1 = (SELECT COUNT(DISTINCT x.salary) FROM employees x\n            WHERE x.salary > e.salary);\n\n-- 3. DENSE_RANK: the modern answer, and the one to give in an interview\nSELECT salary FROM (\n  SELECT salary, DENSE_RANK() OVER (ORDER BY salary DESC) AS rnk\n  FROM   employees\n) t\nWHERE  rnk = 2;            -- 78000" },
      { type: 'heading', value: 'Why ties make RANK and DENSE_RANK differ' },
      { type: 'queryResult', query: "SELECT name, salary,\n       ROW_NUMBER() OVER (ORDER BY salary DESC) AS row_num,\n       RANK()       OVER (ORDER BY salary DESC) AS rank,\n       DENSE_RANK() OVER (ORDER BY salary DESC) AS dense_rank\nFROM   employees;", headers: ['name', 'salary', 'row_num', 'rank', 'dense_rank'], rows: [
        ['Ana Iyer', '92000', '1', '1', '1'],
        ['Bo Chen', '78000', '2', '2', '2'],
        ['Cy Das', '64000', '3', '3', '3'],
        ['Dia Rao', '64000', '4', '3', '3'],
        ['Eli Roy', '51000', '5', '5', '4'],
      ], note: 'Cy and Dia tie. ROW_NUMBER breaks the tie arbitrarily; RANK gives both 3 and then skips to 5; DENSE_RANK gives both 3 and continues at 4. For "the Nth distinct salary", DENSE_RANK is the one that matches the question.' },
      { type: 'alert', value: 'The right follow-up question in an interview is "should tied salaries count as one place or two?". Asking it demonstrates more than producing any of the three queries from memory.' },
    ],
    objectives: [
      'Write correlated subqueries and understand their cost',
      'Prefer EXISTS over IN for correlated and NULL-prone checks',
      'Solve Nth-highest three ways and explain the tie-handling difference',
    ],
    takeaways: [
      'A correlated subquery re-runs per outer row — readable, but often replaceable by a window function.',
      'NOT IN with a NULL in the set returns zero rows; NOT EXISTS does not have this failure.',
      'ROW_NUMBER, RANK and DENSE_RANK differ only on ties — and ties are exactly what Nth-highest is about.',
    ],
  },
};
