import { LessonMap } from './types';

/** Module 15 (backend) + 16 (projects) + 17 (interview) + assessment, certification, capstone. */
export const appliedLessons: LessonMap = {
  // ─────────────────────────── MODULE 15 ───────────────────────────
  'm15-l1': {
    title: 'Node.js + SQL Connections',
    content: [
      { type: 'text', value: 'Connecting a backend to PostgreSQL involves three decisions that matter far more than the syntax: pool or single connection, parameterised or concatenated queries, and where transactions are managed.' },
      { type: 'heading', value: 'Always use a pool' },
      { type: 'diagram', name: 'sql-connection-pool', caption: 'Opening a connection costs tens of milliseconds. Borrowing one from a pool costs microseconds.' },
      { type: 'code', language: 'javascript', value: "import { Pool } from 'pg';\n\nexport const pool = new Pool({\n  host: process.env.PGHOST,\n  port: 5432,\n  database: process.env.PGDATABASE,\n  user: process.env.PGUSER,\n  password: process.env.PGPASSWORD,\n  max: 20,                      // maximum connections held open\n  idleTimeoutMillis: 30_000,    // release idle connections\n  connectionTimeoutMillis: 5_000, // fail fast rather than hanging\n});\n\n// Simple queries: the pool checks a connection out and back automatically\nconst { rows } = await pool.query(\n  'SELECT id, name FROM employees WHERE dept_id = $1',\n  [deptId],\n);" },
      { type: 'alert', value: 'Size the pool against the database, not against your traffic. PostgreSQL default max_connections is 100 and each connection costs real memory. Four application instances with max: 20 each already consumes 80 of them. For serverless or very high instance counts, put PgBouncer in front.' },
      { type: 'heading', value: 'Parameterised queries, always' },
      { type: 'diagram', name: 'sql-injection', caption: 'Parameters are not "escaping done well" — the query is planned before the value arrives, so input can never become code.' },
      { type: 'code', language: 'javascript', value: "// NEVER do this\nconst q = `SELECT * FROM users WHERE email = '${email}'`;\n\n// Always do this: $1, $2 are placeholders sent separately from the SQL\nconst { rows } = await pool.query(\n  'SELECT * FROM users WHERE email = $1 AND active = $2',\n  [email, true],\n);" },
      { type: 'warning', value: 'Placeholders work for values only, never for identifiers. You cannot write ORDER BY $1 to make the sort column dynamic. Validate a dynamic column name against an allow-list in your code, and never interpolate a client-supplied string into SQL.' },
      { type: 'code', language: 'javascript', value: "const SORTABLE = { name: 'name', salary: 'salary', hired: 'hired_on' };\nconst column = SORTABLE[req.query.sort] ?? 'id';   // allow-list, not interpolation\nconst dir = req.query.dir === 'desc' ? 'DESC' : 'ASC';\n\nconst { rows } = await pool.query(\n  `SELECT * FROM employees ORDER BY ${column} ${dir} LIMIT $1`,\n  [limit],\n);" },
      { type: 'heading', value: 'Transactions need a dedicated client' },
      { type: 'text', value: 'pool.query may use a different connection each time, and a transaction only exists on one connection. You must check a client out explicitly and use it for every statement in the transaction.' },
      { type: 'code', language: 'javascript', value: "export async function transfer(fromId, toId, amount) {\n  const client = await pool.connect();\n  try {\n    await client.query('BEGIN');\n\n    const { rows } = await client.query(\n      'UPDATE accounts SET balance = balance - $1 WHERE id = $2 AND balance >= $1 RETURNING balance',\n      [amount, fromId],\n    );\n    if (rows.length === 0) throw new Error('Insufficient funds');\n\n    await client.query(\n      'UPDATE accounts SET balance = balance + $1 WHERE id = $2',\n      [amount, toId],\n    );\n\n    await client.query('COMMIT');\n  } catch (err) {\n    await client.query('ROLLBACK');\n    throw err;\n  } finally {\n    client.release();     // never optional\n  }\n}" },
      { type: 'text', value: 'Note the WHERE balance >= $1 on the debit. The check and the update happen in one atomic statement, so two concurrent transfers cannot both pass a separate balance check and overdraw the account.' },
      { type: 'warning', value: 'A missing client.release() leaks a connection per failed request. The pool drains, every subsequent request waits for a connection that never returns, and the service appears to hang rather than error. Put the release in finally, without exception.' },
      { type: 'heading', value: 'Operational essentials' },
      { type: 'list', items: [
        'Read credentials from environment variables — never commit them.',
        'Require TLS in production: ssl: { rejectUnauthorized: true }.',
        'Set a statement_timeout so one runaway query cannot occupy a connection indefinitely.',
        'Handle pool.on("error") — a backend can drop an idle connection and crash the process if unhandled.',
        'Log slow queries with their parameters redacted.',
      ] },
    ],
    objectives: [
      'Configure a connection pool sensibly',
      'Write parameterised queries and handle dynamic identifiers safely',
      'Manage transactions on a dedicated client with guaranteed release',
    ],
    takeaways: [
      'Placeholders protect values, not identifiers — allow-list dynamic column names.',
      'A transaction lives on one connection; pool.query cannot guarantee that.',
      'client.release() in a finally block prevents the most common pool outage.',
    ],
  },

  'm15-l2': {
    title: 'ORM vs Raw SQL',
    content: [
      { type: 'text', value: 'An ORM maps database rows to objects in your language and generates SQL for you. The question is not whether ORMs are good — it is which parts of your application benefit from one.' },
      { type: 'compare', columns: [
        { title: 'ORM', tone: 'olive', subtitle: 'Prisma, TypeORM, Sequelize', items: [
          'Type-safe models and autocompletion',
          'Migrations and schema tooling included',
          'Parameterisation by default',
          'Fast for standard CRUD',
          'Opaque SQL — easy to generate something terrible by accident',
        ] },
        { title: 'Raw SQL', tone: 'honey', subtitle: 'pg, postgres.js, a thin query builder', items: [
          'Exactly the query you intended',
          'Full access to CTEs, window functions, engine features',
          'Predictable performance',
          'More boilerplate for simple reads',
          'You own the mapping and the migrations',
        ] },
      ] },
      { type: 'code', language: 'javascript', value: "// Prisma: schema-first, type-safe\nconst employees = await prisma.employee.findMany({\n  where:   { department: { city: 'Pune' }, salary: { gt: 70_000 } },\n  include: { department: true },\n  orderBy: { salary: 'desc' },\n  take: 10,\n});" },
      { type: 'code', language: 'sql', value: "-- The equivalent SQL. Reading both is the skill worth having.\nSELECT e.*, d.*\nFROM   employees e\nJOIN   departments d ON d.id = e.dept_id\nWHERE  d.city = 'Pune' AND e.salary > 70000\nORDER BY e.salary DESC\nLIMIT 10;" },
      { type: 'heading', value: 'Where ORMs go wrong' },
      { type: 'text', value: 'Two failure modes account for most ORM-related performance problems, and both are invisible until you look at the generated SQL.' },
      { type: 'code', language: 'javascript', value: "// 1. The N+1 problem: 1 query, then 100 more\nconst orders = await prisma.order.findMany();      // 1 query\nfor (const o of orders) {\n  const user = await prisma.user.findUnique({ where: { id: o.userId } });  // ×100\n}\n\n// Fixed with eager loading: one query\nconst orders = await prisma.order.findMany({ include: { user: true } });" },
      { type: 'code', language: 'javascript', value: "// 2. Over-fetching: pulling every column to use two\nconst users = await prisma.user.findMany();        // all columns, all rows\n\n// Fixed by selecting explicitly\nconst users = await prisma.user.findMany({\n  select: { id: true, email: true },\n});" },
      { type: 'alert', value: 'Turn on query logging in development. Prisma has log: ["query"], Sequelize has logging: console.log. Watching the SQL your ORM generates on every page load is the fastest way to catch both problems before they reach production.' },
      { type: 'heading', value: 'The escape hatch matters' },
      { type: 'text', value: 'Every good ORM lets you drop to raw SQL for the queries that need it. Reporting queries, window functions and recursive CTEs are usually far clearer written directly.' },
      { type: 'code', language: 'javascript', value: "// Prisma: still parameterised, via a tagged template\nconst rows = await prisma.$queryRaw`\n  SELECT d.name,\n         COUNT(e.id) AS headcount,\n         RANK() OVER (ORDER BY COUNT(e.id) DESC) AS rank\n  FROM   departments d\n  LEFT JOIN employees e ON e.dept_id = d.id\n  WHERE  d.city = ${city}\n  GROUP BY d.name\n`;" },
      { type: 'warning', value: 'Use $queryRaw with the tagged template, never $queryRawUnsafe with string concatenation. The tagged form parameterises interpolated values; the unsafe form is a SQL injection waiting to happen.' },
      { type: 'heading', value: 'A workable default' },
      { type: 'list', items: [
        'ORM for CRUD, migrations and the type-safe model layer — that is most of an application.',
        'Raw SQL for reporting, analytics, bulk operations and anything the ORM expresses awkwardly.',
        'Review the generated SQL for every query on a hot path.',
        'Learn SQL properly regardless: you cannot debug what an ORM produces if you cannot read it.',
      ] },
    ],
    objectives: [
      'Weigh ORM convenience against SQL control',
      'Detect and fix N+1 and over-fetching',
      'Drop to raw SQL safely when the ORM is the wrong tool',
    ],
    takeaways: [
      'An ORM does not remove the need to know SQL — it raises the cost of not knowing it.',
      'N+1 and over-fetching are invisible without query logging.',
      'Use the parameterised raw-query API, never the unsafe string version.',
    ],
  },

  'm15-l3': {
    title: 'Migrations and Seeders',
    content: [
      { type: 'text', value: 'A migration is a version-controlled, ordered schema change. It is how a schema travels from a laptop to staging to production without anyone applying statements by hand.' },
      { type: 'heading', value: 'Why not just run ALTER TABLE?' },
      { type: 'list', items: [
        'Reproducibility: a new developer runs one command and gets the exact production schema.',
        'Review: schema changes appear in pull requests alongside the code that needs them.',
        'Ordering: migrations apply in a defined sequence, and the tool records which have run.',
        'Deployment: the same command runs in CI, in staging and in production.',
      ] },
      { type: 'code', language: 'sql', value: "-- migrations/20240115_120000_add_employee_email.sql\n\n-- Up\nALTER TABLE employees ADD COLUMN email TEXT;\nCREATE UNIQUE INDEX CONCURRENTLY idx_employees_email ON employees (email);\n\n-- Down\nDROP INDEX IF EXISTS idx_employees_email;\nALTER TABLE employees DROP COLUMN IF EXISTS email;" },
      { type: 'heading', value: 'Writing migrations that do not cause an outage' },
      { type: 'text', value: 'On a table with millions of rows, an innocuous-looking statement can lock writes for minutes. These are the ones to be careful with.' },
      { type: 'table', headers: ['Operation', 'Risk', 'Safe approach'], rows: [
        ['ADD COLUMN with a volatile DEFAULT', 'Rewrites the whole table on older versions', 'Add nullable, backfill in batches, then set the default'],
        ['CREATE INDEX', 'Blocks writes for the duration', 'CREATE INDEX CONCURRENTLY, outside a transaction'],
        ['ALTER COLUMN TYPE', 'Full table rewrite with an exclusive lock', 'Add a new column, backfill, swap, drop the old one'],
        ['ADD NOT NULL', 'Full table scan holding a lock', 'Add a CHECK NOT VALID, VALIDATE it, then convert'],
        ['DROP COLUMN', 'Breaks any deployed code still selecting it', 'Deploy code that stops using it first, drop in a later release'],
      ] },
      { type: 'warning', value: 'CREATE INDEX CONCURRENTLY cannot run inside a transaction block. Most migration tools wrap each migration in a transaction by default, so this needs an explicit opt-out — and if it fails, it leaves an invalid index you must drop manually.' },
      { type: 'heading', value: 'The expand-and-contract pattern' },
      { type: 'text', value: 'The general technique for changing a schema without downtime: make the change additive, migrate in stages, and only remove the old shape once nothing references it.' },
      { type: 'steps', title: 'Renaming a column with zero downtime', steps: [
        { label: 'Expand', text: 'add the new column. Deploy code that writes to both columns and reads the old one.' },
        { label: 'Backfill', text: 'copy existing data across in batches, so no single statement holds a long lock.' },
        { label: 'Switch reads', text: 'deploy code that reads the new column. Both are still being written.' },
        { label: 'Stop dual writes', text: 'deploy code that only uses the new column.' },
        { label: 'Contract', text: 'drop the old column in a later migration, once no deployed version references it.' },
      ] },
      { type: 'alert', value: 'Every step is independently deployable and independently reversible. That is what makes it safe — at no point does a rollback of the application break against the database.' },
      { type: 'heading', value: 'Seeders' },
      { type: 'text', value: 'Seed data populates a database for development, testing or first boot. Keep two kinds separate: reference data the application needs to function, and sample data that exists only to make development pleasant.' },
      { type: 'code', language: 'sql', value: "-- Reference data: idempotent, safe to run in production\nINSERT INTO order_statuses (code, label) VALUES\n  ('pending','Pending'), ('paid','Paid'), ('shipped','Shipped')\nON CONFLICT (code) DO NOTHING;\n\n-- Development sample data: never runs in production\nINSERT INTO employees (name, dept_id, salary, hired_on)\nSELECT 'Employee ' || i,\n       (i % 3) + 1,\n       50000 + (i * 137) % 50000,\n       CURRENT_DATE - (i % 900)\nFROM   GENERATE_SERIES(1, 1000) AS i;" },
      { type: 'text', value: 'GENERATE_SERIES is worth knowing for this: a thousand realistic rows in one statement is far better for testing than five hand-written ones, and it lets you see which queries need indexes.' },
      { type: 'heading', value: 'Rules that keep a migration history healthy' },
      { type: 'list', items: [
        'Never edit a migration that has already run anywhere. Write a new one.',
        'Always write the down migration, and test it at least once.',
        'One logical change per migration — easier to review and to revert.',
        'Test against a copy of production-sized data, not an empty table.',
        'Take a backup before running anything destructive.',
      ] },
    ],
    objectives: [
      'Write reversible, reviewable migrations',
      'Avoid locking operations on large tables',
      'Apply expand-and-contract for zero-downtime changes',
    ],
    takeaways: [
      'Never edit an applied migration — history must match what actually ran.',
      'CREATE INDEX CONCURRENTLY cannot run inside a transaction block.',
      'Expand-and-contract keeps every intermediate state deployable and reversible.',
    ],
  },

  // ─────────────────────────── MODULE 16 ───────────────────────────
  'm16-p1': {
    title: 'Project 1 — Student Management Database',
    content: [
      { type: 'text', value: 'The first project applies Modules 2, 12 and 13: design a normalised schema from a description, then write the queries the application needs.' },
      { type: 'heading', value: 'Requirements' },
      { type: 'list', items: [
        'Students enrol in many courses; a course has many students.',
        'Each course is taught by one instructor; an instructor teaches many courses.',
        'Enrolments record the date and, once assessed, a grade.',
        'Courses belong to a department and carry a credit value.',
        'The system must report GPA per student and pass rate per course.',
      ] },
      { type: 'heading', value: 'Schema' },
      { type: 'code', language: 'sql', value: "CREATE TABLE departments (\n  id   INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  name TEXT NOT NULL UNIQUE\n);\n\nCREATE TABLE instructors (\n  id      INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  name    TEXT NOT NULL,\n  email   TEXT NOT NULL UNIQUE,\n  dept_id INT REFERENCES departments(id) ON DELETE SET NULL\n);\n\nCREATE TABLE students (\n  id         INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  name       TEXT NOT NULL,\n  email      TEXT NOT NULL UNIQUE,\n  enrolled_on DATE NOT NULL DEFAULT CURRENT_DATE\n);\n\nCREATE TABLE courses (\n  id            INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  code          TEXT NOT NULL UNIQUE,\n  title         TEXT NOT NULL,\n  credits       INT  NOT NULL CHECK (credits BETWEEN 1 AND 6),\n  dept_id       INT  NOT NULL REFERENCES departments(id),\n  instructor_id INT  REFERENCES instructors(id) ON DELETE SET NULL\n);\n\nCREATE TABLE enrollments (\n  student_id  INT NOT NULL REFERENCES students(id) ON DELETE CASCADE,\n  course_id   INT NOT NULL REFERENCES courses(id)  ON DELETE CASCADE,\n  enrolled_at DATE NOT NULL DEFAULT CURRENT_DATE,\n  grade       TEXT CHECK (grade IN ('A','B','C','D','F')),\n  PRIMARY KEY (student_id, course_id)\n);\n\nCREATE INDEX idx_enrollments_course ON enrollments (course_id);\nCREATE INDEX idx_courses_dept       ON courses (dept_id);\nCREATE INDEX idx_courses_instructor ON courses (instructor_id);" },
      { type: 'alert', value: 'grade is nullable on purpose: an enrolment exists before it is assessed. NULL here means "not yet graded", which is genuinely different from any grade including F.' },
      { type: 'heading', value: 'The queries the application needs' },
      { type: 'code', language: 'sql', value: "-- 1. A student's transcript\nSELECT c.code, c.title, c.credits, e.grade\nFROM   enrollments e\nJOIN   courses c ON c.id = e.course_id\nWHERE  e.student_id = $1\nORDER BY c.code;\n\n-- 2. GPA per student, ignoring ungraded enrolments\nSELECT s.name,\n       ROUND(SUM(CASE e.grade WHEN 'A' THEN 4 WHEN 'B' THEN 3\n                              WHEN 'C' THEN 2 WHEN 'D' THEN 1\n                              ELSE 0 END * c.credits)::NUMERIC\n             / NULLIF(SUM(c.credits), 0), 2) AS gpa\nFROM   students s\nJOIN   enrollments e ON e.student_id = s.id AND e.grade IS NOT NULL\nJOIN   courses c     ON c.id = e.course_id\nGROUP BY s.id, s.name\nORDER BY gpa DESC NULLS LAST;\n\n-- 3. Pass rate per course, including courses with no enrolments\nSELECT c.code, c.title,\n       COUNT(e.student_id)                              AS enrolled,\n       COUNT(*) FILTER (WHERE e.grade IS NOT NULL\n                          AND e.grade <> 'F')           AS passed,\n       ROUND(100.0 * COUNT(*) FILTER (WHERE e.grade IS NOT NULL AND e.grade <> 'F')\n             / NULLIF(COUNT(*) FILTER (WHERE e.grade IS NOT NULL), 0), 1) AS pass_pct\nFROM   courses c\nLEFT JOIN enrollments e ON e.course_id = c.id\nGROUP BY c.id, c.code, c.title\nORDER BY pass_pct DESC NULLS LAST;\n\n-- 4. Students who have not enrolled in anything (anti-join)\nSELECT s.name, s.email\nFROM   students s\nLEFT JOIN enrollments e ON e.student_id = s.id\nWHERE  e.student_id IS NULL;\n\n-- 5. Top two students per department by GPA (window function)\nWITH gpa AS (\n  SELECT d.name AS dept, s.name AS student,\n         AVG(CASE e.grade WHEN 'A' THEN 4 WHEN 'B' THEN 3\n                          WHEN 'C' THEN 2 WHEN 'D' THEN 1 ELSE 0 END) AS gpa\n  FROM   enrollments e\n  JOIN   students s    ON s.id = e.student_id\n  JOIN   courses c     ON c.id = e.course_id\n  JOIN   departments d ON d.id = c.dept_id\n  WHERE  e.grade IS NOT NULL\n  GROUP BY d.name, s.name\n)\nSELECT * FROM (\n  SELECT *, ROW_NUMBER() OVER (PARTITION BY dept ORDER BY gpa DESC) AS rn\n  FROM gpa\n) t WHERE rn <= 2;" },
      { type: 'heading', value: 'Build it yourself' },
      { type: 'steps', steps: [
        { label: 'Create the schema', text: 'run the DDL above and verify with \\d in psql.' },
        { label: 'Seed realistic volume', text: 'use GENERATE_SERIES to insert 500 students, 40 courses and 3,000 enrolments.' },
        { label: 'Run every query', text: 'confirm each returns what you expect, including the zero cases.' },
        { label: 'EXPLAIN ANALYZE the reports', text: 'find the sequential scans and decide which indexes are genuinely justified.' },
      ] },
    ],
    objectives: [
      'Design a normalised schema from written requirements',
      'Write transcript, GPA and pass-rate reporting queries',
      'Validate the design against realistic data volume',
    ],
    takeaways: [
      'Nullable grade encodes "not yet assessed" — a real state, not missing data.',
      'FILTER makes multi-metric aggregation readable in a single pass.',
      'Design is not finished until you have run the queries the application needs.',
    ],
  },

  'm16-p2': {
    title: 'Project 2 — E-Commerce Database',
    content: [
      { type: 'text', value: 'This project introduces the constraints that make commerce systems harder than they look: prices change but invoices must not, stock must never go negative, and orders must be atomic.' },
      { type: 'code', language: 'sql', value: "CREATE TABLE users (\n  id         INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  email      TEXT NOT NULL UNIQUE,\n  name       TEXT NOT NULL,\n  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n);\n\nCREATE TABLE addresses (\n  id      INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  line1   TEXT NOT NULL,\n  city    TEXT NOT NULL,\n  pincode TEXT NOT NULL,\n  is_default BOOLEAN NOT NULL DEFAULT FALSE\n);\n\nCREATE TABLE categories (\n  id        INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  name      TEXT NOT NULL UNIQUE,\n  parent_id INT REFERENCES categories(id)   -- self-reference: a tree\n);\n\nCREATE TABLE products (\n  id          INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  sku         TEXT NOT NULL UNIQUE,\n  name        TEXT NOT NULL,\n  price_cents BIGINT NOT NULL CHECK (price_cents >= 0),\n  stock       INT NOT NULL DEFAULT 0 CHECK (stock >= 0),\n  category_id INT REFERENCES categories(id)\n);\n\nCREATE TABLE orders (\n  id           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  user_id      INT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,\n  address_id   INT NOT NULL REFERENCES addresses(id) ON DELETE RESTRICT,\n  status       TEXT NOT NULL DEFAULT 'pending'\n               CHECK (status IN ('pending','paid','shipped','delivered','cancelled')),\n  total_cents  BIGINT NOT NULL DEFAULT 0 CHECK (total_cents >= 0),\n  placed_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()\n);\n\nCREATE TABLE order_items (\n  order_id    BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,\n  product_id  INT    NOT NULL REFERENCES products(id) ON DELETE RESTRICT,\n  quantity    INT    NOT NULL CHECK (quantity > 0),\n  unit_cents  BIGINT NOT NULL CHECK (unit_cents >= 0),   -- price at time of sale\n  PRIMARY KEY (order_id, product_id)\n);\n\nCREATE INDEX idx_orders_user    ON orders (user_id, placed_at DESC);\nCREATE INDEX idx_items_product  ON order_items (product_id);" },
      { type: 'heading', value: 'Three design decisions worth defending' },
      { type: 'list', items: [
        'unit_cents on order_items, not read from products. A price change must never alter a past invoice. This is the current-value versus recorded-fact distinction from Module 12.',
        'ON DELETE RESTRICT on orders.user_id and order_items.product_id. Financial history must survive the deletion of a user or a product.',
        'Money as BIGINT cents rather than NUMERIC. Both are correct; integers make arithmetic and equality comparisons unambiguous, which is why most payment systems use them.',
      ] },
      { type: 'heading', value: 'Placing an order — the transaction' },
      { type: 'code', language: 'sql', value: "BEGIN;\n\n  INSERT INTO orders (user_id, address_id, status)\n  VALUES ($1, $2, 'pending')\n  RETURNING id INTO v_order_id;\n\n  -- Decrement stock and fail if insufficient, in one atomic statement\n  UPDATE products\n  SET    stock = stock - $4\n  WHERE  id = $3 AND stock >= $4\n  RETURNING price_cents INTO v_price;\n\n  IF NOT FOUND THEN\n    RAISE EXCEPTION 'Insufficient stock for product %', $3;\n  END IF;\n\n  INSERT INTO order_items (order_id, product_id, quantity, unit_cents)\n  VALUES (v_order_id, $3, $4, v_price);\n\n  UPDATE orders\n  SET    total_cents = (SELECT SUM(quantity * unit_cents)\n                        FROM order_items WHERE order_id = v_order_id)\n  WHERE  id = v_order_id;\n\nCOMMIT;" },
      { type: 'alert', value: 'The stock decrement and its check are a single UPDATE with WHERE stock >= quantity. Reading the stock, checking it in application code, then updating would let two concurrent orders both pass the check and drive stock negative. The CHECK (stock >= 0) constraint is the second line of defence.' },
      { type: 'heading', value: 'Reporting queries' },
      { type: 'code', language: 'sql', value: "-- Monthly revenue with month-over-month growth\nWITH monthly AS (\n  SELECT DATE_TRUNC('month', placed_at) AS month,\n         SUM(total_cents) / 100.0       AS revenue\n  FROM   orders WHERE status <> 'cancelled'\n  GROUP BY 1\n)\nSELECT month, revenue,\n       LAG(revenue) OVER (ORDER BY month) AS prev,\n       ROUND((revenue - LAG(revenue) OVER (ORDER BY month)) * 100.0\n             / NULLIF(LAG(revenue) OVER (ORDER BY month), 0), 1) AS growth_pct\nFROM   monthly ORDER BY month;\n\n-- Top 10 products by revenue\nSELECT p.name,\n       SUM(oi.quantity)                        AS units,\n       SUM(oi.quantity * oi.unit_cents) / 100.0 AS revenue\nFROM   order_items oi\nJOIN   products p ON p.id = oi.product_id\nJOIN   orders   o ON o.id = oi.order_id AND o.status <> 'cancelled'\nGROUP BY p.id, p.name\nORDER BY revenue DESC\nLIMIT 10;\n\n-- Customers who have never ordered\nSELECT u.email FROM users u\nLEFT JOIN orders o ON o.user_id = u.id\nWHERE  o.id IS NULL;\n\n-- Full category tree with depth (recursive CTE)\nWITH RECURSIVE tree AS (\n  SELECT id, name, parent_id, 1 AS depth, name::TEXT AS path\n  FROM   categories WHERE parent_id IS NULL\n  UNION ALL\n  SELECT c.id, c.name, c.parent_id, t.depth + 1, t.path || ' > ' || c.name\n  FROM   categories c JOIN tree t ON t.id = c.parent_id\n)\nSELECT REPEAT('  ', depth - 1) || name AS category, depth FROM tree ORDER BY path;" },
      { type: 'warning', value: 'is_default on addresses is not properly constrained by this schema — nothing stops a user having three default addresses. Fixing it is a good exercise: a partial unique index, CREATE UNIQUE INDEX ON addresses (user_id) WHERE is_default, enforces exactly one.' },
    ],
    objectives: [
      'Model a commerce schema with historical price integrity',
      'Place an order atomically without overselling stock',
      'Write revenue, ranking and hierarchy reports',
    ],
    takeaways: [
      'Invoice lines record the price at the time of sale, not the current price.',
      'Check-and-update in one statement is the only safe way to decrement stock.',
      'A partial unique index enforces "exactly one default per user".',
    ],
  },

  'm16-p3': {
    title: 'Project 3 — Learning Management System',
    content: [
      { type: 'text', value: 'The most involved project: a course platform tracking content, progress and assessment. It combines every module — hierarchical content, per-user progress, quiz scoring and analytics.' },
      { type: 'code', language: 'sql', value: "CREATE TABLE users (\n  id    INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  email TEXT NOT NULL UNIQUE,\n  name  TEXT NOT NULL,\n  role  TEXT NOT NULL DEFAULT 'student'\n        CHECK (role IN ('student','instructor','admin'))\n);\n\nCREATE TABLE courses (\n  id            INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  slug          TEXT NOT NULL UNIQUE,\n  title         TEXT NOT NULL,\n  instructor_id INT REFERENCES users(id) ON DELETE SET NULL,\n  published_at  TIMESTAMPTZ\n);\n\nCREATE TABLE modules (\n  id        INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  course_id INT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,\n  title     TEXT NOT NULL,\n  position  INT NOT NULL,\n  UNIQUE (course_id, position)\n);\n\nCREATE TABLE lessons (\n  id         INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  module_id  INT NOT NULL REFERENCES modules(id) ON DELETE CASCADE,\n  title      TEXT NOT NULL,\n  position   INT NOT NULL,\n  kind       TEXT NOT NULL DEFAULT 'lesson'\n             CHECK (kind IN ('lesson','quiz','assignment')),\n  UNIQUE (module_id, position)\n);\n\nCREATE TABLE enrollments (\n  user_id     INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  course_id   INT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,\n  enrolled_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n  PRIMARY KEY (user_id, course_id)\n);\n\nCREATE TABLE lesson_progress (\n  user_id      INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  lesson_id    INT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,\n  completed_at TIMESTAMPTZ,\n  seconds_spent INT NOT NULL DEFAULT 0 CHECK (seconds_spent >= 0),\n  PRIMARY KEY (user_id, lesson_id)\n);\n\nCREATE TABLE quiz_attempts (\n  id           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  user_id      INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  lesson_id    INT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,\n  score        INT NOT NULL CHECK (score BETWEEN 0 AND 100),\n  attempted_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n);\n\nCREATE INDEX idx_progress_user   ON lesson_progress (user_id);\nCREATE INDEX idx_attempts_lesson ON quiz_attempts (lesson_id, user_id);" },
      { type: 'alert', value: 'UNIQUE (course_id, position) enforces that no two modules claim the same slot. Ordering data is easy to get wrong; letting the database hold the rule means the UI cannot corrupt it.' },
      { type: 'heading', value: 'The queries a learning platform actually runs' },
      { type: 'code', language: 'sql', value: "-- 1. Course progress percentage for one user\nSELECT c.title,\n       COUNT(l.id)                                          AS total_lessons,\n       COUNT(lp.completed_at)                               AS completed,\n       ROUND(100.0 * COUNT(lp.completed_at)\n             / NULLIF(COUNT(l.id), 0), 1)                   AS pct\nFROM   courses c\nJOIN   modules m  ON m.course_id = c.id\nJOIN   lessons l  ON l.module_id = m.id\nLEFT JOIN lesson_progress lp\n       ON lp.lesson_id = l.id AND lp.user_id = $1\nWHERE  c.id = $2\nGROUP BY c.id, c.title;\n\n-- 2. The next lesson to resume\nSELECT l.id, l.title, m.title AS module\nFROM   lessons l\nJOIN   modules m ON m.id = l.module_id\nLEFT JOIN lesson_progress lp\n       ON lp.lesson_id = l.id AND lp.user_id = $1\nWHERE  m.course_id = $2 AND lp.completed_at IS NULL\nORDER BY m.position, l.position\nLIMIT 1;\n\n-- 3. Best score per quiz (window function over attempts)\nSELECT DISTINCT ON (lesson_id)\n       lesson_id, score, attempted_at\nFROM   quiz_attempts\nWHERE  user_id = $1\nORDER BY lesson_id, score DESC, attempted_at DESC;\n\n-- 4. Where do learners drop off? (funnel by lesson position)\nSELECT m.position AS module_pos, l.position AS lesson_pos, l.title,\n       COUNT(lp.user_id) FILTER (WHERE lp.completed_at IS NOT NULL) AS finished\nFROM   lessons l\nJOIN   modules m ON m.id = l.module_id\nLEFT JOIN lesson_progress lp ON lp.lesson_id = l.id\nWHERE  m.course_id = $1\nGROUP BY m.position, l.position, l.title\nORDER BY m.position, l.position;\n\n-- 5. Cohort retention: learners still active 30 days after enrolling\nSELECT DATE_TRUNC('week', e.enrolled_at)::DATE AS cohort,\n       COUNT(DISTINCT e.user_id)                AS enrolled,\n       COUNT(DISTINCT lp.user_id) FILTER (\n         WHERE lp.completed_at >= e.enrolled_at + INTERVAL '30 days'\n       )                                        AS active_at_30d\nFROM   enrollments e\nLEFT JOIN lesson_progress lp ON lp.user_id = e.user_id\nGROUP BY cohort\nORDER BY cohort;" },
      { type: 'text', value: 'Query 4 is the one worth studying. A drop-off funnel is how a real platform finds the lesson where learners give up — and it is nothing more than a LEFT JOIN with a FILTERed count, ordered by position.' },
      { type: 'alert', value: 'DISTINCT ON in query 3 is PostgreSQL-specific and extremely useful: it returns the first row per group according to the ORDER BY. The portable equivalent is ROW_NUMBER() in a CTE filtered to rn = 1.' },
      { type: 'heading', value: 'Extend it' },
      { type: 'list', items: [
        'Add certificates issued when progress reaches 100%, with a verification code.',
        'Add discussion threads per lesson, using a self-referencing parent_id for replies.',
        'Add a materialised view for the instructor dashboard, refreshed nightly.',
        'Add a partial index on lesson_progress WHERE completed_at IS NULL to speed up the resume query.',
      ] },
    ],
    objectives: [
      'Model hierarchical content with enforced ordering',
      'Track per-user progress and compute completion',
      'Write funnel and cohort retention analytics',
    ],
    takeaways: [
      'UNIQUE (parent, position) is how you stop ordering data from corrupting.',
      'A drop-off funnel is a LEFT JOIN plus a filtered count, ordered by position.',
      'DISTINCT ON gives you the best row per group in one clause.',
    ],
  },

  // ─────────────────────────── MODULE 17 ───────────────────────────
  'm17-l1': {
    title: 'Interview Prep — Fundamentals',
    content: [
      { type: 'text', value: 'Fundamentals questions test whether you understand mechanisms or have memorised definitions. For each answer below, the second sentence is what separates the two.' },
      { type: 'heading', value: 'Definitions with the reason attached' },
      { type: 'table', headers: ['Question', 'A strong answer'], rows: [
        ['What is a primary key?', 'A column or set of columns uniquely identifying each row, never NULL. It should also be immutable, because every foreign key referencing it depends on it not changing'],
        ['DELETE vs TRUNCATE vs DROP', 'DELETE removes selected rows and can be filtered and rolled back per row; TRUNCATE empties the table quickly with no WHERE; DROP removes the table itself'],
        ['WHERE vs HAVING', 'WHERE filters rows before grouping, HAVING filters groups after. That is why WHERE cannot reference an aggregate — it does not exist yet at that stage'],
        ['CHAR vs VARCHAR', 'CHAR pads to a fixed length, VARCHAR does not. In PostgreSQL VARCHAR and TEXT perform identically, so VARCHAR(n) is only for genuine business limits'],
        ['What is an index?', 'A sorted structure making lookups logarithmic instead of linear. The cost is slower writes and extra storage, so index deliberately'],
        ['What is a view?', 'A stored query treated as a table. It holds no data and makes nothing faster — it exists for abstraction and access control'],
      ] },
      { type: 'heading', value: 'The NULL questions, which come up constantly' },
      { type: 'code', language: 'sql', value: "-- Why does this return nothing?\nSELECT * FROM employees WHERE dept_id = NULL;\n-- NULL means unknown; = NULL evaluates to UNKNOWN, and only TRUE keeps a row.\n\n-- What is the difference?\nCOUNT(*)        -- counts rows\nCOUNT(dept_id)  -- counts non-NULL values\n\n-- Why does this return zero rows if the subquery contains a NULL?\nWHERE id NOT IN (SELECT dept_id FROM employees);\n-- id <> NULL is UNKNOWN for every id, so the condition is never TRUE.\n-- Use NOT EXISTS instead." },
      { type: 'heading', value: 'Question types to expect' },
      { type: 'list', items: [
        'Write a query — usually joins plus aggregation. Talk through your reasoning as you write it.',
        'Explain a concept — always attach the mechanism and the trade-off, not just the definition.',
        'Debug a query — the answer is very often a NULL, a missing GROUP BY column, or a WHERE that should have been in ON.',
        'Design a schema — start by asking clarifying questions before drawing anything.',
      ] },
      { type: 'alert', value: 'When asked to write a query, say your plan out loud first: "I will start from orders, join users to get the name, filter to this year, then group by user." Interviewers are assessing how you decompose the problem at least as much as your syntax.' },
      { type: 'heading', value: 'Practice set' },
      { type: 'code', language: 'sql', value: "-- 1. Second highest salary\n-- 2. Duplicate emails in a users table\n-- 3. Employees earning more than their department average\n-- 4. Departments with no employees\n-- 5. Running total of daily sales\n-- 6. Customers who ordered in January but not February\n-- 7. Nth row of a table without OFFSET\n-- 8. Delete duplicates keeping the lowest id" },
      { type: 'code', language: 'sql', value: "-- 2. Duplicate emails\nSELECT email, COUNT(*) FROM users GROUP BY email HAVING COUNT(*) > 1;\n\n-- 6. Ordered in January but not February\nSELECT DISTINCT u.id, u.email\nFROM   users u\nJOIN   orders j ON j.user_id = u.id\n                AND j.placed_at >= '2024-01-01' AND j.placed_at < '2024-02-01'\nWHERE  NOT EXISTS (\n  SELECT 1 FROM orders f\n  WHERE  f.user_id = u.id\n    AND  f.placed_at >= '2024-02-01' AND f.placed_at < '2024-03-01'\n);\n\n-- 8. Delete duplicates, keeping the lowest id\nDELETE FROM users a\nUSING  users b\nWHERE  a.email = b.email AND a.id > b.id;" },
    ],
    objectives: [
      'Answer definition questions with mechanism and trade-off',
      'Explain the NULL behaviours interviewers probe for',
      'Structure a query answer by narrating your plan first',
    ],
    takeaways: [
      'Definition plus mechanism plus trade-off is what separates a strong answer from a memorised one.',
      'Most SQL debugging questions have NULL, GROUP BY or ON/WHERE placement as the answer.',
      'Narrating your approach is assessed as heavily as the final query.',
    ],
  },

  'm17-l2': {
    title: 'Interview Prep — Joins and Aggregation',
    content: [
      { type: 'text', value: 'This is the largest category of SQL interview questions, and almost all of them are variations on a handful of patterns. Learn the patterns and the questions stop being individually memorable.' },
      { type: 'heading', value: 'Pattern 1 — the anti-join' },
      { type: 'code', language: 'sql', value: "-- Customers with no orders / products never sold / users who never logged in\nSELECT u.name\nFROM   users u\nLEFT JOIN orders o ON o.user_id = u.id\nWHERE  o.id IS NULL;\n\n-- Equivalent, and safer against NULLs\nSELECT u.name FROM users u\nWHERE  NOT EXISTS (SELECT 1 FROM orders o WHERE o.user_id = u.id);" },
      { type: 'heading', value: 'Pattern 2 — aggregate including the zeros' },
      { type: 'code', language: 'sql', value: "-- Every department, including those with nobody in them\nSELECT d.name, COUNT(e.id) AS headcount\nFROM   departments d\nLEFT JOIN employees e ON e.dept_id = d.id\nGROUP BY d.name;" },
      { type: 'warning', value: 'COUNT(e.id), never COUNT(*). With a LEFT JOIN, an unmatched department still produces one NULL-padded row, so COUNT(*) reports 1 instead of 0. Interviewers watch for exactly this.' },
      { type: 'heading', value: 'Pattern 3 — compare a row to its group' },
      { type: 'code', language: 'sql', value: "-- Employees earning more than their department average\n\n-- With a correlated subquery\nSELECT e.name, e.salary\nFROM   employees e\nWHERE  e.salary > (SELECT AVG(salary) FROM employees x WHERE x.dept_id = e.dept_id);\n\n-- With a window function — usually the better answer\nSELECT name, salary FROM (\n  SELECT name, salary, AVG(salary) OVER (PARTITION BY dept_id) AS dept_avg\n  FROM   employees\n) t WHERE salary > dept_avg;" },
      { type: 'heading', value: 'Pattern 4 — top N per group' },
      { type: 'code', language: 'sql', value: "WITH ranked AS (\n  SELECT name, dept_id, salary,\n         ROW_NUMBER() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS rn\n  FROM   employees\n)\nSELECT name, dept_id, salary FROM ranked WHERE rn <= 3;" },
      { type: 'alert', value: 'Ask which ranking function they want. ROW_NUMBER breaks ties arbitrarily, RANK skips numbers after a tie, DENSE_RANK does not. "Should tied salaries both count as first place?" is a question that demonstrates real understanding.' },
      { type: 'heading', value: 'Pattern 5 — pivoting with conditional aggregation' },
      { type: 'code', language: 'sql', value: "-- Turn rows into columns without a PIVOT clause\nSELECT DATE_TRUNC('month', placed_at)::DATE AS month,\n       COUNT(*) FILTER (WHERE status = 'paid')      AS paid,\n       COUNT(*) FILTER (WHERE status = 'shipped')   AS shipped,\n       COUNT(*) FILTER (WHERE status = 'cancelled') AS cancelled\nFROM   orders\nGROUP BY 1 ORDER BY 1;" },
      { type: 'heading', value: 'Pattern 6 — consecutive days / gaps and islands' },
      { type: 'code', language: 'sql', value: "-- Users active three or more days in a row.\n-- Trick: date minus row_number is constant within a consecutive run.\nWITH marked AS (\n  SELECT user_id, active_on,\n         active_on - (ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY active_on))::INT AS grp\n  FROM   (SELECT DISTINCT user_id, active_on FROM activity) d\n)\nSELECT user_id, MIN(active_on) AS streak_start, COUNT(*) AS streak_days\nFROM   marked\nGROUP BY user_id, grp\nHAVING COUNT(*) >= 3;" },
      { type: 'heading', value: 'The duplicate-rows question' },
      { type: 'code', language: 'sql', value: "-- Find duplicates\nSELECT email, COUNT(*) FROM users GROUP BY email HAVING COUNT(*) > 1;\n\n-- Delete duplicates keeping the earliest row\nDELETE FROM users a USING users b\nWHERE  a.email = b.email AND a.id > b.id;\n\n-- Same thing with a window function, which generalises better\nDELETE FROM users WHERE id IN (\n  SELECT id FROM (\n    SELECT id, ROW_NUMBER() OVER (PARTITION BY email ORDER BY id) AS rn\n    FROM users\n  ) t WHERE rn > 1\n);" },
      { type: 'alert', value: 'A join can multiply rows. If an aggregate looks too high, check whether a one-to-many join duplicated the rows before aggregation. Aggregating in a CTE first, then joining, is the usual fix.' },
    ],
    objectives: [
      'Recognise the six recurring join and aggregation patterns',
      'Choose between correlated subqueries and window functions',
      'Handle duplicates, pivots and consecutive-day problems',
    ],
    takeaways: [
      'With a LEFT JOIN, count a column from the joined side, never *.',
      'Top-N-per-group is ROW_NUMBER in a CTE — memorise the shape.',
      'Inflated aggregates usually mean a join multiplied rows before the aggregation.',
    ],
  },

  'm17-l3': {
    title: 'Interview Prep — Optimisation and Indexing',
    content: [
      { type: 'text', value: 'Senior interviews move from "write this query" to "this query is slow, what do you do?". The answer is always a process, never a guess.' },
      { type: 'steps', title: 'The answer to "how would you optimise this?"', steps: [
        { label: 'Measure', text: 'EXPLAIN ANALYZE first. Never optimise from intuition — say this out loud, it is half the answer.' },
        { label: 'Find the cost', text: 'locate the node with the highest actual time × loops, not the highest estimate.' },
        { label: 'Check the estimates', text: 'a large gap between estimated and actual rows means stale statistics. Run ANALYZE.' },
        { label: 'Look for missing indexes', text: 'a Seq Scan on a large table with most rows removed by a filter.' },
        { label: 'Check for index-defeating predicates', text: 'a function wrapping the column, a leading wildcard, an implicit type cast.' },
        { label: 'Reduce rows early', text: 'filter before joining, aggregate before joining where possible.' },
        { label: 'Verify', text: 're-run EXPLAIN ANALYZE and confirm the plan actually changed.' },
      ] },
      { type: 'heading', value: 'Questions you will be asked directly' },
      { type: 'table', headers: ['Question', 'What they are checking'], rows: [
        ['When is an index a bad idea?', 'Small tables, low-selectivity columns, write-heavy tables. Every index taxes every write'],
        ['Why is my index not being used?', 'Function on the column, leading wildcard, type mismatch, or the table is small enough that a scan is genuinely cheaper'],
        ['Composite index on (a,b,c) — which queries benefit?', 'Anything filtering on a leading prefix. Filtering on b alone cannot use it'],
        ['SELECT * vs naming columns', 'More I/O, prevents index-only scans, and breaks when the schema changes'],
        ['Why is OFFSET 100000 slow?', 'The engine generates and discards 100,000 rows. Keyset pagination stays constant'],
        ['How do you find slow queries in production?', 'pg_stat_statements ordered by total time, not average'],
      ] },
      { type: 'heading', value: 'Rewrites worth knowing by heart' },
      { type: 'code', language: 'sql', value: "-- Function on the column defeats the index\nWHERE DATE(created_at) = '2024-01-15'\n-- becomes\nWHERE created_at >= '2024-01-15' AND created_at < '2024-01-16'\n\n-- Leading wildcard forces a scan\nWHERE name LIKE '%smith%'\n-- becomes a trigram index, or full-text search\nCREATE EXTENSION pg_trgm;\nCREATE INDEX idx_name_trgm ON users USING GIN (name gin_trgm_ops);\n\n-- Deep OFFSET degrades linearly\nORDER BY id LIMIT 20 OFFSET 100000\n-- becomes keyset pagination, constant time at any depth\nWHERE id > :last_seen_id ORDER BY id LIMIT 20\n\n-- NOT IN breaks on NULL and optimises poorly\nWHERE id NOT IN (SELECT user_id FROM banned)\n-- becomes\nWHERE NOT EXISTS (SELECT 1 FROM banned b WHERE b.user_id = users.id)" },
      { type: 'heading', value: 'Scaling questions' },
      { type: 'table', headers: ['Technique', 'What it solves'], rows: [
        ['Read replicas', 'Read-heavy load — writes go to the primary, reads spread across replicas'],
        ['Partitioning', 'Very large tables — split by date or key so queries touch one partition'],
        ['Connection pooling (PgBouncer)', 'Too many application instances for max_connections'],
        ['Caching (Redis)', 'Repeated identical reads that tolerate slight staleness'],
        ['Materialised views', 'Expensive aggregations read far more often than they change'],
        ['Sharding', 'Write volume beyond one machine — the last resort, it complicates everything'],
      ] },
      { type: 'alert', value: 'If asked "how would you scale this?", work up the list in order of cost. Indexes and query fixes first, then caching and replicas, and sharding only when you can explain why nothing simpler works. Reaching for sharding immediately is a red flag.' },
    ],
    objectives: [
      'Present a systematic optimisation process',
      'Explain why an index is unused and rewrite the query',
      'Order scaling techniques by cost and complexity',
    ],
    takeaways: [
      'Always answer optimisation questions with "measure first" — it is the substance, not a formality.',
      'Function-wrapped columns, leading wildcards and type mismatches are the three usual index killers.',
      'Escalate scaling techniques from cheapest to most complex; sharding is last.',
    ],
  },

  'm17-l4': {
    title: 'Interview Prep — Company-Level Practice',
    content: [
      { type: 'text', value: 'Longer problems combining several concepts, of the kind used in take-home tests and onsite rounds. Attempt each before reading the solution.' },
      { type: 'heading', value: 'Problem 1 — Second highest salary per department' },
      { type: 'code', language: 'sql', value: "WITH ranked AS (\n  SELECT dept_id, name, salary,\n         DENSE_RANK() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS rnk\n  FROM   employees\n)\nSELECT dept_id, name, salary FROM ranked WHERE rnk = 2;" },
      { type: 'text', value: 'DENSE_RANK rather than ROW_NUMBER, because two people on the top salary should both be first — making the next distinct salary second, not third.' },
      { type: 'heading', value: 'Problem 2 — Month-over-month revenue growth' },
      { type: 'code', language: 'sql', value: "WITH monthly AS (\n  SELECT DATE_TRUNC('month', placed_at) AS month, SUM(total) AS revenue\n  FROM   orders WHERE status = 'paid'\n  GROUP BY 1\n)\nSELECT month, revenue,\n       LAG(revenue) OVER (ORDER BY month) AS prev,\n       ROUND((revenue - LAG(revenue) OVER (ORDER BY month)) * 100.0\n             / NULLIF(LAG(revenue) OVER (ORDER BY month), 0), 1) AS growth_pct\nFROM   monthly ORDER BY month;" },
      { type: 'heading', value: 'Problem 3 — Median salary' },
      { type: 'code', language: 'sql', value: "-- SQL has no MEDIAN function; this is the standard approach\nSELECT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY salary) AS median\nFROM   employees;\n\n-- Per department\nSELECT dept_id,\n       PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY salary) AS median\nFROM   employees GROUP BY dept_id;" },
      { type: 'heading', value: 'Problem 4 — Retention cohorts' },
      { type: 'code', language: 'sql', value: "WITH cohorts AS (\n  SELECT user_id, DATE_TRUNC('month', MIN(placed_at)) AS cohort_month\n  FROM   orders GROUP BY user_id\n),\nactivity AS (\n  SELECT c.cohort_month,\n         DATE_TRUNC('month', o.placed_at) AS active_month,\n         COUNT(DISTINCT o.user_id)        AS users\n  FROM   orders o JOIN cohorts c ON c.user_id = o.user_id\n  GROUP BY 1, 2\n)\nSELECT cohort_month,\n       EXTRACT(MONTH FROM AGE(active_month, cohort_month))::INT AS month_number,\n       users\nFROM   activity\nORDER BY cohort_month, month_number;" },
      { type: 'heading', value: 'Problem 5 — Sessionisation' },
      { type: 'code', language: 'sql', value: "-- Group events into sessions: a gap over 30 minutes starts a new one\nWITH gaps AS (\n  SELECT user_id, event_at,\n         CASE WHEN event_at - LAG(event_at) OVER (PARTITION BY user_id ORDER BY event_at)\n                   > INTERVAL '30 minutes'\n              THEN 1 ELSE 0 END AS is_new_session\n  FROM   events\n),\nsessions AS (\n  SELECT user_id, event_at,\n         SUM(is_new_session) OVER (PARTITION BY user_id ORDER BY event_at) AS session_id\n  FROM   gaps\n)\nSELECT user_id, session_id,\n       MIN(event_at) AS started, MAX(event_at) AS ended,\n       COUNT(*)      AS events\nFROM   sessions\nGROUP BY user_id, session_id\nORDER BY user_id, started;" },
      { type: 'text', value: 'The running SUM over a 0/1 flag is the key idea. It increments only when a new session starts, so it becomes an identifier shared by every event in the same session. The same trick solves most gaps-and-islands problems.' },
      { type: 'heading', value: 'Design round: "design a schema for X"' },
      { type: 'steps', title: 'How to run the conversation', steps: [
        { label: 'Clarify first', text: 'ask about scale, the access patterns, and what must be consistent. Designing before asking is the most common mistake.' },
        { label: 'Name the entities', text: 'say them out loud and confirm before drawing.' },
        { label: 'Establish cardinality', text: 'check each relationship in both directions.' },
        { label: 'Write the DDL', text: 'with real types and constraints, not just column names.' },
        { label: 'Validate against queries', text: 'walk through the three or four questions the application must answer.' },
        { label: 'Discuss scale last', text: 'indexes, then denormalisation, then partitioning — and say why each is needed.' },
      ] },
      { type: 'alert', value: 'The strongest signal you can give in a design round is stating your trade-offs. "I would store the price on the order line rather than joining to products, because an invoice must not change when the catalogue does" tells an interviewer more than a perfect diagram.' },
    ],
    objectives: [
      'Solve multi-concept problems combining windows, CTEs and aggregation',
      'Apply the running-sum trick to sessionisation and gaps-and-islands',
      'Structure a schema design conversation',
    ],
    takeaways: [
      'A running SUM over a 0/1 flag generates group identifiers — the core gaps-and-islands technique.',
      'PERCENTILE_CONT is how you compute a median in SQL.',
      'In design rounds, clarify before designing and state trade-offs explicitly.',
    ],
  },

  // ─────────────────────── ASSESSMENT & CERTIFICATION ───────────────────────
  'test-theory': {
    title: 'Theory Test',
    content: [
      { type: 'text', value: 'A written assessment covering the conceptual half of the course. Sixty minutes, no reference material.' },
      { type: 'heading', value: 'Coverage' },
      { type: 'table', headers: ['Area', 'Weight', 'Drawn from'], rows: [
        ['Relational model, keys and constraints', '20%', 'Modules 1–2'],
        ['SQL command families and clause semantics', '15%', 'Modules 3–5'],
        ['Joins, aggregation and subqueries', '25%', 'Modules 6–8'],
        ['Transactions, ACID, isolation and locking', '20%', 'Module 10'],
        ['Normalisation and schema design', '20%', 'Modules 12–13'],
      ] },
      { type: 'heading', value: 'The kind of question to expect' },
      { type: 'list', items: [
        'Explain why WHERE cannot reference an aggregate, in terms of execution order.',
        'A query returns fewer rows after adding a WHERE clause to a LEFT JOIN. Explain why, and fix it.',
        'Given a table, identify which normal form it violates and give the corrected schema.',
        'Two transactions deadlock. Describe the mechanism and two ways to prevent it.',
        'Explain when a composite index on (a, b) will not help a query.',
      ] },
      { type: 'alert', value: 'Answers are marked on mechanism, not vocabulary. "HAVING filters after grouping" earns partial credit; "HAVING filters after grouping, which is why it can see aggregates and WHERE cannot" earns full marks.' },
      { type: 'heading', value: 'How to revise' },
      { type: 'steps', steps: [
        { label: 'Key takeaways', text: 'reread the takeaway cards at the foot of every lesson — they are the examinable core.' },
        { label: 'Redo the quizzes', text: 'any question you get wrong points at a lesson to reread.' },
        { label: 'Explain aloud', text: 'pick five concepts and explain each without notes. Where you stall is where to revise.' },
        { label: 'Focus on the traps', text: 'NULL semantics, ON versus WHERE, execution order, and index-defeating predicates account for most lost marks.' },
      ] },
    ],
    objectives: ['Consolidate the conceptual material', 'Explain mechanisms rather than recite definitions', 'Identify weak areas before the practical test'],
    takeaways: ['Marks come from explaining why, not what.', 'NULL, join semantics and execution order are the highest-yield revision topics.', 'Explaining a concept aloud exposes gaps that rereading hides.'],
  },

  'test-practical': {
    title: 'Practical Query Test',
    content: [
      { type: 'text', value: 'A hands-on assessment against a seeded database. Ninety minutes, documentation permitted — this tests whether you can construct queries, not whether you memorised syntax.' },
      { type: 'heading', value: 'The tasks' },
      { type: 'list', items: [
        'Basic retrieval with filtering, sorting and pagination.',
        'Multi-table joins including at least one outer join with correct NULL handling.',
        'Aggregation with GROUP BY and HAVING across three tables.',
        'A subquery or CTE solving a problem a single flat query cannot.',
        'A window function: ranking, running total, or top-N per group.',
        'A data modification wrapped in a transaction, with correct rollback on failure.',
        'Read an EXPLAIN plan and propose a specific index.',
      ] },
      { type: 'heading', value: 'How answers are marked' },
      { type: 'table', headers: ['Criterion', 'Weight'], rows: [
        ['Correctness — the query returns exactly the right rows', '50%'],
        ['Edge cases — NULLs, empty groups, ties, boundaries', '20%'],
        ['Efficiency — no needless subqueries, cross joins or full scans', '20%'],
        ['Readability — aliases, formatting, sensible naming', '10%'],
      ] },
      { type: 'alert', value: 'Edge cases are twenty percent for a reason. A query that is right for the sample data and wrong when a department is empty or a value is NULL is the exact failure this test is designed to catch.' },
      { type: 'heading', value: 'Approach' },
      { type: 'steps', steps: [
        { label: 'Read the schema first', text: 'spend five minutes on \\d for every table. Knowing which columns are nullable prevents most mistakes.' },
        { label: 'Build incrementally', text: 'start with SELECT * FROM one table, add one join, check the row count, add the next.' },
        { label: 'Watch the row count', text: 'if it jumps after a join, that join is multiplying rows. Find out why before continuing.' },
        { label: 'Test the empty case', text: 'does your query still behave when a group has zero members?' },
        { label: 'Format before submitting', text: 'aligned keywords and clear aliases cost thirty seconds and are worth ten percent.' },
      ] },
    ],
    objectives: ['Write correct queries against an unfamiliar schema', 'Handle NULLs, ties and empty groups', 'Build complex queries incrementally'],
    takeaways: ['Read the schema before writing a single query.', 'A jump in row count after a join means duplication — investigate immediately.', 'Edge cases carry as much weight as the happy path.'],
  },

  'test-design': {
    title: 'Schema Design Evaluation',
    content: [
      { type: 'text', value: 'You are given a plain-English description of a system and asked to produce a schema, justify it, and identify its weaknesses. This is the assessment closest to real work.' },
      { type: 'heading', value: 'What you submit' },
      { type: 'list', items: [
        'An ER diagram with every relationship and its cardinality.',
        'Complete DDL — types, constraints, defaults, and delete behaviours.',
        'The indexes you would create, each with a one-line justification.',
        'Five queries the application would run, written against your schema.',
        'A short note on any deliberate denormalisation and how it stays in sync.',
      ] },
      { type: 'heading', value: 'Marking criteria' },
      { type: 'table', headers: ['Criterion', 'What earns marks'], rows: [
        ['Completeness', 'Every stated requirement is representable'],
        ['Normalisation', '3NF, or a stated and defended reason for departing from it'],
        ['Integrity', 'Constraints enforce the rules rather than relying on application code'],
        ['Delete semantics', 'Every foreign key has a deliberate ON DELETE behaviour'],
        ['Indexing', 'Justified by the queries, not scattered defensively'],
        ['Queryability', 'The five queries are natural to write against the design'],
        ['Trade-offs', 'Weaknesses identified and discussed, not hidden'],
      ] },
      { type: 'alert', value: 'The last criterion is where strong candidates separate themselves. Writing "I chose to store the aggregate count on posts to avoid counting on every page load; it needs a trigger to stay accurate" shows judgement. A design presented as flawless shows less.' },
      { type: 'heading', value: 'Common mistakes' },
      { type: 'list', items: [
        'No primary key on a junction table, allowing duplicate pairs.',
        'ON DELETE CASCADE on financial or audit tables.',
        'Money stored as FLOAT.',
        'TIMESTAMP without timezone for events.',
        'Comma-separated values in a column instead of a related table.',
        'Missing indexes on foreign keys.',
        'Current prices read from the product table on historical invoices.',
      ] },
    ],
    objectives: ['Produce a complete, defensible schema from requirements', 'Justify indexes against real queries', 'Identify and discuss your own trade-offs'],
    takeaways: ['Every foreign key needs a deliberate delete behaviour.', 'Indexes are justified by queries, never added defensively.', 'Naming your design weaknesses is a strength, not an admission.'],
  },

  'test-viva': {
    title: 'Viva / Interview Round',
    content: [
      { type: 'text', value: 'A thirty-minute spoken assessment. It tests whether you can explain your reasoning — the skill that actually gets used in code review and design discussion.' },
      { type: 'heading', value: 'Structure' },
      { type: 'steps', steps: [
        { label: 'Concepts (10 min)', text: 'explain five concepts in your own words, with follow-up questions probing the mechanism.' },
        { label: 'Whiteboard query (10 min)', text: 'write a query aloud while narrating your reasoning.' },
        { label: 'Design discussion (10 min)', text: 'defend your schema submission and respond to a change in requirements.' },
      ] },
      { type: 'heading', value: 'Questions that will come up' },
      { type: 'list', items: [
        'Explain a JOIN to someone who has never used a database.',
        'You have a slow query. Walk me through what you do.',
        'When would you not normalise?',
        'What happens, mechanically, when I run COMMIT?',
        'Why does this LEFT JOIN return fewer rows than the left table?',
        'Talk me through a database problem you have actually debugged.',
      ] },
      { type: 'heading', value: 'How to do well' },
      { type: 'compare', columns: [
        { title: 'Strong answers', tone: 'olive', items: [
          'Start with the mechanism, then the consequence',
          'Use a concrete example — rows, not abstractions',
          'State trade-offs unprompted',
          'Say "I am not certain, but I would expect…" and reason it through',
          'Ask a clarifying question before designing',
        ] },
        { title: 'Weak answers', tone: 'rose', items: [
          'Reciting a definition with no mechanism',
          'Staying abstract when an example would settle it',
          'Presenting one option as the only option',
          'Guessing confidently rather than reasoning aloud',
          'Designing before understanding the requirement',
        ] },
      ] },
      { type: 'alert', value: 'Being asked "are you sure?" is not a signal that you are wrong. It is usually a test of whether you can re-derive your answer. Walk through the reasoning again rather than immediately reversing.' },
    ],
    objectives: ['Explain database concepts clearly aloud', 'Narrate query construction while writing', 'Defend design decisions and adapt to new requirements'],
    takeaways: ['Mechanism first, consequence second — that order makes an explanation land.', 'Concrete rows beat abstract description every time.', 'Reasoning aloud under challenge is more valuable than never being wrong.'],
  },

  'cert-view': {
    title: 'SQL Mastery Certificate',
    content: [
      { type: 'text', value: 'The certificate is issued once every module quiz, both assignments, all four assessment components and the capstone project are complete.' },
      { type: 'heading', value: 'Requirements' },
      { type: 'table', headers: ['Component', 'Requirement'], rows: [
        ['Module quizzes (17)', 'Each passed at 70% or above'],
        ['Module assignments', 'All submitted and reviewed'],
        ['Theory test', '70% or above'],
        ['Practical query test', '70% or above'],
        ['Schema design evaluation', 'Complete submission, passed'],
        ['Viva round', 'Passed'],
        ['Capstone project', 'Submitted and reviewed'],
      ] },
      { type: 'heading', value: 'What the certificate records' },
      { type: 'list', items: [
        'Your name and a unique verification code.',
        'Issue date and the course version completed.',
        'The verified skills listed on the next page.',
        'A public verification URL an employer can check.',
      ] },
      { type: 'alert', value: 'A certificate is evidence, not a substitute for a portfolio. Push the capstone schema and its queries to a public repository with a README explaining your design decisions — that repository will do more in an interview than the certificate will.' },
    ],
    objectives: ['Understand the certification requirements', 'Track completion across all components'],
    takeaways: ['Every component must be passed independently.', 'A public capstone repository carries more weight than the certificate alone.'],
  },

  'cert-skills': {
    title: 'Verified Skills',
    content: [
      { type: 'text', value: 'The competencies the certificate attests to, phrased the way they appear in job descriptions.' },
      { type: 'heading', value: 'Querying' },
      { type: 'list', items: [
        'Retrieval with filtering, sorting, pagination and correct NULL handling',
        'All join types, with deliberate ON versus WHERE placement',
        'Aggregation with GROUP BY, HAVING and conditional aggregation',
        'Subqueries, CTEs and recursive CTEs',
        'Window functions for ranking, running totals and top-N-per-group',
      ] },
      { type: 'heading', value: 'Design' },
      { type: 'list', items: [
        'Normalisation to 3NF, with justified denormalisation',
        'One-to-one, one-to-many and many-to-many modelling',
        'Type selection, constraints and referential integrity',
        'ER diagramming and requirements-to-schema translation',
      ] },
      { type: 'heading', value: 'Operations' },
      { type: 'list', items: [
        'Transactions, isolation levels and savepoints',
        'Lock behaviour, deadlock prevention and retry strategy',
        'Index design, EXPLAIN ANALYZE interpretation and query tuning',
        'Views and materialised views',
      ] },
      { type: 'heading', value: 'Backend integration' },
      { type: 'list', items: [
        'Connection pooling and parameterised queries',
        'ORM usage with awareness of N+1 and over-fetching',
        'Versioned migrations and zero-downtime schema change',
        'SQL injection prevention',
      ] },
      { type: 'alert', value: 'Choose three or four of these for a CV rather than listing all of them, and pick the ones you can demonstrate from your capstone. "Designed a normalised e-commerce schema and tuned its reporting queries with EXPLAIN ANALYZE" is stronger than a list.' },
    ],
    objectives: ['Review the full skill set covered', 'Select the competencies to present on a CV'],
    takeaways: ['Skills are worth more when tied to something you built.', 'Three demonstrable skills beat twenty listed ones.'],
  },

  'capstone-project': {
    title: 'Capstone — Learning Platform Database',
    content: [
      { type: 'text', value: 'Design and build the complete database for a platform combining course delivery with coding practice — a system with the content model of Udemy and the judging model of HackerRank. This is the project that exercises every module.' },
      { type: 'heading', value: 'Requirements' },
      { type: 'compare', columns: [
        { title: 'Course delivery', tone: 'olive', items: [
          'Courses contain ordered modules; modules contain ordered lessons',
          'Instructors author courses; students enrol in them',
          'Per-lesson progress and time spent are tracked',
          'Quizzes with multiple attempts, best score retained',
          'Certificates issued on completion, with verification codes',
        ] },
        { title: 'Coding practice', tone: 'honey', items: [
          'Problems with difficulty, tags and test cases',
          'Submissions in several languages with a verdict per test case',
          'Contests running for a fixed window with a leaderboard',
          'User rating updated after each contest',
          'Streaks and daily solve counts',
        ] },
      ] },
      { type: 'heading', value: 'Deliverables' },
      { type: 'steps', steps: [
        { label: 'ER diagram', text: 'every entity and relationship with cardinality marked.' },
        { label: 'Schema DDL', text: 'full types, constraints, defaults and delete behaviours. Normalised to 3NF, with any denormalisation explained.' },
        { label: 'Seed data', text: 'realistic volume via GENERATE_SERIES — at least 1,000 users, 50 courses and 50,000 submissions, so performance work is meaningful.' },
        { label: 'Twenty queries', text: 'the list below. Each must be correct on edge cases, not only on the happy path.' },
        { label: 'Index plan', text: 'each index justified by a specific query, with EXPLAIN ANALYZE before and after.' },
        { label: 'Transaction logic', text: 'submission judging and contest scoring implemented atomically.' },
        { label: 'README', text: 'your design decisions, trade-offs and known weaknesses.' },
      ] },
      { type: 'heading', value: 'The twenty queries' },
      { type: 'code', language: 'text', value: "Progress and content\n 1. Course completion percentage per enrolled user\n 2. The next uncompleted lesson for a user (resume)\n 3. Course catalogue with enrolment counts, including courses with none\n 4. Learners who enrolled but never started a lesson\n 5. Drop-off funnel by lesson position\n\nAssessment\n 6. Best quiz score per user per lesson\n 7. Quiz questions with the lowest correct-answer rate\n 8. Users eligible for a certificate (100% progress, all quizzes passed)\n 9. Average attempts before passing, per quiz\n10. Grade distribution per course\n\nCoding practice\n11. Acceptance rate per problem\n12. A user's solved problems by difficulty\n13. Problems attempted but never solved, per user\n14. First-accepted submission per user per problem\n15. Current solve streak per user (gaps and islands)\n\nContests and analytics\n16. Contest leaderboard with tie-breaking on submission time\n17. Rating change per user after a contest\n18. Weekly active learners with week-over-week growth\n19. Retention cohorts by enrolment month\n20. Top 3 courses per category by completion rate" },
      { type: 'heading', value: 'Which module each query exercises' },
      { type: 'table', headers: ['Queries', 'Modules exercised'], rows: [
        ['1–5', 'Joins, outer joins, aggregation with zeros (6, 7)'],
        ['6–10', 'Subqueries, DISTINCT ON, conditional aggregation (6, 8)'],
        ['11–15', 'Window functions, gaps and islands (14)'],
        ['16–20', 'CTEs, ranking, cohort analysis (14, 17)'],
      ] },
      { type: 'alert', value: 'Query 15 — the solve streak — is the hardest. It is a gaps-and-islands problem: subtract a row number from the date and consecutive days share a constant value, which you then group by. Module 17 covers the technique.' },
      { type: 'heading', value: 'How it is assessed' },
      { type: 'table', headers: ['Criterion', 'Weight'], rows: [
        ['Schema correctness and normalisation', '25%'],
        ['Constraints and integrity enforcement', '15%'],
        ['Query correctness, including edge cases', '30%'],
        ['Index design with measured justification', '15%'],
        ['Transaction handling', '10%'],
        ['Documentation and stated trade-offs', '5%'],
      ] },
      { type: 'warning', value: 'Seed realistic volume before writing the index plan. Every query is instant on fifty rows, so an index plan built against a small dataset demonstrates nothing. Fifty thousand submissions is where the sequential scans start to show.' },
    ],
    objectives: [
      'Design a production-grade schema spanning two related domains',
      'Write twenty correct queries covering the full course',
      'Justify every index with measured EXPLAIN ANALYZE evidence',
    ],
    takeaways: [
      'Realistic data volume is what makes performance work meaningful.',
      'The twenty queries are deliberately chosen to exercise every module.',
      'A README explaining your trade-offs is part of the deliverable, not an extra.',
    ],
  },
};
