import { LessonMap, EMPLOYEES } from './types';

/** Module 3 (DDL/DML/DQL) + Module 4 (filtering) + Module 5 (functions). */
export const commandLessons: LessonMap = {
  // ─────────────────────────── MODULE 3 ───────────────────────────
  'm3-l1': {
    title: 'DDL — CREATE, ALTER, DROP',
    content: [
      { type: 'text', value: 'SQL statements fall into families. Knowing which family a keyword belongs to tells you immediately what it affects, whether it can be rolled back, and how dangerous it is.' },
      { type: 'diagram', name: 'sql-command-families', caption: 'Every keyword in this course belongs to one of these five families.' },
      { type: 'text', value: 'DDL — Data Definition Language — changes the shape of the database: which tables exist and what columns they have. It never touches the values inside rows, except when removing a column takes its data with it.' },
      { type: 'heading', value: 'CREATE TABLE' },
      { type: 'code', language: 'sql', value: "CREATE TABLE departments (\n  id    INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  name  TEXT NOT NULL UNIQUE,\n  city  TEXT NOT NULL\n);\n\nCREATE TABLE employees (\n  id        INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  name      TEXT NOT NULL,\n  dept_id   INT REFERENCES departments(id) ON DELETE SET NULL,\n  salary    NUMERIC(10,2) NOT NULL CHECK (salary > 0),\n  hired_on  DATE NOT NULL DEFAULT CURRENT_DATE\n);" },
      { type: 'alert', value: 'Order matters: departments must exist before employees can reference it. When writing a schema file, define parent tables before child tables.' },
      { type: 'text', value: 'CREATE TABLE IF NOT EXISTS makes a script safe to re-run, which is useful in setup scripts — though real projects should use migrations (Module 15) rather than re-runnable scripts.' },
      { type: 'heading', value: 'ALTER TABLE' },
      { type: 'code', language: 'sql', value: "-- Add a column (existing rows get NULL, or the default)\nALTER TABLE employees ADD COLUMN email TEXT;\n\n-- Add a column that must always have a value\nALTER TABLE employees ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;\n\n-- Rename\nALTER TABLE employees RENAME COLUMN name TO full_name;\n\n-- Change a type (only if every existing value can convert)\nALTER TABLE employees ALTER COLUMN salary TYPE NUMERIC(12,2);\n\n-- Add a constraint after the fact\nALTER TABLE employees ADD CONSTRAINT email_unique UNIQUE (email);\n\n-- Remove a column — this deletes its data permanently\nALTER TABLE employees DROP COLUMN email;" },
      { type: 'warning', value: 'Adding a NOT NULL column with no DEFAULT to a table that already has rows fails immediately: the existing rows would violate it. Either supply a DEFAULT, or add the column nullable, backfill it, then add the NOT NULL.' },
      { type: 'heading', value: 'Removing things — and the three that look alike' },
      { type: 'compare', columns: [
        { title: 'DROP TABLE', tone: 'rose', subtitle: 'DDL', items: [
          'Removes the table and all its data',
          'The table no longer exists',
          'Indexes and constraints go with it',
          'Reversible only inside a transaction',
        ] },
        { title: 'TRUNCATE', tone: 'honey', subtitle: 'DDL', items: [
          'Removes every row instantly',
          'The empty table remains',
          'Cannot use WHERE — it is all or nothing',
          'Far faster than DELETE on large tables',
        ] },
        { title: 'DELETE', tone: 'olive', subtitle: 'DML', items: [
          'Removes the rows you select',
          'Accepts a WHERE clause',
          'Logged row by row, fires triggers',
          'Slower, but precise and reversible',
        ] },
      ] },
      { type: 'code', language: 'sql', value: "DROP TABLE employees;              -- table gone\nTRUNCATE TABLE employees;          -- table empty, structure intact\nDELETE FROM employees WHERE id = 5;  -- one row gone\n\n-- Safe variants\nDROP TABLE IF EXISTS employees;\nDROP TABLE departments CASCADE;    -- also drops dependent objects" },
      { type: 'alert', value: 'PostgreSQL is unusual and wonderful here: DDL is transactional. You can BEGIN, run five ALTER TABLE statements, discover a mistake, and ROLLBACK the whole migration. MySQL cannot do this — each DDL statement commits implicitly.' },
    ],
    objectives: [
      'Create tables with the right column definitions and ordering',
      'Alter an existing table safely, including the NOT NULL backfill pattern',
      'Distinguish DROP, TRUNCATE and DELETE',
    ],
    takeaways: [
      'DDL changes structure; DML changes rows. The distinction predicts the risk.',
      'Adding a NOT NULL column to a populated table needs a DEFAULT or a three-step backfill.',
      'In PostgreSQL, wrapping a migration in a transaction makes a failed migration a non-event.',
    ],
  },

  'm3-l2': {
    title: 'DML — INSERT, UPDATE, DELETE',
    content: [
      { type: 'text', value: 'DML changes the rows inside tables. These are the statements that will one day cause you real trouble, so this lesson spends as much time on how to run them safely as on their syntax.' },
      { type: 'heading', value: 'INSERT' },
      { type: 'code', language: 'sql', value: "-- Always name your columns. Positional inserts break the moment\n-- somebody adds a column in the middle.\nINSERT INTO departments (name, city)\nVALUES ('Engineering', 'Pune');\n\n-- Many rows in one statement: one round trip instead of four\nINSERT INTO employees (name, dept_id, salary, hired_on) VALUES\n  ('Ana Iyer', 1, 92000, '2021-03-14'),\n  ('Bo Chen',  1, 78000, '2022-07-01'),\n  ('Cy Das',   2, 64000, '2020-11-23'),\n  ('Dia Rao',  2, 64000, '2023-01-09');\n\n-- Get the generated id back without a second query\nINSERT INTO departments (name, city)\nVALUES ('Legal', 'Delhi')\nRETURNING id, name;" },
      { type: 'alert', value: 'RETURNING is a PostgreSQL feature worth remembering. It turns "insert then select the id" into a single atomic statement, which is both faster and free of race conditions.' },
      { type: 'heading', value: 'UPSERT — insert, or update if it already exists' },
      { type: 'code', language: 'sql', value: "INSERT INTO employees (id, name, salary)\nVALUES (1, 'Ana Iyer', 96000)\nON CONFLICT (id) DO UPDATE\n  SET salary = EXCLUDED.salary;\n\n-- Or quietly skip duplicates instead of erroring\nINSERT INTO departments (name, city)\nVALUES ('Engineering', 'Pune')\nON CONFLICT (name) DO NOTHING;" },
      { type: 'heading', value: 'UPDATE' },
      { type: 'code', language: 'sql', value: "-- Raise one person's salary\nUPDATE employees\nSET    salary = 96000\nWHERE  id = 1;\n\n-- Several columns at once, computed from the current value\nUPDATE employees\nSET    salary   = salary * 1.10,\n       hired_on = hired_on\nWHERE  dept_id = 1;\n\n-- Confirm what you changed\nUPDATE employees SET salary = salary * 1.10\nWHERE  dept_id = 1\nRETURNING id, name, salary;" },
      { type: 'warning', value: 'An UPDATE with no WHERE updates every row in the table. There is no confirmation prompt and no undo outside a transaction. This is the single most common way people damage a production database.' },
      { type: 'heading', value: 'The habit that prevents that' },
      { type: 'steps', title: 'Run every destructive statement in this order', steps: [
        { label: 'SELECT first', text: 'run SELECT * FROM employees WHERE dept_id = 1; and look at exactly which rows come back.' },
        { label: 'BEGIN', text: 'open a transaction so nothing is final yet.' },
        { label: 'Run it', text: 'execute the UPDATE or DELETE and read the reported row count.' },
        { label: 'Verify', text: 'if the count is not what you predicted, ROLLBACK. Only COMMIT when it matches.' },
      ] },
      { type: 'code', language: 'sql', value: "BEGIN;\n\nUPDATE employees SET salary = salary * 1.10 WHERE dept_id = 1;\n-- psql reports: UPDATE 2\n-- Expected 2? Good.\n\nCOMMIT;   -- or ROLLBACK; if the number surprised you" },
      { type: 'heading', value: 'DELETE' },
      { type: 'code', language: 'sql', value: "DELETE FROM employees WHERE id = 5;\n\nDELETE FROM employees WHERE hired_on < '2021-01-01';\n\n-- Delete based on another table\nDELETE FROM employees\nWHERE  dept_id IN (SELECT id FROM departments WHERE city = 'Delhi');\n\nDELETE FROM employees;    -- every row. Use TRUNCATE if that is genuinely the intent." },
      { type: 'alert', value: 'Many production systems never physically delete. Instead they set a deleted_at timestamp — a soft delete — so the row can be restored and audit history survives. Views or WHERE deleted_at IS NULL then hide them from normal queries.' },
    ],
    objectives: [
      'Insert single and multiple rows, and retrieve generated keys with RETURNING',
      'Write UPSERT statements with ON CONFLICT',
      'Run destructive statements safely using SELECT-then-transaction',
    ],
    takeaways: [
      'Always name columns in an INSERT; positional inserts break on the next migration.',
      'An UPDATE or DELETE without WHERE touches every row, silently.',
      'SELECT it, wrap it in BEGIN, check the row count, then COMMIT.',
    ],
  },

  'm3-l3': {
    title: 'DQL — SELECT, WHERE, ORDER BY, LIMIT',
    content: [
      { type: 'text', value: 'SELECT is the statement you will write more than all the others combined. It has exactly one job — return a set of rows — and a handful of clauses that shape what that set contains.' },
      { type: 'syntax', title: 'The full shape of a SELECT', parts: [
        { clause: 'SELECT', text: 'which columns (or computed expressions) appear in the output.' },
        { clause: 'FROM', text: 'which table the rows come from.' },
        { clause: 'JOIN', text: 'which other tables to attach, and on what condition (Module 7).' },
        { clause: 'WHERE', text: 'which individual rows to keep.' },
        { clause: 'GROUP BY', text: 'how to collapse rows into groups (Module 6).' },
        { clause: 'HAVING', text: 'which groups to keep.' },
        { clause: 'ORDER BY', text: 'the order to return them in.' },
        { clause: 'LIMIT / OFFSET', text: 'how many to return, and where to start.' },
      ] },
      { type: 'heading', value: 'Write order is not execution order' },
      { type: 'text', value: 'This is the idea that makes half of SQL suddenly make sense. You write SELECT first, but the engine evaluates it almost last — which is why you cannot use a column alias defined in SELECT inside your WHERE clause.' },
      { type: 'diagram', name: 'sql-execution-order', caption: 'FROM builds the row set, WHERE filters it, and only then does SELECT decide which columns to show.' },
      { type: 'code', language: 'sql', value: "-- Fails: annual_pay does not exist yet when WHERE runs\nSELECT name, salary * 12 AS annual_pay\nFROM   employees\nWHERE  annual_pay > 800000;    -- ERROR: column \"annual_pay\" does not exist\n\n-- Works: repeat the expression, or wrap the query\nSELECT name, salary * 12 AS annual_pay\nFROM   employees\nWHERE  salary * 12 > 800000;\n\n-- ORDER BY, however, runs after SELECT — so the alias is fine there\nSELECT name, salary * 12 AS annual_pay\nFROM   employees\nORDER BY annual_pay DESC;" },
      { type: 'heading', value: 'Working against real rows' },
      { type: 'dataset', name: 'employees', ...EMPLOYEES },
      { type: 'queryResult', query: "SELECT name, salary\nFROM   employees\nWHERE  salary > 65000\nORDER BY salary DESC;", headers: ['name', 'salary'], rows: [['Ana Iyer', '92000'], ['Bo Chen', '78000']], note: 'Three rows were filtered out by WHERE before ORDER BY ever saw them.' },
      { type: 'heading', value: 'DISTINCT' },
      { type: 'queryResult', query: 'SELECT DISTINCT salary FROM employees ORDER BY salary;', headers: ['salary'], rows: [['51000'], ['64000'], ['78000'], ['92000']], note: 'Cy and Dia both earn 64000, so it appears once. DISTINCT applies to the whole selected row, not just the first column.' },
      { type: 'heading', value: 'ORDER BY details worth knowing' },
      { type: 'code', language: 'sql', value: "-- Multiple keys: sort by department, then by salary within it\nSELECT name, dept_id, salary\nFROM   employees\nORDER BY dept_id ASC, salary DESC;\n\n-- Where NULLs land is a choice, not luck\nORDER BY dept_id ASC NULLS FIRST;\nORDER BY dept_id ASC NULLS LAST;   -- PostgreSQL default for ASC" },
      { type: 'heading', value: 'LIMIT and OFFSET — and their trap' },
      { type: 'code', language: 'sql', value: "SELECT * FROM employees ORDER BY id LIMIT 10;             -- page 1\nSELECT * FROM employees ORDER BY id LIMIT 10 OFFSET 10;   -- page 2\nSELECT * FROM employees ORDER BY id LIMIT 10 OFFSET 20;   -- page 3" },
      { type: 'warning', value: 'A LIMIT with no ORDER BY returns an arbitrary ten rows — and the engine is free to return a different ten next time. Pagination without a deterministic ORDER BY will duplicate and skip rows, and the bug only appears under load.' },
      { type: 'alert', value: 'OFFSET 100000 still makes the database generate and discard 100,000 rows. For deep pagination, use keyset pagination instead: WHERE id > :last_seen_id ORDER BY id LIMIT 10. It stays fast at any depth.' },
    ],
    objectives: [
      'Compose a SELECT with all its clauses in the right order',
      'Explain why aliases work in ORDER BY but not in WHERE',
      'Paginate correctly, and know when OFFSET stops scaling',
    ],
    takeaways: [
      'Written order and execution order differ; SELECT is evaluated near the end.',
      'LIMIT without ORDER BY returns an arbitrary subset, not a stable one.',
      'Deep OFFSET pagination degrades linearly — keyset pagination does not.',
    ],
  },

  // ─────────────────────────── MODULE 4 ───────────────────────────
  'm4-l1': {
    title: 'Comparison Operators',
    content: [
      { type: 'text', value: 'Every WHERE clause is a boolean expression evaluated once per row. If it comes out TRUE, the row is kept; FALSE or UNKNOWN, and it is discarded. That third outcome is where NULL keeps reappearing.' },
      { type: 'table', headers: ['Operator', 'Meaning', 'Example'], rows: [
        ['=', 'Equal to', "status = 'active'"],
        ['<> or !=', 'Not equal to', "status <> 'archived'"],
        ['>  <  >=  <=', 'Ordering comparisons', 'salary >= 70000'],
        ['BETWEEN a AND b', 'Inclusive range', 'salary BETWEEN 60000 AND 80000'],
        ['IS NULL / IS NOT NULL', 'The only valid NULL tests', 'dept_id IS NULL'],
        ['IS DISTINCT FROM', 'Like <>, but treats NULL as comparable', 'dept_id IS DISTINCT FROM 1'],
      ] },
      { type: 'dataset', name: 'employees', ...EMPLOYEES },
      { type: 'queryResult', query: 'SELECT name, salary FROM employees WHERE salary >= 64000;', headers: ['name', 'salary'], rows: [['Ana Iyer', '92000'], ['Bo Chen', '78000'], ['Cy Das', '64000'], ['Dia Rao', '64000']], note: '>= includes the boundary. Eli, at 51000, is the only row excluded.' },
      { type: 'heading', value: 'BETWEEN is inclusive on both ends' },
      { type: 'queryResult', query: 'SELECT name, salary\nFROM   employees\nWHERE  salary BETWEEN 64000 AND 78000;', headers: ['name', 'salary'], rows: [['Bo Chen', '78000'], ['Cy Das', '64000'], ['Dia Rao', '64000']], note: 'Identical to salary >= 64000 AND salary <= 78000. Both endpoints are included.' },
      { type: 'warning', value: 'BETWEEN on timestamps is a classic bug. BETWEEN \'2024-01-01\' AND \'2024-01-31\' silently excludes almost all of the 31st, because the bare date means midnight. Use >= \'2024-01-01\' AND < \'2024-02-01\' for date ranges — the half-open interval is always correct.' },
      { type: 'heading', value: 'IS DISTINCT FROM: the NULL-safe comparison' },
      { type: 'text', value: 'Recall from Module 2 that dept_id <> 1 drops the row whose department is unknown. IS DISTINCT FROM treats NULL as a comparable value, so it does what you usually meant.' },
      { type: 'queryResult', query: 'SELECT name, dept_id FROM employees WHERE dept_id <> 1;', headers: ['name', 'dept_id'], rows: [['Cy Das', '2'], ['Dia Rao', '2']], note: 'Eli is silently excluded — the comparison with NULL was UNKNOWN.' },
      { type: 'queryResult', query: 'SELECT name, dept_id FROM employees WHERE dept_id IS DISTINCT FROM 1;', headers: ['name', 'dept_id'], rows: [['Cy Das', '2'], ['Dia Rao', '2'], ['Eli Roy', '']], note: 'Eli is included: an unknown department is certainly distinct from department 1.' },
      { type: 'heading', value: 'Comparing text and dates' },
      { type: 'code', language: 'sql', value: "-- Text comparison is case-sensitive in PostgreSQL\nWHERE name = 'ana iyer'      -- no match for 'Ana Iyer'\nWHERE LOWER(name) = 'ana iyer'  -- matches, but cannot use a plain index\n\n-- Dates and timestamps compare naturally\nWHERE hired_on >= '2022-01-01'\nWHERE hired_on < CURRENT_DATE - INTERVAL '1 year'" },
      { type: 'alert', value: 'Wrapping a column in a function — LOWER(name), DATE(created_at) — prevents the planner from using an ordinary index on that column. Module 9 shows the fix: an expression index, or restructuring the comparison so the column stays bare.' },
    ],
    objectives: [
      'Use every comparison operator, including the NULL-safe one',
      'Write correct date-range filters with half-open intervals',
      'Recognise when a function on a column disables an index',
    ],
    takeaways: [
      'A row is kept only when the condition is definitely TRUE.',
      'Half-open ranges (>= start AND < next_start) are the only reliable date filter.',
      'IS DISTINCT FROM is <> that behaves sensibly around NULL.',
    ],
  },

  'm4-l2': {
    title: 'Logical Operators',
    content: [
      { type: 'text', value: 'AND, OR and NOT combine conditions. They behave the way you would expect until NULL enters, at which point SQL switches to three-valued logic and a few results become genuinely surprising.' },
      { type: 'heading', value: 'Precedence: AND binds tighter than OR' },
      { type: 'text', value: 'This is the cause of more wrong result sets than any other single rule. Read the two queries below carefully — they are not the same.' },
      { type: 'code', language: 'sql', value: "-- What you probably meant: engineers or salespeople, who earn a lot\nWHERE (dept_id = 1 OR dept_id = 2) AND salary > 70000\n\n-- What SQL reads if you omit the brackets:\n-- everyone in dept 1, plus anyone at all in dept 2 earning over 70000\nWHERE dept_id = 1 OR dept_id = 2 AND salary > 70000" },
      { type: 'queryResult', query: 'SELECT name, dept_id, salary FROM employees\nWHERE  dept_id = 1 OR dept_id = 2 AND salary > 70000;', headers: ['name', 'dept_id', 'salary'], rows: [['Ana Iyer', '1', '92000'], ['Bo Chen', '1', '78000']], note: 'Both Engineering rows are returned regardless of salary, because AND was evaluated first. The salary filter only ever applied to department 2.' },
      { type: 'queryResult', query: 'SELECT name, dept_id, salary FROM employees\nWHERE  (dept_id = 1 OR dept_id = 2) AND salary > 70000;', headers: ['name', 'dept_id', 'salary'], rows: [['Ana Iyer', '1', '92000'], ['Bo Chen', '1', '78000']], note: 'Here the same two rows are correct — but for the right reason. Change Cy\'s salary to 80000 and only this version would include them.' },
      { type: 'alert', value: 'Use brackets whenever AND and OR appear in the same WHERE clause, even when you are sure of the precedence. The next person to read the query should not have to be sure.' },
      { type: 'heading', value: 'Three-valued logic' },
      { type: 'table', headers: ['A', 'B', 'A AND B', 'A OR B'], rows: [
        ['TRUE', 'TRUE', 'TRUE', 'TRUE'],
        ['TRUE', 'FALSE', 'FALSE', 'TRUE'],
        ['TRUE', 'NULL', 'NULL', 'TRUE'],
        ['FALSE', 'NULL', 'FALSE', 'NULL'],
        ['NULL', 'NULL', 'NULL', 'NULL'],
      ] },
      { type: 'text', value: 'Two rows in that table are worth memorising. TRUE OR NULL is TRUE — because it is true regardless of what the unknown turns out to be. FALSE AND NULL is FALSE, for the same reason. SQL resolves the unknown whenever the answer cannot depend on it.' },
      { type: 'heading', value: 'NOT and the NULL trap' },
      { type: 'code', language: 'sql', value: "-- If dept_id is NULL, the inner test is UNKNOWN,\n-- and NOT UNKNOWN is still UNKNOWN. The row is dropped either way.\nWHERE NOT (dept_id = 1)\n\n-- Say what you mean instead\nWHERE dept_id <> 1 OR dept_id IS NULL" },
      { type: 'warning', value: 'NOT IN with a subquery that can return NULL returns zero rows — always. WHERE id NOT IN (1, 2, NULL) is never TRUE for any id, because the comparison against NULL is UNKNOWN. Use NOT EXISTS instead (Module 8), which does not have this failure mode.' },
      { type: 'heading', value: 'Short-circuiting is not guaranteed' },
      { type: 'text', value: 'Unlike most programming languages, SQL does not promise to evaluate AND left to right. The planner may reorder conditions to run the cheapest or most selective one first. Never rely on an earlier condition to protect a later one from an error.' },
      { type: 'code', language: 'sql', value: "-- Unsafe: the planner may run the cast before the type check\nWHERE data_type = 'int' AND value::INT > 10\n\n-- Safe: CASE forces the evaluation order\nWHERE CASE WHEN data_type = 'int' THEN value::INT > 10 ELSE FALSE END" },
    ],
    objectives: [
      'Combine conditions with correct AND/OR precedence',
      'Reason about three-valued logic with NULL',
      'Avoid the NOT IN NULL trap',
    ],
    takeaways: [
      'AND binds tighter than OR — bracket every mixed condition.',
      'TRUE OR NULL is TRUE; FALSE AND NULL is FALSE. The unknown only matters when it could change the answer.',
      'NOT IN with any NULL in the list returns nothing at all.',
    ],
  },

  'm4-l3': {
    title: 'Advanced Filtering — IN, LIKE, and pattern matching',
    content: [
      { type: 'heading', value: 'IN — membership in a set' },
      { type: 'code', language: 'sql', value: "-- These two are identical; IN is simply easier to read\nWHERE dept_id IN (1, 2)\nWHERE dept_id = 1 OR dept_id = 2\n\n-- The set can come from another query\nWHERE dept_id IN (SELECT id FROM departments WHERE city = 'Pune')" },
      { type: 'queryResult', query: "SELECT name, dept_id FROM employees WHERE dept_id IN (1, 2);", headers: ['name', 'dept_id'], rows: [['Ana Iyer', '1'], ['Bo Chen', '1'], ['Cy Das', '2'], ['Dia Rao', '2']], note: 'Eli, whose dept_id is NULL, is not a member of any set — NULL is never IN anything.' },
      { type: 'heading', value: 'LIKE — simple pattern matching' },
      { type: 'table', headers: ['Pattern', 'Matches', 'Example match'], rows: [
        ["'A%'", 'Starts with A', 'Ana Iyer'],
        ["'%Roy'", 'Ends with Roy', 'Eli Roy'],
        ["'%a%'", 'Contains a lowercase a', 'Ana Iyer, Cy Das'],
        ["'_o%'", 'Second character is o', 'Bo Chen'],
        ["'C_ Das'", 'C, any one character, then " Das"', 'Cy Das'],
      ] },
      { type: 'queryResult', query: "SELECT name FROM employees WHERE name LIKE '%a%';", headers: ['name'], rows: [['Ana Iyer'], ['Cy Das'], ['Dia Rao']], note: 'LIKE is case-sensitive in PostgreSQL, so the capital A in "Ana" does not match the pattern — the lowercase a in "Ana" does.' },
      { type: 'code', language: 'sql', value: "-- Case-insensitive matching, PostgreSQL-specific\nWHERE name ILIKE '%ana%'\n\n-- Portable equivalent (but disables a plain index)\nWHERE LOWER(name) LIKE '%ana%'\n\n-- Matching a literal % or _ requires an escape\nWHERE code LIKE '100\\%%'   -- codes starting with the text \"100%\"" },
      { type: 'warning', value: 'A leading wildcard — LIKE \'%term\' — cannot use a B-Tree index, so it forces a full table scan. On a large table this is the difference between 2 milliseconds and 2 seconds. For real text search, use a trigram index or PostgreSQL full-text search rather than LIKE.' },
      { type: 'heading', value: 'Regular expressions, when LIKE is not enough' },
      { type: 'code', language: 'sql', value: "-- ~ is case-sensitive regex, ~* is case-insensitive\nWHERE email ~* '^[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,}$'\n\n-- Anchored patterns: names starting with a vowel\nWHERE name ~ '^[AEIOU]'" },
      { type: 'heading', value: 'Putting the filters together' },
      { type: 'code', language: 'sql', value: "SELECT name, dept_id, salary, hired_on\nFROM   employees\nWHERE  dept_id IN (1, 2)\n  AND  salary BETWEEN 60000 AND 95000\n  AND  name NOT LIKE 'Z%'\n  AND  hired_on >= '2021-01-01'\nORDER BY salary DESC\nLIMIT 10;" },
      { type: 'alert', value: 'Order your conditions by how much they eliminate when writing for humans — most selective first reads better. The planner will reorder them anyway based on its statistics, so this is about readability, not speed.' },
    ],
    objectives: [
      'Filter by set membership with IN and its subquery form',
      'Match patterns with LIKE, ILIKE and wildcards',
      'Recognise which patterns can use an index and which cannot',
    ],
    takeaways: [
      'NULL is never IN a set, and never NOT IN one either.',
      'Leading wildcards force a full scan — for real search, use a proper text index.',
      'ILIKE is convenient but PostgreSQL-specific; LOWER() is portable and slower.',
    ],
  },

  // ─────────────────────────── MODULE 5 ───────────────────────────
  'm5-l1': {
    title: 'String Functions',
    content: [
      { type: 'text', value: 'String functions clean, reshape and combine text. They are heavily used in reporting queries and in the migrations that fix data somebody imported badly.' },
      { type: 'table', headers: ['Function', 'Does', 'Example → result'], rows: [
        ['LENGTH(s)', 'Character count', "LENGTH('Ana') → 3"],
        ['UPPER(s) / LOWER(s)', 'Change case', "UPPER('ana') → ANA"],
        ['INITCAP(s)', 'Title case', "INITCAP('ana iyer') → Ana Iyer"],
        ['TRIM(s)', 'Strip surrounding spaces', "TRIM('  a  ') → a"],
        ['LTRIM / RTRIM', 'Strip one side', "RTRIM('a  ') → a"],
        ['SUBSTRING(s FROM p FOR n)', 'Extract part', "SUBSTRING('Ana Iyer' FROM 1 FOR 3) → Ana"],
        ['POSITION(sub IN s)', 'Index of substring, 0 if absent', "POSITION('@' IN email) → 4"],
        ['REPLACE(s, from, to)', 'Substitute text', "REPLACE('a-b','-','_') → a_b"],
        ['SPLIT_PART(s, delim, n)', 'Take the nth piece', "SPLIT_PART('a@b.com','@',2) → b.com"],
        ['LPAD / RPAD', 'Pad to a width', "LPAD('7', 3, '0') → 007"],
      ] },
      { type: 'alert', value: 'SQL strings are 1-indexed, not 0-indexed. SUBSTRING(s FROM 1 FOR 3) takes the first three characters. This catches out every programmer coming from another language.' },
      { type: 'heading', value: 'Concatenation' },
      { type: 'code', language: 'sql', value: "-- || is the standard operator, and PostgreSQL's idiom\nSELECT name || ' <' || email || '>' AS contact FROM employees;\n\n-- CONCAT is portable and, importantly, ignores NULLs\nSELECT CONCAT(first_name, ' ', last_name) FROM people;\n\n-- CONCAT_WS puts a separator between non-null parts only\nSELECT CONCAT_WS(', ', street, city, postcode) AS address FROM places;" },
      { type: 'warning', value: 'Anything || NULL is NULL. If email is missing, the first query above produces NULL for the entire contact string, not a partial one. CONCAT and CONCAT_WS treat NULL as an empty string, which is usually what you wanted.' },
      { type: 'heading', value: 'Worked example: splitting a badly imported name column' },
      { type: 'queryResult', query: "SELECT name,\n       SPLIT_PART(name, ' ', 1)            AS first_name,\n       SPLIT_PART(name, ' ', 2)            AS last_name,\n       UPPER(LEFT(name, 1))                AS initial,\n       LENGTH(name)                        AS chars\nFROM   employees\nORDER BY id\nLIMIT 3;", headers: ['name', 'first_name', 'last_name', 'initial', 'chars'], rows: [['Ana Iyer', 'Ana', 'Iyer', 'A', '8'], ['Bo Chen', 'Bo', 'Chen', 'B', '7'], ['Cy Das', 'Cy', 'Das', 'C', '6']] },
      { type: 'heading', value: 'Generating a slug — a realistic cleanup' },
      { type: 'code', language: 'sql', value: "SELECT title,\n       LOWER(\n         REGEXP_REPLACE(\n           TRIM(title),\n           '[^a-zA-Z0-9]+', '-', 'g'\n         )\n       ) AS slug\nFROM   articles;\n\n-- 'Indexes Explained!  ' → 'indexes-explained-'" },
      { type: 'alert', value: 'A pattern worth internalising: clean data on the way in, not on the way out. Running TRIM and LOWER in every SELECT is slow and easy to forget. Normalise once during INSERT, or add a generated column.' },
    ],
    objectives: [
      'Apply the common string functions to reshape text',
      'Concatenate safely in the presence of NULL',
      'Use regular expression replacement for cleanup tasks',
    ],
    takeaways: [
      'String positions are 1-indexed in SQL.',
      '|| propagates NULL through the whole expression; CONCAT does not.',
      'Normalise text at write time rather than in every read query.',
    ],
  },

  'm5-l2': {
    title: 'Numeric Functions',
    content: [
      { type: 'table', headers: ['Function', 'Does', 'Example → result'], rows: [
        ['ROUND(n, d)', 'Round to d decimal places', 'ROUND(3.14159, 2) → 3.14'],
        ['CEIL(n)', 'Round up to an integer', 'CEIL(3.1) → 4'],
        ['FLOOR(n)', 'Round down to an integer', 'FLOOR(3.9) → 3'],
        ['TRUNC(n, d)', 'Cut off, never round', 'TRUNC(3.99, 1) → 3.9'],
        ['ABS(n)', 'Absolute value', 'ABS(-42) → 42'],
        ['MOD(a, b)', 'Remainder', 'MOD(10, 3) → 1'],
        ['POWER(a, b)', 'Exponent', 'POWER(2, 10) → 1024'],
        ['SQRT(n)', 'Square root', 'SQRT(144) → 12'],
        ['GREATEST / LEAST', 'Max or min of the arguments', 'GREATEST(3, 9, 5) → 9'],
      ] },
      { type: 'heading', value: 'The integer division trap' },
      { type: 'text', value: 'Dividing two integers in SQL gives an integer. This is not a rounding error you can ignore — it silently discards the fractional part, and it is the most common numeric bug in reporting queries.' },
      { type: 'queryResult', query: "SELECT 7 / 2               AS integer_division,\n       7.0 / 2             AS decimal_division,\n       7::NUMERIC / 2      AS explicit_cast,\n       ROUND(7::NUMERIC / 2, 2) AS rounded;", headers: ['integer_division', 'decimal_division', 'explicit_cast', 'rounded'], rows: [['3', '3.5', '3.5', '3.50']], note: 'Cast one side to NUMERIC before dividing. Doing it after the division is too late — the fraction is already gone.' },
      { type: 'heading', value: 'Division by zero' },
      { type: 'code', language: 'sql', value: "-- This aborts the whole query with an error\nSELECT total / quantity FROM order_items;\n\n-- NULLIF turns the 0 into NULL, and dividing by NULL gives NULL\nSELECT total / NULLIF(quantity, 0) AS unit_price FROM order_items;\n\n-- Combine with COALESCE for a displayable default\nSELECT COALESCE(total / NULLIF(quantity, 0), 0) AS unit_price FROM order_items;" },
      { type: 'alert', value: 'NULLIF(x, 0) is the standard idiom for safe division across every SQL engine. Learn it once and you will use it constantly in reporting queries.' },
      { type: 'heading', value: 'Percentages, worked properly' },
      { type: 'queryResult', query: "SELECT name,\n       salary,\n       ROUND(salary * 100.0 / SUM(salary) OVER (), 1) AS pct_of_payroll\nFROM   employees\nORDER BY salary DESC;", headers: ['name', 'salary', 'pct_of_payroll'], rows: [['Ana Iyer', '92000', '26.6'], ['Bo Chen', '78000', '22.5'], ['Cy Das', '64000', '18.5'], ['Dia Rao', '64000', '18.5'], ['Eli Roy', '51000', '14.7']], note: 'The 100.0 is doing real work: written as 100 it would trigger integer division and every percentage would be 0. SUM(...) OVER () is a window function — Module 14 covers it properly.' },
      { type: 'heading', value: 'Rounding money' },
      { type: 'code', language: 'sql', value: "-- ROUND on NUMERIC uses half-up rounding, which is what invoices expect\nSELECT ROUND(2.5::NUMERIC), ROUND(3.5::NUMERIC);   -- 3, 4\n\n-- ROUND on DOUBLE PRECISION uses banker's rounding — different results\nSELECT ROUND(2.5::FLOAT),  ROUND(3.5::FLOAT);      -- 2, 4" },
      { type: 'warning', value: 'That difference is not a curiosity. If your financial totals are computed on FLOAT columns, rounding will disagree with the accounting system in a way that is very hard to trace. NUMERIC everywhere money is involved.' },
    ],
    objectives: [
      'Round and truncate numbers deliberately',
      'Avoid integer division and division-by-zero errors',
      'Compute percentages that are actually correct',
    ],
    takeaways: [
      'Integer ÷ integer = integer. Cast before dividing, never after.',
      'NULLIF(x, 0) is the universal guard against division by zero.',
      'NUMERIC and FLOAT round differently — another reason money is NUMERIC.',
    ],
  },

  'm5-l3': {
    title: 'Date and Time Functions',
    content: [
      { type: 'text', value: 'Date handling is where most reporting bugs live. The functions themselves are simple; the difficulty is timezones and boundaries, so this lesson spends its time there.' },
      { type: 'table', headers: ['Function', 'Returns'], rows: [
        ['NOW() / CURRENT_TIMESTAMP', 'Current date and time with timezone'],
        ['CURRENT_DATE', "Today's date, no time"],
        ['AGE(a, b)', 'The interval between two timestamps, as years/months/days'],
        ['EXTRACT(part FROM ts)', 'One component: YEAR, MONTH, DOW, EPOCH…'],
        ['DATE_TRUNC(unit, ts)', 'Round down to the start of an hour, day, month, year'],
        ['TO_CHAR(ts, fmt)', 'Format as text'],
        ["ts + INTERVAL '1 month'", 'Date arithmetic'],
      ] },
      { type: 'heading', value: 'DATE_TRUNC is the one to learn first' },
      { type: 'text', value: 'Almost every "group by month" or "daily active users" query is built on DATE_TRUNC. It snaps a timestamp down to the start of the unit you name.' },
      { type: 'queryResult', query: "SELECT name,\n       hired_on,\n       DATE_TRUNC('year',  hired_on)::DATE AS year_start,\n       DATE_TRUNC('month', hired_on)::DATE AS month_start,\n       EXTRACT(YEAR FROM hired_on)         AS year\nFROM   employees\nORDER BY hired_on;", headers: ['name', 'hired_on', 'year_start', 'month_start', 'year'], rows: [
        ['Cy Das', '2020-11-23', '2020-01-01', '2020-11-01', '2020'],
        ['Ana Iyer', '2021-03-14', '2021-01-01', '2021-03-01', '2021'],
        ['Bo Chen', '2022-07-01', '2022-01-01', '2022-07-01', '2022'],
        ['Dia Rao', '2023-01-09', '2023-01-01', '2023-01-01', '2023'],
        ['Eli Roy', '2023-06-30', '2023-01-01', '2023-06-01', '2023'],
      ], note: 'Grouping by DATE_TRUNC(\'month\', ...) is how every monthly report is built.' },
      { type: 'heading', value: 'Date arithmetic' },
      { type: 'code', language: 'sql', value: "SELECT CURRENT_DATE + INTERVAL '30 days'   AS in_30_days,\n       CURRENT_DATE - INTERVAL '1 year'    AS a_year_ago,\n       NOW() + INTERVAL '2 hours 30 minutes' AS later_today;\n\n-- Tenure in whole years\nSELECT name, EXTRACT(YEAR FROM AGE(CURRENT_DATE, hired_on)) AS years_served\nFROM   employees;\n\n-- Difference in days: subtracting two DATEs gives an integer\nSELECT hired_on, CURRENT_DATE - hired_on AS days_employed FROM employees;" },
      { type: 'heading', value: 'The boundary bug, and its fix' },
      { type: 'text', value: 'This is worth reading twice. Filtering a timestamp column against bare dates loses almost a full day of data, and the query looks entirely reasonable.' },
      { type: 'code', language: 'sql', value: "-- WRONG: '2024-01-31' means 2024-01-31 00:00:00.\n-- Everything that happened during the 31st is excluded.\nWHERE created_at BETWEEN '2024-01-01' AND '2024-01-31'\n\n-- ALSO WRONG: works, but the function on the column kills the index\nWHERE DATE(created_at) BETWEEN '2024-01-01' AND '2024-01-31'\n\n-- RIGHT: a half-open interval, and created_at stays bare so an index applies\nWHERE created_at >= '2024-01-01'\n  AND created_at <  '2024-02-01'" },
      { type: 'warning', value: 'The half-open pattern — inclusive start, exclusive end — is correct for every granularity and every timezone. Adopt it as a reflex and an entire category of off-by-one reporting bugs disappears.' },
      { type: 'heading', value: 'Timezones' },
      { type: 'code', language: 'sql', value: "-- TIMESTAMPTZ stores UTC internally and renders in your session timezone\nSHOW timezone;\nSET  timezone = 'Asia/Kolkata';\n\nSELECT NOW();                                -- rendered in IST\nSELECT NOW() AT TIME ZONE 'UTC';             -- the underlying UTC value\nSELECT NOW() AT TIME ZONE 'America/New_York'; -- the same instant, elsewhere" },
      { type: 'alert', value: 'The working rule for any application: store TIMESTAMPTZ, which is UTC underneath; convert to a local timezone only at the moment you display it. Storing local times is how you end up with two 01:30s on the night the clocks change.' },
      { type: 'heading', value: 'Formatting for output' },
      { type: 'code', language: 'sql', value: "SELECT TO_CHAR(hired_on, 'DD Mon YYYY')       AS pretty,   -- 14 Mar 2021\n       TO_CHAR(hired_on, 'YYYY-MM')           AS period,   -- 2021-03\n       TO_CHAR(NOW(),    'Day, DD Month YYYY') AS long_form\nFROM   employees;" },
    ],
    objectives: [
      'Truncate and extract parts of timestamps for reporting',
      'Perform date arithmetic with INTERVAL',
      'Write timezone-safe, index-friendly date range filters',
    ],
    takeaways: [
      "DATE_TRUNC is the backbone of every 'per day/month/year' report.",
      'Half-open ranges are the only date filter that is correct at every boundary.',
      'Store UTC (TIMESTAMPTZ), convert only when displaying.',
    ],
  },
};
