import { LessonMap, EMPLOYEES, DEPARTMENTS } from './types';

/** Course overview + Module 1 (fundamentals) + Module 2 (design basics). */
export const foundationLessons: LessonMap = {
  'overview-welcome': {
    title: 'Welcome to SQL Mastery',
    content: [
      { type: 'text', value: 'SQL is the oldest language you will still be writing in twenty years. It was standardised in 1986, and every serious application built since — banking, ticketing, payroll, e-commerce, analytics — still asks a relational database questions in almost exactly the same syntax. Learning it once pays off for an entire career.' },
      { type: 'text', value: 'This course takes you from "what is a table?" to designing a normalised schema, reading an execution plan, and wiring a database into a Node.js backend safely. Every module builds on the last, and every concept is shown against real rows so you can see what a query actually does rather than memorising its shape.' },
      { type: 'heading', value: 'The dataset you will see everywhere' },
      { type: 'text', value: 'Rather than inventing new tables for each topic, almost every example in this course queries the same two small tables. By Module 7 you will know these five employees by name, which means when we introduce a LEFT JOIN, the only new thing on the page is the join itself.' },
      { type: 'dataset', name: 'employees', caption: 'five rows — note that Eli has no department', ...EMPLOYEES },
      { type: 'dataset', name: 'departments', caption: 'three rows — note that Legal has no employees', ...DEPARTMENTS },
      { type: 'text', value: 'Those two gaps are deliberate. An unmatched row on each side is what makes the difference between INNER, LEFT, RIGHT and FULL joins visible instead of theoretical.' },
      { type: 'heading', value: 'How to work through this course' },
      { type: 'steps', steps: [
        { label: 'Read', text: 'each lesson pairs the concept with the exact rows it produces.' },
        { label: 'Predict', text: 'before you scroll to a result grid, guess what it will contain. Being wrong is the fastest way to learn.' },
        { label: 'Run it', text: 'keep a psql window open and type the query yourself. Reading SQL is easy; writing it is the skill.' },
        { label: 'Break it', text: 'change a JOIN to a LEFT JOIN, remove a GROUP BY column, drop a WHERE. Watching a query fail teaches you the rule behind it.' },
      ] },
      { type: 'alert', value: 'Examples use PostgreSQL syntax, which is the closest of the mainstream engines to the SQL standard. Almost everything transfers to MySQL unchanged; where it does not, the lesson says so explicitly.' },
    ],
    objectives: [
      'Understand what this course covers and how the modules build on each other',
      'Meet the employees and departments tables used throughout',
      'Set up a habit of predicting a result before reading it',
    ],
    takeaways: [
      'SQL is a declarative language: you describe the rows you want, not how to fetch them.',
      'One consistent dataset across the course means each lesson introduces exactly one new idea.',
      'Typing every query yourself is the difference between recognising SQL and writing it.',
    ],
  },

  'overview-outcomes': {
    title: 'Learning Outcomes',
    content: [
      { type: 'text', value: 'By the end of this path you will be able to do the following, without reaching for documentation on the basics.' },
      { type: 'heading', value: 'Query' },
      { type: 'list', items: [
        'Filter, sort and paginate with WHERE, ORDER BY and LIMIT, including correct NULL handling.',
        'Combine four or five tables with the right join type for the question being asked.',
        'Aggregate with GROUP BY and HAVING, and know precisely why HAVING exists separately from WHERE.',
        'Reach for a subquery, a CTE or a window function depending on which one the problem actually calls for.',
      ] },
      { type: 'heading', value: 'Design' },
      { type: 'list', items: [
        'Pick data types that will not betray you in production (why money is never a FLOAT).',
        'Model one-to-one, one-to-many and many-to-many relationships with the right keys and constraints.',
        'Normalise a schema to 3NF, and argue for the specific places you would deliberately denormalise.',
        'Draw an ER diagram a colleague can read.',
      ] },
      { type: 'heading', value: 'Operate' },
      { type: 'list', items: [
        'Wrap multi-step changes in a transaction and reason about what happens when one step fails.',
        'Read an EXPLAIN ANALYZE plan and tell a sequential scan from an index scan.',
        'Add an index that helps, and recognise the ones that only cost you write throughput.',
        'Connect a Node.js service to PostgreSQL using pooled, parameterised queries and versioned migrations.',
      ] },
      { type: 'heading', value: 'A realistic timeline' },
      { type: 'table', headers: ['Phase', 'Modules', 'What clicks'], rows: [
        ['Foundations', '1–5', 'Tables, types, constraints, and getting exactly the rows you asked for'],
        ['Analysis', '6–8', 'Aggregation, joins and subqueries — where SQL starts feeling powerful'],
        ['Depth', '9–14', 'Indexes, transactions, normalisation, window functions'],
        ['Applied', '15–17', 'Backend integration, full projects, and interview-grade fluency'],
      ] },
      { type: 'alert', value: 'Modules 6 to 8 are the ones that separate people who "know some SQL" from people who are trusted with a production database. If you slow down anywhere, slow down there.' },
    ],
    objectives: [
      'Know the concrete skills this course delivers',
      'Understand which modules carry the most weight',
      'Set expectations for pacing across the seventeen modules',
    ],
    takeaways: [
      'The goal is fluency, not syntax recall — being able to reach for the right construct without thinking.',
      'Joins, aggregation and subqueries are the highest-leverage modules in the course.',
      'Design and operations skills are what distinguish a backend engineer from a query writer.',
    ],
  },

  // ─────────────────────────── MODULE 1 ───────────────────────────
  'm1-l1': {
    title: 'What is Data?',
    content: [
      { type: 'text', value: 'Data is any fact recorded in a form a machine can process. On its own a value like 92000 means nothing. Attached to a column called salary, in a row that also holds the name Ana Iyer, it becomes information — something you can act on.' },
      { type: 'text', value: 'That difference is the whole reason databases exist. A database does not just store values; it stores the structure that gives values meaning, and it enforces that structure so meaning cannot quietly rot.' },
      { type: 'heading', value: 'The three shapes data comes in' },
      { type: 'compare', columns: [
        { title: 'Structured', tone: 'olive', subtitle: 'Fits a table with fixed columns', items: [
          'A users table: id, email, created_at',
          'Every row has the same fields with the same types',
          'You can ask precise questions and get exact answers',
          'This is what SQL is built for',
        ] },
        { title: 'Semi-structured', tone: 'honey', subtitle: 'Has structure, but it varies', items: [
          'JSON API responses, XML feeds, log lines',
          'Two records may carry different fields',
          'Queryable, but only with special operators',
          'PostgreSQL handles this with JSONB (Module 14)',
        ] },
        { title: 'Unstructured', tone: 'rose', subtitle: 'No inherent field layout', items: [
          'Photos, PDFs, audio, free-form text',
          'Cannot be filtered on content by SQL alone',
          'Usually stored as files, with metadata in SQL',
          'Search engines and vector stores handle these',
        ] },
      ] },
      { type: 'heading', value: 'Why the distinction matters in practice' },
      { type: 'text', value: 'Almost every real system holds all three. A typical product stores user accounts as structured rows, event payloads as semi-structured JSON, and profile pictures as unstructured blobs on object storage with only the URL kept in the database.' },
      { type: 'example', title: 'A concrete split', value: 'Instagram-style app:\n  • users, follows, posts, likes  →  structured, SQL tables\n  • the analytics event for each view →  semi-structured JSON\n  • the image itself                  →  unstructured file in S3;\n                                        SQL stores only its key' },
      { type: 'alert', value: 'A common beginner instinct is to store everything as JSON because it is flexible. Flexibility is exactly what you do not want for the facts your business depends on — a schema is a promise the database keeps on your behalf.' },
    ],
    objectives: [
      'Distinguish data from information',
      'Classify data as structured, semi-structured or unstructured',
      'Recognise which storage each kind belongs in',
    ],
    takeaways: [
      'Structure is what turns a value into a fact you can query.',
      'SQL is purpose-built for structured data; the other two shapes have their own tools.',
      'Real systems mix all three — the skill is knowing which belongs where.',
    ],
  },

  'm1-l2': {
    title: 'File System vs Database',
    content: [
      { type: 'text', value: 'Before databases, applications stored data in flat files: one CSV per entity, read and written by whatever code needed it. It works, right up until two things happen at once — and in any real system, two things always happen at once.' },
      { type: 'text', value: 'Imagine a shop with orders.csv and customers.csv. Here is what goes wrong, in the order it usually goes wrong.' },
      { type: 'heading', value: 'Problem 1 — redundancy leads to contradiction' },
      { type: 'text', value: 'The customer address is copied into every order row so the shipping script can read one file. A customer moves house. You update customers.csv. Now three thousand order rows disagree with the customer record, and nothing in the system knows which one is right.' },
      { type: 'heading', value: 'Problem 2 — concurrent writes destroy each other' },
      { type: 'steps', title: 'Two processes, one file, no coordination', steps: [
        { label: '10:00:00', text: 'Process A reads orders.csv into memory (1,000 rows).' },
        { label: '10:00:01', text: 'Process B reads the same file (the same 1,000 rows).' },
        { label: '10:00:02', text: 'A appends its order and writes 1,001 rows back.' },
        { label: '10:00:03', text: 'B appends its order and writes its own 1,001 rows back — overwriting A.' },
        { label: 'Result', text: "A's order is gone. Nothing errored. Nobody finds out until the customer complains." },
      ] },
      { type: 'heading', value: 'Problem 3 — no integrity rules' },
      { type: 'text', value: 'Nothing stops a script writing "twelve" into a quantity column, an order referencing a customer who was deleted last week, or a negative price. Every one of those checks has to be re-implemented in every program that touches the file, and they will drift apart.' },
      { type: 'heading', value: 'Problem 4 — no partial failure recovery' },
      { type: 'text', value: 'A transfer means debiting one row and crediting another. If the process dies between the two writes, a flat file has no way to undo the first one. The money simply vanishes.' },
      { type: 'heading', value: 'What a DBMS gives you instead' },
      { type: 'compare', columns: [
        { title: 'Flat files', tone: 'rose', items: [
          'You write the read/write logic yourself',
          'Last writer silently wins',
          'Any program can write any garbage',
          'Finding one row means scanning the whole file',
          'Half-finished work stays half-finished',
        ] },
        { title: 'A database', tone: 'olive', items: [
          'One query language for every access pattern',
          'Locking and transactions serialise conflicts',
          'Types and constraints reject invalid data at the door',
          'Indexes find one row out of millions in milliseconds',
          'A failed transaction rolls back completely',
        ] },
      ] },
      { type: 'alert', value: 'Flat files are not obsolete — CSV and Parquet are excellent for bulk import, export and archival. The rule is simple: files for data at rest that nobody edits, a database for data that changes.' },
    ],
    objectives: [
      'Name the four failure modes of file-based storage',
      'Explain how concurrent writes silently lose data',
      'Justify choosing a database over files for mutable data',
    ],
    takeaways: [
      'Redundancy is not a storage problem, it is a correctness problem — copies disagree.',
      'Concurrency is where flat files fail hardest, and it fails silently.',
      'A DBMS centralises the rules so every program is held to the same ones.',
    ],
  },

  'm1-l3': {
    title: 'What is DBMS & RDBMS?',
    content: [
      { type: 'text', value: 'A DBMS (Database Management System) is the software layer sitting between your application and the bytes on disk. You never open a data file yourself; you send the DBMS a request and it handles storage, retrieval, concurrency, permissions and crash recovery.' },
      { type: 'text', value: 'An RDBMS is a DBMS built on the relational model, published by Edgar F. Codd at IBM in 1970. The idea is deceptively small: store all data in tables of rows and columns, and let relationships between tables be expressed by matching values rather than by pointers on disk.' },
      { type: 'heading', value: 'The four ideas that make it relational' },
      { type: 'steps', steps: [
        { label: 'Tables', text: 'every piece of data lives in a named table with named, typed columns. Nothing is stored "off to the side".' },
        { label: 'Rows are unordered', text: 'a table is a set. There is no "third row" unless you ask for an order explicitly with ORDER BY.' },
        { label: 'Keys, not pointers', text: 'an order refers to a customer by storing the customer id value — not a disk address. Move the data, reorganise the file, the relationship still holds.' },
        { label: 'Declarative access', text: 'you state which rows you want; the engine decides how to find them. That freedom is what lets it use an index you added years later without you rewriting a single query.' },
      ] },
      { type: 'diagram', name: 'sql-keys', caption: 'Relationships are values, not pointers — and the database refuses to store a value that points nowhere.' },
      { type: 'heading', value: 'What the engine is doing for you' },
      { type: 'table', headers: ['Responsibility', 'What it means in practice'], rows: [
        ['Storage management', 'Lays out rows in pages, reuses freed space, keeps indexes in sync'],
        ['Query processing', 'Parses your SQL, chooses an execution plan, runs it'],
        ['Concurrency control', 'Lets hundreds of sessions read and write without corrupting each other'],
        ['Integrity enforcement', 'Rejects writes that break a type, a constraint or a foreign key'],
        ['Durability & recovery', 'Writes ahead to a log so a power cut cannot lose a committed transaction'],
        ['Access control', 'Decides which roles may read or modify which tables'],
      ] },
      { type: 'alert', value: 'The word "relation" in relational model means a table, not a relationship between tables. It comes from set theory, and it trips up nearly everyone the first time.' },
    ],
    objectives: [
      'Define DBMS and RDBMS and state the difference',
      'Explain the four principles of the relational model',
      'List the responsibilities a database engine takes off your hands',
    ],
    takeaways: [
      'A relation is a table; relationships between tables are expressed by matching key values.',
      'Declarative querying is what lets the engine optimise without you rewriting queries.',
      'Concurrency, integrity and crash recovery are the hardest parts, and the engine owns them.',
    ],
  },

  'm1-l4': {
    title: 'SQL vs NoSQL',
    content: [
      { type: 'text', value: 'This comparison is usually framed as a rivalry. It is better understood as a trade: NoSQL databases give up some guarantees in exchange for a different scaling and modelling story. Knowing exactly what is being traded is what makes you able to choose.' },
      { type: 'compare', columns: [
        { title: 'Relational (SQL)', tone: 'olive', subtitle: 'PostgreSQL, MySQL, SQL Server', items: [
          'Fixed schema declared up front and enforced on every write',
          'Relationships modelled with foreign keys and resolved with joins',
          'Strong ACID transactions across multiple tables',
          'Scales up (bigger machine) and out with more effort',
          'Best when the data has real relationships and correctness matters',
        ] },
        { title: 'Non-relational (NoSQL)', tone: 'rose', subtitle: 'MongoDB, DynamoDB, Cassandra, Redis', items: [
          'Flexible or absent schema; each document can differ',
          'Related data usually nested inside one document instead of joined',
          'Transactions often limited to a single document or partition',
          'Designed to scale out across many nodes from day one',
          'Best for huge volume, simple access patterns, evolving shapes',
        ] },
      ] },
      { type: 'heading', value: 'The same data, modelled both ways' },
      { type: 'text', value: 'A blog post with its tags and author. In SQL you would normalise it across three tables and join. In a document store you would embed it.' },
      { type: 'code', language: 'sql', value: "-- Relational: three tables, one join per relationship\nSELECT p.title, u.name AS author\nFROM   posts p\nJOIN   users u ON u.id = p.author_id\nWHERE  p.id = 42;" },
      { type: 'code', language: 'json', value: '// Document: one read, everything embedded\n{\n  "_id": 42,\n  "title": "Indexes explained",\n  "author": { "id": 7, "name": "Ana Iyer" },\n  "tags": ["databases", "performance"]\n}' },
      { type: 'text', value: 'The document version is one fast read. But if Ana changes her name, you must find and update every post that embedded it — the exact redundancy problem from the flat-file lesson, now chosen deliberately in exchange for read speed.' },
      { type: 'heading', value: 'How to actually choose' },
      { type: 'table', headers: ['If your situation is…', 'Lean toward'], rows: [
        ['Money, inventory, bookings — anything where a wrong number is unacceptable', 'SQL'],
        ['Entities that genuinely relate to each other in many directions', 'SQL'],
        ['You will need to answer questions you have not thought of yet', 'SQL'],
        ['Enormous write volume with one known access pattern (event logs, metrics)', 'NoSQL'],
        ['Deeply nested documents always read as a whole', 'NoSQL'],
        ['Caching, sessions, leaderboards', 'A key-value store like Redis'],
      ] },
      { type: 'alert', value: 'Most production systems use both. A common shape is PostgreSQL as the source of truth, Redis for caching, and a search index for text. "SQL vs NoSQL" is rarely a decision about the whole system — it is a decision per workload.' },
      { type: 'warning', value: 'Choosing NoSQL to avoid designing a schema is choosing to design it later, in application code, where nothing enforces it. Schemaless does not mean structure-free — it means the structure is undocumented.' },
    ],
    objectives: [
      'Articulate what NoSQL trades away and what it gains',
      'Model the same data relationally and as a document',
      'Choose a store based on access pattern rather than fashion',
    ],
    takeaways: [
      'Embedding buys read speed and pays for it with update cost and duplication.',
      'SQL earns its keep when data relates in many directions or correctness is non-negotiable.',
      'The realistic answer is usually "both, for different jobs".',
    ],
  },

  'm1-l5': {
    title: 'Popular Databases',
    content: [
      { type: 'text', value: 'The SQL you learn here transfers across all of these. What differs is the extras: types, functions, and how far each engine goes beyond the standard.' },
      { type: 'table', headers: ['Engine', 'Character', 'Reach for it when'], rows: [
        ['PostgreSQL', 'Open source, standards-first, extremely feature-rich', 'Default choice for a new backend. JSONB, arrays, CTEs, window functions, extensions'],
        ['MySQL / MariaDB', 'Open source, ubiquitous, simple to operate', 'Existing PHP or WordPress estates, huge hosting support'],
        ['SQLite', 'A library, not a server — the whole database is one file', 'Mobile apps, desktop apps, tests, prototypes'],
        ['SQL Server', 'Microsoft, deep .NET and Windows integration', 'Enterprise Microsoft stacks'],
        ['Oracle', 'Very mature, very expensive, very entrenched', 'Banking and legacy enterprise systems'],
      ] },
      { type: 'heading', value: 'Why this course uses PostgreSQL' },
      { type: 'list', items: [
        'It follows the SQL standard more closely than any other mainstream engine, so what you learn is transferable rather than dialect-specific.',
        'It ships with the advanced features you will need later — window functions, CTEs, JSONB, full-text search — without add-ons.',
        'Its EXPLAIN output is the clearest of any engine, which matters enormously for Module 9.',
        'It is free, and it is what most new backend projects choose.',
      ] },
      { type: 'heading', value: 'Differences you will actually hit' },
      { type: 'table', headers: ['Task', 'PostgreSQL', 'MySQL'], rows: [
        ['Auto-incrementing id', 'GENERATED ALWAYS AS IDENTITY or SERIAL', 'AUTO_INCREMENT'],
        ['String concatenation', "a || b", 'CONCAT(a, b)'],
        ['Case-sensitive LIKE', 'LIKE is case-sensitive; ILIKE is not', 'LIKE is case-insensitive by default'],
        ['Limit rows', 'LIMIT 10', 'LIMIT 10 (same)'],
        ['Current timestamp', 'NOW()', 'NOW() (same)'],
      ] },
      { type: 'alert', value: 'Do not try to learn several dialects at once. Learn one deeply; the second one takes a weekend because the concepts are identical and only the spelling changes.' },
    ],
    objectives: [
      'Compare the major relational engines and their niches',
      'Explain why PostgreSQL is a strong default',
      'Recognise the handful of dialect differences that matter early',
    ],
    takeaways: [
      'Concepts transfer completely between engines; only syntax details differ.',
      'SQLite is a library, not a server — that single fact explains most of its trade-offs.',
      'Learn one engine deeply rather than three shallowly.',
    ],
  },

  'm1-l6': {
    title: 'Installing PostgreSQL',
    content: [
      { type: 'text', value: 'You need a database running before anything else in this course is useful. Docker is the recommended route: it keeps your machine clean, gives you the exact version you want, and lets you throw the whole thing away and start again in ten seconds.' },
      { type: 'heading', value: 'Option A — Docker (recommended)' },
      { type: 'code', language: 'bash', value: 'docker run --name sql-course \\\n  -e POSTGRES_PASSWORD=secret \\\n  -e POSTGRES_DB=skillofied \\\n  -p 5432:5432 \\\n  -v sql_course_data:/var/lib/postgresql/data \\\n  -d postgres:16' },
      { type: 'syntax', title: 'What each flag does', parts: [
        { clause: '--name', text: 'a handle so later commands can say sql-course instead of a container id.' },
        { clause: '-e POSTGRES_PASSWORD', text: 'the password for the default postgres superuser. Required — the image refuses to start without it.' },
        { clause: '-e POSTGRES_DB', text: 'creates this database on first boot so you are not working in the default postgres one.' },
        { clause: '-p 5432:5432', text: 'maps the container port to your machine, so tools on your laptop can connect to localhost:5432.' },
        { clause: '-v sql_course_data', text: 'a named volume. Without this, deleting the container deletes all your data.' },
        { clause: '-d', text: 'detached: run in the background and give you your terminal back.' },
      ] },
      { type: 'heading', value: 'Connecting' },
      { type: 'code', language: 'bash', value: '# open a psql shell inside the container\ndocker exec -it sql-course psql -U postgres -d skillofied\n\n# useful psql meta-commands once you are in\n\\l          -- list databases\n\\dt         -- list tables in the current schema\n\\d users    -- describe the users table\n\\x          -- toggle expanded output (great for wide rows)\n\\q          -- quit' },
      { type: 'heading', value: 'Option B — native install' },
      { type: 'code', language: 'bash', value: '# macOS\nbrew install postgresql@16 && brew services start postgresql@16\n\n# Ubuntu / Debian\nsudo apt install postgresql postgresql-contrib\nsudo systemctl start postgresql\n\n# Windows: download the EnterpriseDB installer from postgresql.org' },
      { type: 'heading', value: 'A GUI is worth installing too' },
      { type: 'text', value: 'psql is excellent for running statements, but a graphical client makes result sets and schemas far easier to read while you are learning. DBeaver is free and works with every engine in this course; pgAdmin ships with PostgreSQL; TablePlus is a polished paid option.' },
      { type: 'warning', value: 'Forgetting the -v volume flag is the single most common mistake here. The container works perfectly, you build a schema over a week, then you recreate the container and everything is gone. Name the volume.' },
      { type: 'alert', value: 'Verify your setup by running SELECT version(); — if that returns a row, you are ready for Module 2.' },
    ],
    objectives: [
      'Run PostgreSQL locally via Docker or a native install',
      'Connect with psql and navigate using meta-commands',
      'Persist data correctly with a named volume',
    ],
    takeaways: [
      'Docker gives you a disposable, version-pinned database in one command.',
      'Without a named volume, your data lives and dies with the container.',
      'psql meta-commands (\\dt, \\d, \\x) are the fastest way to explore a schema.',
    ],
  },

  'm1-l7': {
    title: 'Database Architecture',
    content: [
      { type: 'text', value: 'When you run a query, it does not simply "read a file". It travels through several distinct stages, and understanding those stages is what makes performance tuning in Module 9 make sense rather than feel like guesswork.' },
      { type: 'diagram', name: 'sql-architecture', caption: 'A query is text until the planner turns it into a strategy. That strategy is what actually costs time.' },
      { type: 'heading', value: 'The journey of one query' },
      { type: 'steps', steps: [
        { label: 'Connection', text: 'your client opens a TCP session and authenticates. This is expensive, which is why backends pool connections (Module 15).' },
        { label: 'Parser', text: 'checks the SQL is syntactically valid and that every table and column named actually exists. A typo dies here.' },
        { label: 'Planner / optimiser', text: 'the interesting stage. It considers several ways to get your rows — scan the whole table, use this index, join in this order — estimates the cost of each, and picks the cheapest.' },
        { label: 'Executor', text: 'runs the chosen plan, reading pages from the buffer cache or from disk.' },
        { label: 'Result', text: 'rows are streamed back to the client over the same connection.' },
      ] },
      { type: 'heading', value: 'Why the planner is the whole game' },
      { type: 'text', value: 'Two queries that return identical rows can differ by a factor of ten thousand in speed, purely because the planner chose a different strategy. You never tell PostgreSQL how to fetch rows — you influence the planner by adding indexes and keeping statistics fresh, and then you verify with EXPLAIN.' },
      { type: 'code', language: 'sql', value: '-- Ask the planner what it intends to do, without running the query\nEXPLAIN SELECT * FROM employees WHERE salary > 70000;\n\n-- Run it and report what actually happened\nEXPLAIN ANALYZE SELECT * FROM employees WHERE salary > 70000;' },
      { type: 'heading', value: 'Memory and disk' },
      { type: 'table', headers: ['Component', 'Role'], rows: [
        ['Shared buffers', 'An in-memory cache of recently used data pages. A cache hit is roughly 1000× faster than a disk read'],
        ['WAL (write-ahead log)', 'Every change is written here before the data files. This is what makes a committed transaction survive a crash'],
        ['Data files', 'The tables and indexes themselves, stored as fixed-size pages (8 KB in PostgreSQL)'],
        ['Background writer', 'Flushes dirty pages to disk gradually so no single query pays the whole cost'],
      ] },
      { type: 'alert', value: 'The write-ahead log is the mechanism behind the D in ACID. A COMMIT returns as soon as the log entry is safely on disk — the data files catch up afterwards. That is why commits are fast and crashes are survivable.' },
    ],
    objectives: [
      'Trace a query through connection, parse, plan and execute',
      'Explain why the planner determines query speed',
      'Describe the roles of shared buffers and the write-ahead log',
    ],
    takeaways: [
      'Parsing catches typos; planning determines performance. They are entirely different failures.',
      'You never dictate the strategy — you give the planner better options and verify with EXPLAIN.',
      'The WAL is why a committed transaction survives losing power one millisecond later.',
    ],
  },

  // ─────────────────────────── MODULE 2 ───────────────────────────
  'm2-l1': {
    title: 'Database, Schema, Tables',
    content: [
      { type: 'text', value: 'Four words get used loosely in conversation and precisely in SQL: server, database, schema, table. Getting them straight now prevents a lot of confusion later, particularly when a query fails with "relation does not exist" even though you can see the table right there.' },
      { type: 'diagram', name: 'sql-hierarchy', caption: 'Each level is a namespace inside the one above it, and each bar inside a table is one row.' },
      { type: 'table', headers: ['Level', 'What it is', 'Example'], rows: [
        ['Server (cluster)', 'One running PostgreSQL process listening on a port', 'localhost:5432'],
        ['Database', 'An isolated collection of schemas. You connect to exactly one at a time', 'skillofied'],
        ['Schema', 'A namespace grouping tables inside a database', 'public, analytics, audit'],
        ['Table', 'The actual grid of typed columns and rows', 'employees'],
      ] },
      { type: 'heading', value: 'The rule that surprises people' },
      { type: 'text', value: 'A single query cannot span two databases. Schemas within one database can be joined freely; separate databases cannot. This is why teams usually create one database per application and separate concerns with schemas rather than with databases.' },
      { type: 'code', language: 'sql', value: '-- Create a database (run from psql, outside a transaction)\nCREATE DATABASE skillofied;\n\n-- Connect to it\n\\c skillofied\n\n-- Create a schema to group related tables\nCREATE SCHEMA analytics;\n\n-- Fully qualified: schema.table\nCREATE TABLE analytics.page_views (\n  id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  path       TEXT NOT NULL,\n  viewed_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()\n);\n\n-- Unqualified names resolve against the search_path, which is "public" by default\nCREATE TABLE employees ( ... );   -- becomes public.employees' },
      { type: 'heading', value: 'What a table declaration actually fixes' },
      { type: 'text', value: 'Creating a table is a set of promises: these columns exist, in this order, with these types, subject to these rules. Every INSERT is checked against them. That is the contract that flat files could not offer.' },
      { type: 'code', language: 'sql', value: 'CREATE TABLE employees (\n  id        INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  name      VARCHAR(100)  NOT NULL,\n  dept_id   INT           REFERENCES departments(id),\n  salary    NUMERIC(10,2) NOT NULL CHECK (salary > 0),\n  hired_on  DATE          NOT NULL DEFAULT CURRENT_DATE\n);' },
      { type: 'warning', value: '"relation does not exist" almost always means one of three things: you are connected to the wrong database, the table lives in a schema not on your search_path, or the name was created with capital letters inside double quotes. Unquoted identifiers in PostgreSQL are folded to lowercase — CREATE TABLE Users creates users, but CREATE TABLE "Users" creates a table you must always quote.' },
    ],
    objectives: [
      'Distinguish server, database, schema and table',
      'Use schemas to namespace tables within one database',
      'Read a CREATE TABLE statement as a set of enforced promises',
    ],
    takeaways: [
      'One connection sees one database; schemas — not databases — are how you group inside it.',
      'Unquoted identifiers are lowercased, which is the cause of most "does not exist" errors.',
      'A table definition is a contract the engine enforces on every single write.',
    ],
  },

  'm2-l2': {
    title: 'Rows, Columns and NULL',
    content: [
      { type: 'text', value: 'A column is a named, typed attribute — the same kind of fact for every row. A row is one complete record. That much is easy. The part that quietly causes bugs for years is the third element: NULL.' },
      { type: 'dataset', name: 'employees', caption: 'Eli has no dept_id — that empty cell is NULL, not zero and not an empty string', ...EMPLOYEES, highlightRows: [4] },
      { type: 'heading', value: 'NULL means "unknown", not "empty"' },
      { type: 'text', value: 'This is the single most important idea in the lesson. NULL is not a value; it is the absence of one. And because it is unknown, any comparison involving it returns neither true nor false — it returns unknown, and rows are only kept when a condition is definitely true.' },
      { type: 'code', language: 'sql', value: "-- All of these are UNKNOWN, not TRUE, and never match a row:\nNULL = NULL      -- unknown\nNULL <> 5        -- unknown\nNULL + 100       -- NULL\n\n-- The only correct tests:\ndept_id IS NULL\ndept_id IS NOT NULL" },
      { type: 'queryResult', query: '-- Intuition says this returns Eli. It returns nothing.\nSELECT name, dept_id\nFROM   employees\nWHERE  dept_id = NULL;', headers: ['name', 'dept_id'], rows: [], note: 'Zero rows. The comparison never evaluated to true, so no row qualified — and no error was raised, which is what makes this bug so easy to ship.' },
      { type: 'queryResult', query: 'SELECT name, dept_id\nFROM   employees\nWHERE  dept_id IS NULL;', headers: ['name', 'dept_id'], rows: [['Eli Roy', '']], note: 'IS NULL is a different operator entirely, and it is the only one that works.' },
      { type: 'heading', value: 'The second NULL trap: exclusion filters' },
      { type: 'text', value: 'A filter like dept_id <> 1 does not mean "everyone not in Engineering". It means "everyone we know is not in Engineering" — and Eli, whose department is unknown, is silently excluded.' },
      { type: 'queryResult', query: "SELECT name, dept_id FROM employees WHERE dept_id <> 1;", headers: ['name', 'dept_id'], rows: [['Cy Das', '2'], ['Dia Rao', '2']], note: 'Eli is missing. If you wanted them, you must ask for them: WHERE dept_id <> 1 OR dept_id IS NULL.' },
      { type: 'heading', value: 'Handling NULL deliberately' },
      { type: 'code', language: 'sql', value: "-- COALESCE returns the first non-NULL argument\nSELECT name, COALESCE(dept_id::TEXT, 'unassigned') AS dept\nFROM   employees;\n\n-- NULLIF does the reverse: turns a sentinel value back into NULL\nSELECT NULLIF(rating, 0) FROM reviews;   -- treat 0 as 'not rated'" },
      { type: 'warning', value: 'Never use 0, -1 or the empty string as a stand-in for "missing". Those are real values: they will be counted by COUNT, included in AVG, and matched by equality. NULL exists precisely so the engine can keep missing data out of your arithmetic.' },
      { type: 'alert', value: 'A useful habit: every time you add a nullable column, write down what NULL means for it. "No department yet" and "explicitly no department" are different facts, and if they share a representation you will eventually need to tell them apart.' },
    ],
    objectives: [
      'Describe rows and columns precisely',
      'Explain why NULL comparisons return unknown',
      'Use IS NULL, COALESCE and NULLIF correctly',
    ],
    takeaways: [
      'NULL means unknown, so = NULL matches nothing and raises no error.',
      'Exclusion filters silently drop NULL rows unless you ask for them back.',
      'Sentinel values like 0 or "" pollute aggregates; NULL is the correct representation of missing.',
    ],
  },

  'm2-l3': {
    title: 'SQL Data Types',
    content: [
      { type: 'text', value: 'Choosing a type is not bookkeeping — it is the first correctness decision you make about a column. The wrong type will let bad data in, silently lose precision, or make a query impossible to write later.' },
      { type: 'heading', value: 'Numbers' },
      { type: 'table', headers: ['Type', 'Range / precision', 'Use for'], rows: [
        ['SMALLINT', '±32,767', 'Small enumerations, ages, counts you are certain stay tiny'],
        ['INTEGER', '±2.1 billion', 'The default for ids and counts'],
        ['BIGINT', '±9.2 quintillion', 'High-volume ids, byte counts, anything that might exceed 2 billion'],
        ['NUMERIC(p,s)', 'Exact, arbitrary precision', 'Money, tax, anything where the arithmetic must be exact'],
        ['REAL / DOUBLE PRECISION', 'Approximate, binary floating point', 'Scientific measurement, coordinates, never money'],
      ] },
      { type: 'heading', value: 'Why money is never a FLOAT' },
      { type: 'text', value: 'Binary floating point cannot represent 0.1 exactly, in the same way decimal cannot represent one third exactly. The tiny error is invisible for one row and devastating across a million.' },
      { type: 'queryResult', query: "SELECT 0.1::FLOAT  + 0.2::FLOAT   AS float_math,\n       0.1::NUMERIC + 0.2::NUMERIC AS numeric_math;", headers: ['float_math', 'numeric_math'], rows: [['0.30000000000000004', '0.3']], note: 'Multiply that error by a few million invoice lines and you have a reconciliation problem nobody can explain.' },
      { type: 'heading', value: 'Text' },
      { type: 'table', headers: ['Type', 'Behaviour', 'Use for'], rows: [
        ['CHAR(n)', 'Fixed length, space-padded to n', 'Almost never — the padding surprises everyone'],
        ['VARCHAR(n)', 'Variable length, rejects anything longer than n', 'When a real business limit exists (a 2-letter country code)'],
        ['TEXT', 'Variable length, unlimited', 'The sensible default for most string columns'],
      ] },
      { type: 'alert', value: 'In PostgreSQL, TEXT and VARCHAR have identical performance — VARCHAR(n) is TEXT plus a length check. Use VARCHAR(n) only when n is a genuine rule, not a guess about how long a name might get.' },
      { type: 'heading', value: 'Dates and times' },
      { type: 'table', headers: ['Type', 'Stores', 'Note'], rows: [
        ['DATE', 'A calendar day', 'Birthdays, invoice dates'],
        ['TIME', 'A clock time with no date', 'Opening hours'],
        ['TIMESTAMP', 'Date + time, no timezone', 'Ambiguous across regions — usually the wrong choice'],
        ['TIMESTAMPTZ', 'Date + time, stored as UTC', 'The right default for anything that happened at a moment'],
        ['INTERVAL', 'A duration', "SELECT NOW() - INTERVAL '7 days'"],
      ] },
      { type: 'warning', value: 'TIMESTAMP without timezone is the source of an entire genre of production bug. It records the wall-clock reading with no record of which clock. Use TIMESTAMPTZ for events; reserve TIMESTAMP for things genuinely without a timezone, like a recurring 09:00 local opening time.' },
      { type: 'heading', value: 'The rest of the toolbox' },
      { type: 'list', items: [
        'BOOLEAN — TRUE, FALSE or NULL. Note the three states.',
        'UUID — a 128-bit identifier, useful when ids must be generated by clients or must not be guessable.',
        'JSONB — indexed binary JSON, for genuinely variable payloads (Module 14).',
        'ARRAY — a column holding multiple values, e.g. TEXT[]. Convenient, but often a normalisation smell.',
        'ENUM — a fixed set of allowed labels, e.g. order status.',
      ] },
      { type: 'code', language: 'sql', value: "CREATE TABLE orders (\n  id           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  user_id      INT           NOT NULL REFERENCES users(id),\n  total_cents  BIGINT        NOT NULL CHECK (total_cents >= 0),\n  currency     CHAR(3)       NOT NULL DEFAULT 'INR',\n  status       TEXT          NOT NULL DEFAULT 'pending',\n  placed_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),\n  metadata     JSONB         NOT NULL DEFAULT '{}'\n);" },
      { type: 'alert', value: 'Note total_cents rather than total. Storing money as an integer count of the smallest unit sidesteps decimal questions entirely, and is what most payment systems do internally.' },
    ],
    objectives: [
      'Choose numeric types with the right range and exactness',
      'Explain why NUMERIC is required for monetary values',
      'Use TIMESTAMPTZ correctly and know when TIMESTAMP is appropriate',
    ],
    takeaways: [
      'FLOAT is approximate by design — never let it near money.',
      'TEXT is the sensible default in PostgreSQL; VARCHAR(n) only when n is a real rule.',
      'TIMESTAMPTZ stores an actual moment; TIMESTAMP stores an ambiguous reading.',
    ],
  },

  'm2-l4': {
    title: 'Constraints (PK, FK, and friends)',
    content: [
      { type: 'text', value: 'Constraints are rules the database enforces on every write, no matter which application, script or intern is doing the writing. Anything you enforce only in application code will eventually be bypassed — by a migration, a background job, or a manual fix at 2am.' },
      { type: 'heading', value: 'The six constraints you will use' },
      { type: 'table', headers: ['Constraint', 'Guarantees', 'Typical use'], rows: [
        ['PRIMARY KEY', 'Unique and never NULL; identifies the row', 'Every table should have exactly one'],
        ['FOREIGN KEY', 'The value exists in the referenced table', 'orders.user_id references users.id'],
        ['UNIQUE', 'No two rows share this value (NULLs allowed)', 'email, username, slug'],
        ['NOT NULL', 'A value is always present', 'Any column the application relies on'],
        ['CHECK', 'A custom boolean rule per row', 'price > 0, status in a known set'],
        ['DEFAULT', 'A value to use when none is supplied', 'created_at DEFAULT NOW()'],
      ] },
      { type: 'heading', value: 'Primary keys' },
      { type: 'text', value: 'A primary key answers "which row is this?" unambiguously. It must be unique, must never be NULL, and should never change — if the value can be edited, every foreign key pointing at it becomes a liability.' },
      { type: 'code', language: 'sql', value: "-- Surrogate key: a meaningless number the database generates.\n-- The safe default, because it can never need to change.\nid INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY\n\n-- Natural key: real data that happens to be unique.\n-- Fine when the value is genuinely immutable.\ncountry_code CHAR(2) PRIMARY KEY\n\n-- Composite key: uniqueness across two columns together.\n-- The standard shape for a junction table.\nPRIMARY KEY (student_id, course_id)" },
      { type: 'heading', value: 'Foreign keys and referential integrity' },
      { type: 'diagram', name: 'sql-keys', caption: 'The database refuses to create an order for a user that does not exist. That refusal is the feature.' },
      { type: 'text', value: 'A foreign key also decides what happens when the parent row is deleted. Choosing this deliberately matters — the default is to block the delete, which is often right but occasionally surprising.' },
      { type: 'table', headers: ['ON DELETE clause', 'When the parent is deleted…'], rows: [
        ['NO ACTION / RESTRICT (default)', 'The delete is rejected while children exist'],
        ['CASCADE', 'The children are deleted too — powerful and dangerous'],
        ['SET NULL', 'The child keeps existing with a NULL reference'],
        ['SET DEFAULT', 'The child is repointed at a default value'],
      ] },
      { type: 'code', language: 'sql', value: "-- Deleting a user should delete their sessions\nuser_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE\n\n-- But an order must survive: it is a financial record\nuser_id INT REFERENCES users(id) ON DELETE SET NULL" },
      { type: 'warning', value: 'ON DELETE CASCADE chains. Deleting one user can silently remove their orders, those orders’ line items, and the payments attached to them. Draw the chain before you add it, and never put it on financial or audit tables.' },
      { type: 'heading', value: 'CHECK constraints earn their keep' },
      { type: 'code', language: 'sql', value: "CREATE TABLE products (\n  id        INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  sku       TEXT NOT NULL UNIQUE,\n  price     NUMERIC(10,2) NOT NULL CHECK (price >= 0),\n  discount  NUMERIC(10,2) CHECK (discount <= price),\n  status    TEXT NOT NULL DEFAULT 'draft'\n            CHECK (status IN ('draft','active','archived'))\n);" },
      { type: 'text', value: 'Every one of those rules would otherwise live in application code, be duplicated across three services, and be forgotten by the fourth. Here it is enforced once, for everyone, forever.' },
      { type: 'alert', value: 'The general principle: put a constraint as close to the data as you can. Application validation gives users a friendly error message; the database constraint is what guarantees the rule was actually kept.' },
    ],
    objectives: [
      'Apply the six core constraints correctly',
      'Choose between surrogate, natural and composite primary keys',
      'Select an ON DELETE behaviour deliberately per relationship',
    ],
    takeaways: [
      'A rule enforced only in application code is a rule that will eventually be broken.',
      'Surrogate keys are the safe default because they never need to change.',
      'ON DELETE CASCADE chains further than you expect — map it before enabling it.',
    ],
  },
};
